--[[
    Equipence
    Copyright (c) 2026 s0high. All rights reserved.

    Source-available proprietary software. See LICENSE for terms.
]]

--@class Engine<ns>
local Engine = select(2, ...);

local FALLBACK_LOCALE = "enUS";

local Locales = {
	enUS = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Item Level %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modifiers",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Gear details when inspecting a character.",
		OPTIONS_SHOW_GEMS = "Gems",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Empty sockets",
		OPTIONS_SHOW_ENCHANTS = "Enchants",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Missing enchants",
		OPTIONS_SHOW_ITEM_LEVELS = "Item levels",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Show average item level (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "Show item levels",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Show average item level",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Decimal values",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Average item level label",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Quality color",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Text position",
		OPTIONS_SCOPE_BOTH = "Player and target",
		OPTIONS_SCOPE_PLAYER = "Player",
		OPTIONS_SCOPE_INSPECT = "Target",
		OPTIONS_SCOPE_NONE = "Disabled",
		OPTIONS_POSITION_TOP = "Top",
		OPTIONS_POSITION_BOTTOM = "Bottom",
		OPTIONS_POSITION_LEFT = "Left",
		OPTIONS_POSITION_RIGHT = "Right",
		OPTIONS_RESET_SETTINGS = "Reset settings",

		OPTIONS_VISUALS = "Appearance",
		OPTIONS_VISUALS_DESC = "Effects, animation, and element behavior.",
		OPTIONS_USE_ROUNDED_ICONS = "Icon rounding",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Matching gem shine",
		OPTIONS_SHINE_SIZE = "Shine size",
		OPTIONS_SHINE_SPEED = "Shine speed",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Show icon tooltips",
		OPTIONS_DISABLE_ICON_HOVER = "Disable Mouseover",
		OPTIONS_SHOW_QUALITY_BORDER = "Quality border",
		OPTIONS_COLOR_ITEM_QUALITY = "Quality color",

		OPTIONS_ICON_LAYOUT = "Placement",
		OPTIONS_ICON_LAYOUT_DESC = "Modifier positions, sizes, and spacing.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Preview",
		OPTIONS_SOCKET_ICON_SIZE = "Gem size",
		OPTIONS_ENCHANT_ICON_SIZE = "Enchant size",
		OPTIONS_ICON_GAP = "Spacing",
		OPTIONS_LEFT_HORIZONTAL = "Left (horizontal)",
		OPTIONS_LEFT_VERTICAL = "Left (vertical)",
		OPTIONS_RIGHT_HORIZONTAL = "Right (horizontal)",
		OPTIONS_RIGHT_VERTICAL = "Right (vertical)",
		OPTIONS_TOP_HORIZONTAL = "Top (horizontal)",
		OPTIONS_TOP_VERTICAL = "Top (vertical)",
		OPTIONS_BOTTOM_HORIZONTAL = "Bottom (horizontal)",
		OPTIONS_BOTTOM_VERTICAL = "Bottom (vertical)",

		OPTIONS_PAPERDOLL_LAYOUT = "Character Window",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Character model and stat display.",
		OPTIONS_MODEL_CENTERING = "Model centering",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Fade stats",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Hide stats",
		OPTIONS_SHOW_AMMO_SLOT = "Ammo slot",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Fade brightness",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Fade duration",
	},

	ruRU = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Ур. предметов %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Модификаторы",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Детали снаряжения при осмотре персонажа.",
		OPTIONS_SHOW_GEMS = "Камни",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Пустые гнёзда",
		OPTIONS_SHOW_ENCHANTS = "Чары",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Отсутствующие чары",
		OPTIONS_SHOW_ITEM_LEVELS = "Уровни предметов",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Показывать средний уровень (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "Отображать уровни",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Отображать средний уровень",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Десятичные доли",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Полный текст",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Цвет по качеству",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Расположение текста",
		OPTIONS_SCOPE_BOTH = "Игрок и цель",
		OPTIONS_SCOPE_PLAYER = "Игрок",
		OPTIONS_SCOPE_INSPECT = "Цель",
		OPTIONS_SCOPE_NONE = "Отключено",
		OPTIONS_POSITION_TOP = "Сверху",
		OPTIONS_POSITION_BOTTOM = "Снизу",
		OPTIONS_POSITION_LEFT = "Слева",
		OPTIONS_POSITION_RIGHT = "Справа",
		OPTIONS_RESET_SETTINGS = "Сбросить настройки",

		OPTIONS_VISUALS = "Внешний вид",
		OPTIONS_VISUALS_DESC = "Эффекты, анимация и поведение элементов.",
		OPTIONS_USE_ROUNDED_ICONS = "Округление иконок",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Сияние подходящих камней",
		OPTIONS_SHINE_SIZE = "Размер сияния",
		OPTIONS_SHINE_SPEED = "Скорость сияния",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Подсказки иконок",
		OPTIONS_DISABLE_ICON_HOVER = "Игнорировать мышь",
		OPTIONS_SHOW_QUALITY_BORDER = "Окантовка качества",
		OPTIONS_COLOR_ITEM_QUALITY = "Окраска по качеству",

		OPTIONS_ICON_LAYOUT = "Размещение",
		OPTIONS_ICON_LAYOUT_DESC = "Позиции, размеры и интервалы модификаторов.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Предпросмотр",
		OPTIONS_SOCKET_ICON_SIZE = "Размер камней",
		OPTIONS_ENCHANT_ICON_SIZE = "Размер чар",
		OPTIONS_ICON_GAP = "Интервал",
		OPTIONS_LEFT_HORIZONTAL = "Слева (горизонталь)",
		OPTIONS_LEFT_VERTICAL = "Слева (вертикаль)",
		OPTIONS_RIGHT_HORIZONTAL = "Справа (горизонталь)",
		OPTIONS_RIGHT_VERTICAL = "Справа (вертикаль)",
		OPTIONS_TOP_HORIZONTAL = "Сверху (горизонталь)",
		OPTIONS_TOP_VERTICAL = "Сверху (вертикаль)",
		OPTIONS_BOTTOM_HORIZONTAL = "Снизу (горизонталь)",
		OPTIONS_BOTTOM_VERTICAL = "Снизу (вертикаль)",

		OPTIONS_PAPERDOLL_LAYOUT = "Окно персонажа",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Модель персонажа и отображение характеристик.",
		OPTIONS_MODEL_CENTERING = "Центрирование модели",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Затухание характеристик",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Скрыть характеристики",
		OPTIONS_SHOW_AMMO_SLOT = "Слот боеприпасов",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Яркость затухания",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Длительность затухания",
	},

	deDE = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Gegenstandsstufe %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modifikatoren",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Ausrüstungsdetails beim Inspizieren eines Charakters.",
		OPTIONS_SHOW_GEMS = "Edelsteine",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Leere Sockel",
		OPTIONS_SHOW_ENCHANTS = "Verzauberungen",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Fehlende Verzauberungen",
		OPTIONS_SHOW_ITEM_LEVELS = "Gegenstandsstufen",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Durchschnittsstufe anzeigen (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "Stufen anzeigen",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Durchschnitt anzeigen",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Dezimalstellen",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Beschriftung der Durchschnittsstufe",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Qualitätsfarbe",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Textposition",
		OPTIONS_SCOPE_BOTH = "Spieler und Ziel",
		OPTIONS_SCOPE_PLAYER = "Spieler",
		OPTIONS_SCOPE_INSPECT = "Ziel",
		OPTIONS_SCOPE_NONE = "Deaktiviert",
		OPTIONS_POSITION_TOP = "Oben",
		OPTIONS_POSITION_BOTTOM = "Unten",
		OPTIONS_POSITION_LEFT = "Links",
		OPTIONS_POSITION_RIGHT = "Rechts",
		OPTIONS_RESET_SETTINGS = "Einstellungen zurücksetzen",

		OPTIONS_VISUALS = "Darstellung",
		OPTIONS_VISUALS_DESC = "Effekte, Animation und Elementverhalten.",
		OPTIONS_USE_ROUNDED_ICONS = "Symbolrundung",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Glanz passender Edelsteine",
		OPTIONS_SHINE_SIZE = "Glanzgröße",
		OPTIONS_SHINE_SPEED = "Glanzgeschwindigkeit",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Symbol-Tooltips anzeigen",
		OPTIONS_DISABLE_ICON_HOVER = "Mouseover deaktivieren",
		OPTIONS_SHOW_QUALITY_BORDER = "Qualitätsrand",
		OPTIONS_COLOR_ITEM_QUALITY = "Qualitätsfarbe",

		OPTIONS_ICON_LAYOUT = "Platzierung",
		OPTIONS_ICON_LAYOUT_DESC = "Positionen, Größen und Abstände der Modifikatoren.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Vorschau",
		OPTIONS_SOCKET_ICON_SIZE = "Edelsteingröße",
		OPTIONS_ENCHANT_ICON_SIZE = "Verzauberungsgröße",
		OPTIONS_ICON_GAP = "Abstand",
		OPTIONS_LEFT_HORIZONTAL = "Links (horizontal)",
		OPTIONS_LEFT_VERTICAL = "Links (vertikal)",
		OPTIONS_RIGHT_HORIZONTAL = "Rechts (horizontal)",
		OPTIONS_RIGHT_VERTICAL = "Rechts (vertikal)",
		OPTIONS_TOP_HORIZONTAL = "Oben (horizontal)",
		OPTIONS_TOP_VERTICAL = "Oben (vertikal)",
		OPTIONS_BOTTOM_HORIZONTAL = "Unten (horizontal)",
		OPTIONS_BOTTOM_VERTICAL = "Unten (vertikal)",

		OPTIONS_PAPERDOLL_LAYOUT = "Charakterfenster",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Charaktermodell und Attributanzeige.",
		OPTIONS_MODEL_CENTERING = "Modellzentrierung",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Attribute verblassen",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Attribute verbergen",
		OPTIONS_SHOW_AMMO_SLOT = "Munitionsplatz",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Helligkeit beim Verblassen",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Dauer des Verblassens",
	},

	frFR = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Niveau d’objet %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modificateurs",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Détails d’équipement lors de l’inspection d’un personnage.",
		OPTIONS_SHOW_GEMS = "Gemmes",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Châsses vides",
		OPTIONS_SHOW_ENCHANTS = "Enchantements",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Enchantements manquants",
		OPTIONS_SHOW_ITEM_LEVELS = "Niveaux d’objet",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Afficher le niveau moyen",
		OPTIONS_ITEM_LEVEL_SCOPE = "Afficher les niveaux",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Afficher le niveau moyen",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Décimales",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Libellé du niveau moyen",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Couleur de qualité",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Position du texte",
		OPTIONS_SCOPE_BOTH = "Joueur et cible",
		OPTIONS_SCOPE_PLAYER = "Joueur",
		OPTIONS_SCOPE_INSPECT = "Cible",
		OPTIONS_SCOPE_NONE = "Désactivé",
		OPTIONS_POSITION_TOP = "Haut",
		OPTIONS_POSITION_BOTTOM = "Bas",
		OPTIONS_POSITION_LEFT = "Gauche",
		OPTIONS_POSITION_RIGHT = "Droite",
		OPTIONS_RESET_SETTINGS = "Réinitialiser les options",

		OPTIONS_VISUALS = "Apparence",
		OPTIONS_VISUALS_DESC = "Effets, animation et comportement des éléments.",
		OPTIONS_USE_ROUNDED_ICONS = "Arrondi des icônes",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Éclat des gemmes compatibles",
		OPTIONS_SHINE_SIZE = "Taille de l’éclat",
		OPTIONS_SHINE_SPEED = "Vitesse de l’éclat",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Afficher les infobulles des icônes",
		OPTIONS_DISABLE_ICON_HOVER = "Désactiver le survol de la souris",
		OPTIONS_SHOW_QUALITY_BORDER = "Bordure de qualité",
		OPTIONS_COLOR_ITEM_QUALITY = "Couleur de qualité",

		OPTIONS_ICON_LAYOUT = "Placement",
		OPTIONS_ICON_LAYOUT_DESC = "Positions, tailles et espacements des modificateurs.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Aperçu",
		OPTIONS_SOCKET_ICON_SIZE = "Taille des gemmes",
		OPTIONS_ENCHANT_ICON_SIZE = "Taille des enchantements",
		OPTIONS_ICON_GAP = "Espacement",
		OPTIONS_LEFT_HORIZONTAL = "Gauche (horizontal)",
		OPTIONS_LEFT_VERTICAL = "Gauche (vertical)",
		OPTIONS_RIGHT_HORIZONTAL = "Droite (horizontal)",
		OPTIONS_RIGHT_VERTICAL = "Droite (vertical)",
		OPTIONS_TOP_HORIZONTAL = "Haut (horizontal)",
		OPTIONS_TOP_VERTICAL = "Haut (vertical)",
		OPTIONS_BOTTOM_HORIZONTAL = "Bas (horizontal)",
		OPTIONS_BOTTOM_VERTICAL = "Bas (vertical)",

		OPTIONS_PAPERDOLL_LAYOUT = "Fenêtre du personnage",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Modèle du personnage et affichage des caractéristiques.",
		OPTIONS_MODEL_CENTERING = "Centrage du modèle",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Estomper les caractéristiques",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Masquer les caractéristiques",
		OPTIONS_SHOW_AMMO_SLOT = "Emplacement de munitions",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Luminosité d’estompage",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Durée d’estompage",
	},

	esES = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Nivel de objeto %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modificadores",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Detalles de equipo al inspeccionar un personaje.",
		OPTIONS_SHOW_GEMS = "Gemas",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Ranuras vacías",
		OPTIONS_SHOW_ENCHANTS = "Encantamientos",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Encantamientos faltantes",
		OPTIONS_SHOW_ITEM_LEVELS = "Niveles de objeto",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Mostrar nivel medio de objeto",
		OPTIONS_ITEM_LEVEL_SCOPE = "Mostrar niveles",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Mostrar nivel medio",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Decimales",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Etiqueta del nivel medio",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Color por calidad",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Posición del texto",
		OPTIONS_SCOPE_BOTH = "Jugador y objetivo",
		OPTIONS_SCOPE_PLAYER = "Jugador",
		OPTIONS_SCOPE_INSPECT = "Objetivo",
		OPTIONS_SCOPE_NONE = "Desactivado",
		OPTIONS_POSITION_TOP = "Arriba",
		OPTIONS_POSITION_BOTTOM = "Abajo",
		OPTIONS_POSITION_LEFT = "Izquierda",
		OPTIONS_POSITION_RIGHT = "Derecha",
		OPTIONS_RESET_SETTINGS = "Restablecer ajustes",

		OPTIONS_VISUALS = "Aspecto",
		OPTIONS_VISUALS_DESC = "Efectos, animación y comportamiento de elementos.",
		OPTIONS_USE_ROUNDED_ICONS = "Redondeo de iconos",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Brillo de gemas compatibles",
		OPTIONS_SHINE_SIZE = "Tamaño del brillo",
		OPTIONS_SHINE_SPEED = "Velocidad del brillo",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Tooltips de iconos",
		OPTIONS_DISABLE_ICON_HOVER = "Ignorar ratón",
		OPTIONS_SHOW_QUALITY_BORDER = "Borde de calidad",
		OPTIONS_COLOR_ITEM_QUALITY = "Color por calidad",

		OPTIONS_ICON_LAYOUT = "Colocación",
		OPTIONS_ICON_LAYOUT_DESC = "Posiciones, tamaños e intervalos de modificadores.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Vista previa",
		OPTIONS_SOCKET_ICON_SIZE = "Tamaño de gemas",
		OPTIONS_ENCHANT_ICON_SIZE = "Tamaño de encantamientos",
		OPTIONS_ICON_GAP = "Intervalo",
		OPTIONS_LEFT_HORIZONTAL = "Izquierda (horizontal)",
		OPTIONS_LEFT_VERTICAL = "Izquierda (vertical)",
		OPTIONS_RIGHT_HORIZONTAL = "Derecha (horizontal)",
		OPTIONS_RIGHT_VERTICAL = "Derecha (vertical)",
		OPTIONS_TOP_HORIZONTAL = "Arriba (horizontal)",
		OPTIONS_TOP_VERTICAL = "Arriba (vertical)",
		OPTIONS_BOTTOM_HORIZONTAL = "Abajo (horizontal)",
		OPTIONS_BOTTOM_VERTICAL = "Abajo (vertical)",

		OPTIONS_PAPERDOLL_LAYOUT = "Ventana del personaje",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Modelo del personaje y atributos.",
		OPTIONS_MODEL_CENTERING = "Centrado del modelo",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Desvanecer atributos",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Ocultar atributos",
		OPTIONS_SHOW_AMMO_SLOT = "Ranura de munición",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Brillo del desvanecimiento",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Duración del desvanecimiento",
	},

	itIT = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Livello oggetto %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modificatori",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Dettagli equipaggiamento durante l'ispezione di un personaggio.",
		OPTIONS_SHOW_GEMS = "Gemme",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Castoni vuoti",
		OPTIONS_SHOW_ENCHANTS = "Incantamenti",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Incantamenti mancanti",
		OPTIONS_SHOW_ITEM_LEVELS = "Livelli oggetto",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Mostra livello oggetto medio",
		OPTIONS_ITEM_LEVEL_SCOPE = "Mostra livelli",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Mostra livello medio",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Decimali",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Etichetta livello medio",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Colore per qualità",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Posizione testo",
		OPTIONS_SCOPE_BOTH = "Giocatore e bersaglio",
		OPTIONS_SCOPE_PLAYER = "Giocatore",
		OPTIONS_SCOPE_INSPECT = "Bersaglio",
		OPTIONS_SCOPE_NONE = "Disattivato",
		OPTIONS_POSITION_TOP = "Alto",
		OPTIONS_POSITION_BOTTOM = "Basso",
		OPTIONS_POSITION_LEFT = "Sinistra",
		OPTIONS_POSITION_RIGHT = "Destra",
		OPTIONS_RESET_SETTINGS = "Ripristina impostazioni",

		OPTIONS_VISUALS = "Aspetto",
		OPTIONS_VISUALS_DESC = "Effetti, animazione e comportamento degli elementi.",
		OPTIONS_USE_ROUNDED_ICONS = "Arrotondamento icone",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Bagliore gemme compatibili",
		OPTIONS_SHINE_SIZE = "Dimensione bagliore",
		OPTIONS_SHINE_SPEED = "Velocità bagliore",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Tooltip icone",
		OPTIONS_DISABLE_ICON_HOVER = "Nascondi le informazioni al passaggio del puntatore",
		OPTIONS_SHOW_QUALITY_BORDER = "Bordo qualità",
		OPTIONS_COLOR_ITEM_QUALITY = "Colore per qualità",

		OPTIONS_ICON_LAYOUT = "Posizionamento",
		OPTIONS_ICON_LAYOUT_DESC = "Posizioni, dimensioni e intervalli dei modificatori.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Anteprima",
		OPTIONS_SOCKET_ICON_SIZE = "Dimensione gemme",
		OPTIONS_ENCHANT_ICON_SIZE = "Dimensione incantamenti",
		OPTIONS_ICON_GAP = "Intervallo",
		OPTIONS_LEFT_HORIZONTAL = "Sinistra (orizzontale)",
		OPTIONS_LEFT_VERTICAL = "Sinistra (verticale)",
		OPTIONS_RIGHT_HORIZONTAL = "Destra (orizzontale)",
		OPTIONS_RIGHT_VERTICAL = "Destra (verticale)",
		OPTIONS_TOP_HORIZONTAL = "Alto (orizzontale)",
		OPTIONS_TOP_VERTICAL = "Alto (verticale)",
		OPTIONS_BOTTOM_HORIZONTAL = "Basso (orizzontale)",
		OPTIONS_BOTTOM_VERTICAL = "Basso (verticale)",

		OPTIONS_PAPERDOLL_LAYOUT = "Finestra personaggio",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Modello del personaggio e attributi.",
		OPTIONS_MODEL_CENTERING = "Centratura modello",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Dissolvi attributi",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Nascondi attributi",
		OPTIONS_SHOW_AMMO_SLOT = "Slot munizioni",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Luminosità dissolvenza",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Durata dissolvenza",
	},

	ptBR = {
		AVERAGE_ITEM_LEVEL_FORMAT = "Nível de item %s",

		OPTIONS_EQUIPMENT_DISPLAY = "Modificadores",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "Detalhes de equipamento ao inspecionar um personagem.",
		OPTIONS_SHOW_GEMS = "Gemas",
		OPTIONS_SHOW_EMPTY_SOCKETS = "Engastes vazios",
		OPTIONS_SHOW_ENCHANTS = "Encantamentos",
		OPTIONS_SHOW_MISSING_ENCHANTS = "Encantamentos ausentes",
		OPTIONS_SHOW_ITEM_LEVELS = "Níveis de item",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "Mostrar nível médio dos itens",
		OPTIONS_ITEM_LEVEL_SCOPE = "Mostrar níveis",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "Mostrar nível médio",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "Decimais",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "Rótulo do nível médio",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "Cor por qualidade",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "Posição do texto",
		OPTIONS_SCOPE_BOTH = "Jogador e alvo",
		OPTIONS_SCOPE_PLAYER = "Jogador",
		OPTIONS_SCOPE_INSPECT = "Alvo",
		OPTIONS_SCOPE_NONE = "Desativado",
		OPTIONS_POSITION_TOP = "Topo",
		OPTIONS_POSITION_BOTTOM = "Baixo",
		OPTIONS_POSITION_LEFT = "Esquerda",
		OPTIONS_POSITION_RIGHT = "Direita",
		OPTIONS_RESET_SETTINGS = "Redefinir configurações",

		OPTIONS_VISUALS = "Visual",
		OPTIONS_VISUALS_DESC = "Efeitos, animação e comportamento dos elementos.",
		OPTIONS_USE_ROUNDED_ICONS = "Arredondamento dos ícones",
		OPTIONS_ANIMATE_MATCHING_GEMS = "Brilho de gemas compatíveis",
		OPTIONS_SHINE_SIZE = "Tamanho do brilho",
		OPTIONS_SHINE_SPEED = "Velocidade do brilho",
		OPTIONS_SHOW_ICON_TOOLTIPS = "Dicas dos ícones",
		OPTIONS_DISABLE_ICON_HOVER = "Desabilitar reação ao cursor do Mouse",
		OPTIONS_SHOW_QUALITY_BORDER = "Borda de qualidade",
		OPTIONS_COLOR_ITEM_QUALITY = "Cor por qualidade",

		OPTIONS_ICON_LAYOUT = "Posicionamento",
		OPTIONS_ICON_LAYOUT_DESC = "Posições, tamanhos e intervalos dos modificadores.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "Prévia",
		OPTIONS_SOCKET_ICON_SIZE = "Tamanho das gemas",
		OPTIONS_ENCHANT_ICON_SIZE = "Tamanho dos encantamentos",
		OPTIONS_ICON_GAP = "Intervalo",
		OPTIONS_LEFT_HORIZONTAL = "Esquerda (horizontal)",
		OPTIONS_LEFT_VERTICAL = "Esquerda (vertical)",
		OPTIONS_RIGHT_HORIZONTAL = "Direita (horizontal)",
		OPTIONS_RIGHT_VERTICAL = "Direita (vertical)",
		OPTIONS_TOP_HORIZONTAL = "Topo (horizontal)",
		OPTIONS_TOP_VERTICAL = "Topo (vertical)",
		OPTIONS_BOTTOM_HORIZONTAL = "Baixo (horizontal)",
		OPTIONS_BOTTOM_VERTICAL = "Baixo (vertical)",

		OPTIONS_PAPERDOLL_LAYOUT = "Janela do personagem",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "Modelo do personagem e atributos.",
		OPTIONS_MODEL_CENTERING = "Centralização do modelo",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "Esmaecer atributos",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "Ocultar atributos",
		OPTIONS_SHOW_AMMO_SLOT = "Espaço de munição",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "Brilho do esmaecimento",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "Duração do esmaecimento",
	},

	zhCN = {
		AVERAGE_ITEM_LEVEL_FORMAT = "物品等级 %s",

		OPTIONS_EQUIPMENT_DISPLAY = "装备强化",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "查看角色时显示装备细节。",
		OPTIONS_SHOW_GEMS = "宝石",
		OPTIONS_SHOW_EMPTY_SOCKETS = "空插槽",
		OPTIONS_SHOW_ENCHANTS = "附魔",
		OPTIONS_SHOW_MISSING_ENCHANTS = "缺失附魔",
		OPTIONS_SHOW_ITEM_LEVELS = "物品等级",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "显示平均等级 (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "显示等级",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "显示平均等级",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "小数",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "平均等级标签",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "品质颜色",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "文字位置",
		OPTIONS_SCOPE_BOTH = "玩家和目标",
		OPTIONS_SCOPE_PLAYER = "玩家",
		OPTIONS_SCOPE_INSPECT = "目标",
		OPTIONS_SCOPE_NONE = "禁用",
		OPTIONS_POSITION_TOP = "顶部",
		OPTIONS_POSITION_BOTTOM = "底部",
		OPTIONS_POSITION_LEFT = "左侧",
		OPTIONS_POSITION_RIGHT = "右侧",
		OPTIONS_RESET_SETTINGS = "重置设置",

		OPTIONS_VISUALS = "外观",
		OPTIONS_VISUALS_DESC = "效果、动画和元素行为。",
		OPTIONS_USE_ROUNDED_ICONS = "图标圆角",
		OPTIONS_ANIMATE_MATCHING_GEMS = "匹配宝石闪光",
		OPTIONS_SHINE_SIZE = "闪光大小",
		OPTIONS_SHINE_SPEED = "闪光速度",
		OPTIONS_SHOW_ICON_TOOLTIPS = "图标提示",
		OPTIONS_DISABLE_ICON_HOVER = "禁用鼠标悬停",
		OPTIONS_SHOW_QUALITY_BORDER = "品质边框",
		OPTIONS_COLOR_ITEM_QUALITY = "品质颜色",

		OPTIONS_ICON_LAYOUT = "位置调整",
		OPTIONS_ICON_LAYOUT_DESC = "强化项的位置、大小和间距。",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "预览",
		OPTIONS_SOCKET_ICON_SIZE = "宝石大小",
		OPTIONS_ENCHANT_ICON_SIZE = "附魔大小",
		OPTIONS_ICON_GAP = "间距",
		OPTIONS_LEFT_HORIZONTAL = "左侧（水平）",
		OPTIONS_LEFT_VERTICAL = "左侧（垂直）",
		OPTIONS_RIGHT_HORIZONTAL = "右侧（水平）",
		OPTIONS_RIGHT_VERTICAL = "右侧（垂直）",
		OPTIONS_TOP_HORIZONTAL = "上方（水平）",
		OPTIONS_TOP_VERTICAL = "上方（垂直）",
		OPTIONS_BOTTOM_HORIZONTAL = "下方（水平）",
		OPTIONS_BOTTOM_VERTICAL = "下方（垂直）",

		OPTIONS_PAPERDOLL_LAYOUT = "角色窗口",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "角色模型和属性显示。",
		OPTIONS_MODEL_CENTERING = "模型居中",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "淡化属性",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "隐藏属性",
		OPTIONS_SHOW_AMMO_SLOT = "弹药栏",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "淡化亮度",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "淡化时长",
	},

	zhTW = {
		AVERAGE_ITEM_LEVEL_FORMAT = "物品等級 %s",

		OPTIONS_EQUIPMENT_DISPLAY = "裝備強化",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "檢視角色時顯示裝備細節。",
		OPTIONS_SHOW_GEMS = "寶石",
		OPTIONS_SHOW_EMPTY_SOCKETS = "空插槽",
		OPTIONS_SHOW_ENCHANTS = "附魔",
		OPTIONS_SHOW_MISSING_ENCHANTS = "缺少的附魔",
		OPTIONS_SHOW_ITEM_LEVELS = "物品等級",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "顯示平均等級 (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "顯示等級",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "顯示平均等級",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "小數",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "平均等級標籤",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "品質顏色",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "文字位置",
		OPTIONS_SCOPE_BOTH = "玩家與目標",
		OPTIONS_SCOPE_PLAYER = "玩家",
		OPTIONS_SCOPE_INSPECT = "目標",
		OPTIONS_SCOPE_NONE = "停用",
		OPTIONS_POSITION_TOP = "上方",
		OPTIONS_POSITION_BOTTOM = "下方",
		OPTIONS_POSITION_LEFT = "左側",
		OPTIONS_POSITION_RIGHT = "右側",
		OPTIONS_RESET_SETTINGS = "重置設定",

		OPTIONS_VISUALS = "外觀",
		OPTIONS_VISUALS_DESC = "效果、動畫與元素行為。",
		OPTIONS_USE_ROUNDED_ICONS = "圖示圓角",
		OPTIONS_ANIMATE_MATCHING_GEMS = "相符寶石閃光",
		OPTIONS_SHINE_SIZE = "閃光大小",
		OPTIONS_SHINE_SPEED = "閃光速度",
		OPTIONS_SHOW_ICON_TOOLTIPS = "圖示提示",
		OPTIONS_DISABLE_ICON_HOVER = "關閉游標提示功能",
		OPTIONS_SHOW_QUALITY_BORDER = "品質邊框",
		OPTIONS_COLOR_ITEM_QUALITY = "品質顏色",

		OPTIONS_ICON_LAYOUT = "位置調整",
		OPTIONS_ICON_LAYOUT_DESC = "強化項的位置、大小與間距。",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "預覽",
		OPTIONS_SOCKET_ICON_SIZE = "寶石大小",
		OPTIONS_ENCHANT_ICON_SIZE = "附魔大小",
		OPTIONS_ICON_GAP = "間距",
		OPTIONS_LEFT_HORIZONTAL = "左側（水平）",
		OPTIONS_LEFT_VERTICAL = "左側（垂直）",
		OPTIONS_RIGHT_HORIZONTAL = "右側（水平）",
		OPTIONS_RIGHT_VERTICAL = "右側（垂直）",
		OPTIONS_TOP_HORIZONTAL = "上方（水平）",
		OPTIONS_TOP_VERTICAL = "上方（垂直）",
		OPTIONS_BOTTOM_HORIZONTAL = "下方（水平）",
		OPTIONS_BOTTOM_VERTICAL = "下方（垂直）",

		OPTIONS_PAPERDOLL_LAYOUT = "角色視窗",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "角色模型與屬性顯示。",
		OPTIONS_MODEL_CENTERING = "模型置中",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "淡化屬性",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "隱藏屬性",
		OPTIONS_SHOW_AMMO_SLOT = "彈藥欄",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "淡化亮度",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "淡化時間",
	},

	koKR = {
		AVERAGE_ITEM_LEVEL_FORMAT = "아이템 레벨 %s",

		OPTIONS_EQUIPMENT_DISPLAY = "장비 강화",
		OPTIONS_EQUIPMENT_DISPLAY_DESC = "캐릭터를 살펴볼 때 장비 정보를 표시합니다.",
		OPTIONS_SHOW_GEMS = "보석",
		OPTIONS_SHOW_EMPTY_SOCKETS = "빈 보석 홈",
		OPTIONS_SHOW_ENCHANTS = "마법부여",
		OPTIONS_SHOW_MISSING_ENCHANTS = "없는 마법부여",
		OPTIONS_SHOW_ITEM_LEVELS = "아이템 레벨",
		OPTIONS_SHOW_AVERAGE_ITEM_LEVEL = "평균 레벨 표시 (iLvl)",
		OPTIONS_ITEM_LEVEL_SCOPE = "레벨 표시",
		OPTIONS_AVERAGE_ITEM_LEVEL_SCOPE = "평균 레벨 표시",
		OPTIONS_AVERAGE_ITEM_LEVEL_DECIMALS = "소수점",
		OPTIONS_AVERAGE_ITEM_LEVEL_LABEL = "평균 레벨 문구",
		OPTIONS_AVERAGE_ITEM_LEVEL_COLOR = "품질 색상",
		OPTIONS_AVERAGE_ITEM_LEVEL_POSITION = "텍스트 위치",
		OPTIONS_SCOPE_BOTH = "플레이어 및 대상",
		OPTIONS_SCOPE_PLAYER = "플레이어",
		OPTIONS_SCOPE_INSPECT = "대상",
		OPTIONS_SCOPE_NONE = "비활성화",
		OPTIONS_POSITION_TOP = "위",
		OPTIONS_POSITION_BOTTOM = "아래",
		OPTIONS_POSITION_LEFT = "왼쪽",
		OPTIONS_POSITION_RIGHT = "오른쪽",
		OPTIONS_RESET_SETTINGS = "설정 초기화",

		OPTIONS_VISUALS = "외형",
		OPTIONS_VISUALS_DESC = "효과, 애니메이션, 요소 동작.",
		OPTIONS_USE_ROUNDED_ICONS = "아이콘 둥글기",
		OPTIONS_ANIMATE_MATCHING_GEMS = "맞는 보석 반짝임",
		OPTIONS_SHINE_SIZE = "반짝임 크기",
		OPTIONS_SHINE_SPEED = "반짝임 속도",
		OPTIONS_SHOW_ICON_TOOLTIPS = "아이콘 툴팁",
		OPTIONS_DISABLE_ICON_HOVER = "마우스 올림 무시",
		OPTIONS_SHOW_QUALITY_BORDER = "품질 테두리",
		OPTIONS_COLOR_ITEM_QUALITY = "품질 색상",

		OPTIONS_ICON_LAYOUT = "배치",
		OPTIONS_ICON_LAYOUT_DESC = "강화 요소의 위치, 크기, 간격.",
		OPTIONS_OPEN_RUNTIME_PREVIEW = "미리보기",
		OPTIONS_SOCKET_ICON_SIZE = "보석 크기",
		OPTIONS_ENCHANT_ICON_SIZE = "마법부여 크기",
		OPTIONS_ICON_GAP = "간격",
		OPTIONS_LEFT_HORIZONTAL = "왼쪽(가로)",
		OPTIONS_LEFT_VERTICAL = "왼쪽(세로)",
		OPTIONS_RIGHT_HORIZONTAL = "오른쪽(가로)",
		OPTIONS_RIGHT_VERTICAL = "오른쪽(세로)",
		OPTIONS_TOP_HORIZONTAL = "위쪽(가로)",
		OPTIONS_TOP_VERTICAL = "위쪽(세로)",
		OPTIONS_BOTTOM_HORIZONTAL = "아래쪽(가로)",
		OPTIONS_BOTTOM_VERTICAL = "아래쪽(세로)",

		OPTIONS_PAPERDOLL_LAYOUT = "캐릭터 창",
		OPTIONS_PAPERDOLL_LAYOUT_DESC = "캐릭터 모델과 능력치 표시.",
		OPTIONS_MODEL_CENTERING = "모델 중앙 정렬",
		OPTIONS_FADE_CHARACTER_ATTRIBUTES = "능력치 흐리게",
		OPTIONS_HIDE_CHARACTER_ATTRIBUTES = "능력치 숨기기",
		OPTIONS_SHOW_AMMO_SLOT = "탄약 칸",
		OPTIONS_FADED_ATTRIBUTES_ALPHA = "흐림 밝기",
		OPTIONS_ATTRIBUTES_FADE_DURATION = "흐림 시간",
	},
};

Locales.esMX = Locales.esES;

Engine.Localization = {};

function Engine.Localization:Init()
	self.fallback = Locales[FALLBACK_LOCALE];
	self.locale = Locales[GetLocale()] or self.fallback;
end

function Engine.Localization:GetLocaleText(key)
	return self.locale[key] or self.fallback[key];
end
