-- SarychUI deDE Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "Allgemein"
L["Enable"] = "Aktivieren"
L["Disable"] = "Deaktivieren"
L["Enabled"] = "Aktiviert"
L["Settings"] = "Einstellungen"
L["Options"] = "Optionen"
L["Reset"] = "Zurücksetzen"
L["Default"] = "Standard"

-- System / wow_optimize compatibility
L["System"] = "System"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Optionaler Kompatibilitätsmodus für wow_optimize.dll. Wenn aktiv, vermeidet SarychUI doppelte GC-/Kampflog-Korrekturen und drosselt schwere Nameplate- und Chatblasen-Scans."
L["WowOptimize_Mode"] = "Kompatibilitätsmodus"
L["WowOptimize_Mode_Desc"] = "Auto — Erkennung über DLL-Globals (LUABOOST_DLL_*). Aktiviert — erzwingen. Deaktiviert — normales SarychUI."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Aktiviert"
L["WowOptimize_Mode_Disabled"] = "Deaktiviert"
L["WowOptimize_Debug"] = "Kompatibilitäts-Debugprotokoll"
L["WowOptimize_Debug_Desc"] = "Angewandte Anpassungen im Chat ausgeben (oder DEBUG_WOW_OPTIMIZE_COMPAT = true setzen)."
L["System_Overview"] = "Übersicht"
L["Dll_Detection_Header"] = "DLL-Erkennung"
L["Dll_Status_Detected"] = "Erkannt"
L["Dll_Status_NotDetected"] = "Nicht erkannt"
L["Dll_Status_Checking"] = "Prüfe..."
L["Dll_Status_NoMarker"] = "Kein Lua-Marker"
L["Dll_Status_ApiDetected"] = "API erkannt"
L["Dll_Status_WaitingNameplates"] = "Warte auf Namensplaketten"
L["Runtime_LuaOptimize"] = "Lua-Optimierung"
L["Runtime_EnableGC"] = "Garbage-Collection-Manager aktivieren"
L["Runtime_EnableGC_Desc"] = "Inkrementelle GC je Modus (normal / Kampf / Leerlauf / Laden). Bei aktiver wow_optimize.dll übernimmt die DLL die GC."
L["Runtime_Preset"] = "GC-Profil"
L["Runtime_Preset_Light"] = "Leicht"
L["Runtime_Preset_Standard"] = "Standard"
L["Runtime_Preset_Heavy"] = "Schwer"
L["Runtime_Preset_Custom"] = "Benutzerdefiniert"
L["Runtime_StepNormal"] = "GC step (normal), KB"
L["Runtime_StepCombat"] = "GC step (Kampf), KB"
L["Runtime_StepIdle"] = "GC step (Leerlauf), KB"
L["Runtime_StepLoading"] = "GC step (Laden), KB"
L["Runtime_EmergencyMB"] = "Schwelle für Notfall-Voll-GC, MB"
L["Runtime_IdleTimeout"] = "Leerlauf-Timeout, Sek"
L["Runtime_SpeedyLoad"] = "Ladebildschirm-Optimierung"
L["Runtime_SpeedyLoadMode"] = "Lademodus"
L["Runtime_SpeedyLoadSafe"] = "Sicher"
L["Runtime_SpeedyLoadAggressive"] = "Aggressiv"
L["Runtime_Debug"] = "Diagnoseausgabe"
L["Runtime_DllStatus"] = "Status von wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "GC wird von wow_optimize.dll gesteuert — Lua-Stepping ist deaktiviert."
L["Runtime_ForceGC"] = "Jetzt vollständig sammeln (außerhalb des Kampfes)"
L["Runtime_ForceGC_Desc"] = "Führt außerhalb des Kampfes eine vollständige Garbage Collection aus. Im Kampf nicht verfügbar."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost erkannt. Die GC-Verwaltung von SarychUI ist deaktiviert, um Konflikte zu vermeiden. Deaktiviere oder entferne !LuaBoost, um diese Option zu nutzen."

-- Modules
L["Modules"] = "Module"
L["Auto Confirm"] = "Autom. Bestätigung"
L["Crowd Control"] = "Massenkontrolle"
L["Cooldown Text"] = "Abklingzeiten und Timer"
L["Font_Path"] = "Schriftpfad"
L["Font_Path_Desc"] = "Vollständiger Pfad zur .ttf (z. B. Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Schriftstil"
L["Font_Flags_Desc"] = "Optionen: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Textgröße (< 60s)"
L["Font_Size_Small_Desc"] = "Textgröße für verbleibende Zeit unter 60 Sekunden"
L["Font_Size_Medium"] = "Textgröße (1–10 Min)"
L["Font_Size_Medium_Desc"] = "Textgröße für 1:00–9:59 und ≥10 Minuten"
L["Font_Size_Large"] = "Textgröße (>10 Min)"
L["Font_Size_Large_Desc"] = "Textgröße für Minutenwerte ≥ 10"
L["Default_Color"] = "Standard-Textfarbe"
L["Appearance"] = "Darstellung"
L["Display_Conditions"] = "Anzeigebedingungen"
L["Behavior"] = "Verhalten"
L["Min_Scale"] = "Minimale Skalierung"
L["Min_Scale_Desc"] = "Text ausblenden, wenn die effektive Symbolskalierung kleiner ist"
L["Min_Icon_Size"] = "Minimale Symbolgröße"
L["Min_Icon_Size_Desc"] = "Text ausblenden, wenn Symbolbreite/-höhe kleiner ist"
L["Hide_On_GCD"] = "Bei GCD ausblenden"
L["Hide_On_GCD_Desc"] = "Abklingzeitentext bei Fähigkeiten mit globaler Abklingzeit ausblenden (GCD ~1.5 Sek)"
L["Chat"] = "Chat"
L["Error Filter"] = "Fehlerfilter"
L["Frame"] = "Fenster"
L["Frames"] = "Fenster"
L["Auras"] = "Auren"
L["Frame Auras"] = "Fenster-Auren"
L["Character Auras"] = "Charakter-Auren"
L["MainMenuBar"] = "Aktionsleiste"
L["MainMenuBar_Description"] = "Passe die Aktionsleiste mit Hotkey-Verwaltung und Makronamen an."
L["Enable_Module"] = "Modul aktivieren"
L["Enable_Module_Desc"] = "Das Aktionsleisten-Modul vollständig aktivieren oder deaktivieren."
L["Hotkeys"] = "Hotkeys"
L["Color Indication"] = "Farbanzeige"
L["Color_Indication_Enabled"] = "Farbanzeige aktivieren"
L["Color_Indication_Enabled_Desc"] = "Farbanzeige für Aktionsleisten-Schaltflächen aktivieren oder deaktivieren"
L["Color_Cooldown_Enabled"] = "Bei Abklingzeit ausgegraut"
L["Color_Cooldown_Enabled_Desc"] = "Schaltflächen grau färben, wenn die Abklingzeit länger als 1.5 Sekunden ist"
L["Color_Cooldown_Alpha"] = "Abklingzeit-Alpha"
L["Color_Cooldown_Alpha_Desc"] = "Alphawert für Schaltflächen auf Abklingzeit (0 - unsichtbar, 1 - Standard)"
L["Color_Mana_Enabled"] = "Blau bei unzureichenden Ressourcen"
L["Color_Mana_Enabled_Desc"] = "Schaltflächen blau färben bei Mangel an Mana, Energie oder Wut"
L["Color_Range_Enabled"] = "Rot außer Reichweite"
L["Color_Range_Enabled_Desc"] = "Schaltflächen rot färben, wenn das Ziel außer Reichweite ist"
L["Color_Unusable_Enabled"] = "Dunkelgrau wenn nicht nutzbar"
L["Color_Unusable_Enabled_Desc"] = "Schaltflächen dunkelgrau färben, wenn die Fähigkeit nicht nutzbar ist"
L["Interface"] = "Benutzeroberfläche"
L["Visual"] = "Text"
L["Hide_Hotkeys"] = "Hotkeys ausblenden"
L["Hide_Hotkeys_Desc"] = "Hotkey-Text auf Aktionsleisten-Schaltflächen ausblenden"
L["Show_In_Combat"] = "Im Kampf anzeigen"
L["Show_In_Combat_Desc"] = "Hotkeys im Kampf anzeigen, auch wenn sie ausgeblendet sind"
L["Show_On_Alt"] = "Bei |cFFFFD700Alt|r anzeigen"
L["Show_On_Alt_Desc"] = "Hotkeys anzeigen, während |cFFFFD700Alt|r gedrückt gehalten wird"
L["Show_With_Target"] = "Bei ausgewähltem Ziel anzeigen"
L["Show_With_Target_Desc"] = "Solange ein Ziel ausgewählt ist, Hotkeys anzeigen (wenn ausgeblendet); sie verschwinden wieder, wenn das Ziel gelöscht wird. Funktioniert mit Kampf- und Alt-Sichtbarkeit. Beeinflusst keine Makronamen."
L["Fade_After_Combat"] = "Nach dem Kampf ausblenden"
L["Fade_After_Combat_Desc"] = "Sanftes Ein-/Ausblenden der Hotkeys nach dem Kampf"
L["Fade_Time"] = "Überblendzeit"
L["Fade_Time_Desc"] = "Dauer des sanften Hotkey-Ein-/Ausblendens (in Sekunden)"
L["Macros"] = "Makros"
L["Hide_Macro_Names"] = "Makronamen ausblenden"
L["Hide_Macro_Names_Desc"] = "Makronamen auf Aktionsleisten-Schaltflächen ausblenden"
L["Hide Hotkeys"] = "Hotkeys ausblenden"
L["Show in Combat"] = "Im Kampf anzeigen"
L["Show on Alt"] = "Bei |cFFFFD700Alt|r anzeigen"
L["Fade After Combat"] = "Nach dem Kampf ausblenden"
L["Fade Time"] = "Überblendzeit"
L["Hide Macro Names"] = "Makronamen ausblenden"
L["Color Indication Enabled"] = "Farbanzeige aktivieren"
L["Cooldown Color"] = "Abklingzeitfarbe"
L["Cooldown Alpha"] = "Abklingzeit-Alpha"
L["Mana Color"] = "Manafarbe"
L["Range Color"] = "Reichweitenfarbe"
L["Unusable Color"] = "Farbe nicht nutzbar"
L["Show Panels on Alt"] = "Leisten bei |cFFFFD700Alt|r anzeigen"
L["Hide Gryphons"] = "Greifen ausblenden"
L["Hide Decorative Elements"] = "Dekorative Elemente ausblenden"
L["Hide Action Bar Backgrounds"] = "Aktionsleisten-Hintergründe ausblenden"
L["Hide Shapeshift Backgrounds"] = "Gestaltwandel-Hintergründe ausblenden"
L["Hide Pet Bar Backgrounds"] = "Begleiterleisten-Hintergründe ausblenden"
L["Hide Possess Bar Backgrounds"] = "Besitzleisten-Hintergründe ausblenden"
L["Hide Bonus Bar Textures"] = "Bonusleisten-Texturen ausblenden"
L["Hide Keyring Button"] = "Schlüsselbund-Schaltfläche ausblenden"
L["Hide Page Buttons"] = "Seiten-Schaltflächen ausblenden"
L["Hide Max Level Bar"] = "Maximalstufenleiste ausblenden"
L["Hide Page Numbers"] = "Seitenzahlen ausblenden"
L["Show Page Numbers in Combat"] = "Seitenzahlen im Kampf anzeigen"
L["Show Page Numbers on Alt"] = "Seitenzahlen bei |cFFFFD700Alt|r anzeigen"
L["Page Numbers Fade After Combat"] = "Seitenzahlen nach Kampf ausblenden"
L["Page Numbers Fade Time"] = "Überblendzeit der Seitenzahlen"
L["Hide Exp Bar"] = "EP-Leiste ausblenden"
L["Show Exp Bar on Alt"] = "EP-Leiste bei |cFFFFD700Alt|r anzeigen"
L["Show Exp Bar on Gain"] = "EP-Leiste bei Gewinn anzeigen"
L["Exp Bar Fade Time"] = "Überblendzeit der EP-Leiste"
L["Exp Bar Show Time"] = "Anzeigedauer der EP-Leiste"
L["Hide Rep Bar"] = "Rufleiste ausblenden"
L["Show Rep Bar on Alt"] = "Rufleiste bei |cFFFFD700Alt|r anzeigen"
L["Show_Reputation_Bar_On_Gain"] = "Bei Rufänderung anzeigen"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Zeigt die Rufleiste vorübergehend an, wenn Ruf gewonnen oder verloren wird."
L["Reputation_Bar_Fade_Time"] = "Überblenddauer der Rufleiste"
L["Reputation_Bar_Fade_Time_Desc"] = "Dauer der Ein-/Ausblendanimation der Rufleiste."
L["Reputation_Bar_Show_Time"] = "Anzeigedauer der Rufleiste"
L["Reputation_Bar_Show_Time_Desc"] = "Wie lange die Rufleiste nach einer Rufänderung sichtbar bleibt."
L["Button Border Alpha"] = "Alpha des Schaltflächenrands"
L["Micro Menu Alpha"] = "Alpha des Mikromenüs"
L["Button Border Alpha Enabled"] = "Alpha des Schaltflächenrands aktivieren"
L["Micro Menu Alpha Enabled"] = "Alpha des Mikromenüs aktivieren"
L["Minimap"] = "Minikarte"
L["Nameplates"] = "Namensplaketten"
L["Plates Auras"] = "Plaketten-Auren"
L["Health Indicators"] = "Gesundheitsanzeigen"
L["Health Indicators Desc"] = "Wähle das System für Gesundheitsanzeigen / Namensplaketten."
L["Health Indicator Type"] = "Typ der Gesundheitsanzeige"
L["Health Indicator Type Desc"] = "ElvUI nutzt eingebettete ElvUI-Namensplaketten. Classic WoW nutzt die Standard-Namensplaketten von Blizzard."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Anzeigeeinstellungen werden bearbeitet für: %s"
L["Health Indicators Reload Notice"] = "Ein UI-Neuladen ist erforderlich, um die Änderung des Gesundheitsanzeige-Typs vollständig anzuwenden."
L["Open ElvUI NamePlates Settings"] = "Einstellungen"
L["Open ElvUI NamePlates Settings Desc"] = "Das ElvUI-NamePlates-Konfigurationsfenster öffnen (/enp)."
L["Arena Frame Type"] = "Arenafenster-Typ"
L["Arena Frame Type Desc"] = "GladiusEx nutzt eingebettete GladiusEx-Arenafenster. Classic WoW nutzt das Standard-Arenamodul von SarychUI."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "GladiusEx-Einstellungen öffnen"
L["Open GladiusEx Settings Desc"] = "Das GladiusEx-Konfigurationsfenster öffnen (/gex ui)."
L["Arena Classic Settings Disabled"] = "Diese Einstellungen sind nur im Classic-WoW-Modus verfügbar."
L["Map"] = "Weltkarte"
L["World Map"] = "Weltkarte"
L["Map Module Desc"] = "Wähle, welches Karten-Addon verwendet werden soll."
L["Map Type"] = "Kartentyp"
L["Map Type Desc"] = "Wähle, welches Karten-Addon verwendet werden soll."
L["Classic WoW Map"] = "Classic-WoW-Karte"
L["Open Mapster Settings"] = "Mapster-Einstellungen öffnen"
L["Open Mapster Settings Desc"] = "Das Mapster-Konfigurationsfenster öffnen (/mapster)."
L["Open Carbonite Settings"] = "Carbonite-Einstellungen öffnen"
L["Open Carbonite Settings Desc"] = "Das Carbonite-Konfigurationsfenster öffnen (/carb options)."
L["Map Type Reload"] = "Ein UI-Neuladen ist erforderlich, um die Änderung des Kartentyps anzuwenden."
L["Nameplate Distance"] = "Entfernungsanzeige aktivieren"
L["Nameplate Distance Desc"] = "Erfordert nameplate_range.dll. Status: System -> Übersicht."
L["Nameplate Distance Tab"] = "Namensplaketten-Entfernung"
L["Nameplate Distance Font Desc"] = "Schriftart für den Entfernungstext auf Namensplaketten."
L["Nameplate Distance Font Size Desc"] = "Schriftgröße für den Entfernungstext."
L["Nameplate Distance Offset X Desc"] = "Horizontaler Versatz des Entfernungstexts."
L["Nameplate Distance Offset Y Desc"] = "Vertikaler Versatz des Entfernungstexts."
L["Font Size"] = "Schriftgröße"
L["Position X"] = "Position X"
L["Position Y"] = "Position Y"
L["Font Outline"] = "Schriftkontur"
L["Nameplate Distance Font Outline Desc"] = "Konturstil des Entfernungstexts (gleiche Optionen wie ElvUI NamePlates)."
L["Shadow X"] = "Schatten X"
L["Shadow Y"] = "Schatten Y"
L["Nameplate Distance Shadow X Desc"] = "Horizontaler Schattenversatz des Entfernungstexts."
L["Nameplate Distance Shadow Y Desc"] = "Vertikaler Schattenversatz des Entfernungstexts."
L["None"] = "Keine"
L["Reload UI"] = "UI neu laden"
L["Reload UI Desc"] = "/reload ausführen, um Änderungen anzuwenden."
L["Tools"] = "Sonstiges"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "Das Modul Autom. Bestätigung bestätigt verschiedene Dialoge automatisch."
L["Crowd Control module displays CC effects on your screen."] = "Das Modul Massenkontrolle zeigt CC-Effekte auf dem Bildschirm an."
L["Chat module enhances the chat interface with additional features."] = "Das Chat-Modul erweitert die Chat-Oberfläche um zusätzliche Funktionen."
L["Error Filter module filters out annoying error messages."] = "Das Fehlerfilter-Modul filtert störende Fehlermeldungen heraus."
L["Frame module allows you to move and customize unit frames."] = "Das Fenstermodul ermöglicht das Verschieben und Anpassen von Einheitsfenstern."
L["Main Menu Bar module customizes the main action bar."] = "Das Aktionsleisten-Modul passt die Hauptaktionsleiste an."
L["Minimap module enhances and customizes the minimap."] = "Das Minikarten-Modul verbessert und passt die Minikarte an."
L["Plates Auras module displays auras on nameplates."] = "Das Modul Plaketten-Auren zeigt Auren auf Namensplaketten an."
L["Tools module provides various utility functions."] = "Das Modul Sonstiges bietet verschiedene Hilfsfunktionen."

-- Module description keys for options
L["Frames_Description"] = "Einstellungen zur Anpassung von Einheitsfenstern"
L["Auras_Description"] = "Ausblenden von Auren, Hervorheben von Bannungen und Verwaltung des Spieler-Bufffensters"
L["Minimap_Description"] = "Minikarten-Einstellungen"
L["Chat_Description"] = "Chat- und Nachrichteneinstellungen"
L["Tools_Description"] = "Verschiedene Werkzeuge und Hilfsmittel"
L["MainMenuBar_Description"] = "Einstellungen der Hauptbefehlsleiste und der Aktionsleisten"
L["CooldownText_Description"] = "Einstellungen für Abklingzeitentext und Timeranzeige"
L["Automation_Description"] = "Automatisierung verschiedener Spielaktionen"

-- Auto Confirm
L["Confirm Loot"] = "Beute bestätigen"
L["Automatically confirm loot rolls."] = "Beutewürfe automatisch bestätigen."
L["Confirm Bind"] = "Bindung bestätigen"
L["Automatically confirm binding items."] = "Das Binden von Gegenständen automatisch bestätigen."
L["Confirm Delete"] = "Löschen bestätigen"
L["Automatically confirm item deletion."] = "Das Löschen von Gegenständen automatisch bestätigen."
L["Confirm Quest"] = "Quest bestätigen"
L["Automatically confirm quest dialogs."] = "Questdialoge automatisch bestätigen."

-- Crowd Control
L["Show Icon"] = "Symbol anzeigen"
L["Show CC icon when you are affected by crowd control."] = "CC-Symbol anzeigen, wenn du von Massenkontrolle betroffen bist."
L["Icon Size"] = "Symbolgröße"
L["Size of the CC icon."] = "Größe des CC-Symbols."
L["Icon Position"] = "Symbolposition"
L["Position of the CC icon on screen."] = "Position des CC-Symbols auf dem Bildschirm."
L["Show Timer"] = "Timer anzeigen"
L["Show remaining time on CC effects."] = "Verbleibende Zeit von CC-Effekten anzeigen."

-- Chat
L["Chat Bar"] = "Chatleiste"
L["Enable chat bar with quick channel buttons."] = "Chatleiste mit schnellen Kanalschaltflächen aktivieren."
L["Position"] = "Position"
L["Chat bar position."] = "Position der Chatleiste."
L["Timestamps"] = "Zeitstempel"
L["Show timestamps in chat."] = "Zeitstempel im Chat anzeigen."
L["Class Colors"] = "Klassenfarben"
L["Color player names by class."] = "Spielernamen nach Klasse einfärben."
L["Short Channel Names"] = "Kurze Kanalnamen"
L["Use abbreviated channel names."] = "Abgekürzte Kanalnamen verwenden."

-- Error Filter
L["Filters"] = "Filter"
L["Configure which errors to filter."] = "Festlegen, welche Fehler gefiltert werden."

-- Frame
L["Move Frames"] = "Fenster verschieben"
L["Allow moving unit frames."] = "Verschieben von Einheitsfenstern erlauben."
L["Combat Indicator"] = "Kampfindikator"
L["Show combat indicator on frames."] = "Kampfindikator auf Fenstern anzeigen."
L["Size"] = "Größe"
L["Frame Text"] = "Fenstertext"
L["Show Name"] = "Namen anzeigen"
L["Show Level"] = "Stufe anzeigen"
L["Show Class"] = "Klasse anzeigen"

-- Main Menu Bar
L["Hide Art"] = "Grafik ausblenden"
L["Hide background art from the main menu bar."] = "Hintergrundgrafik der Hauptmenüleiste ausblenden."
L["Hide Gryphons"] = "Greifen ausblenden"
L["Hide the gryphon decorations."] = "Die Greifen-Verzierungen ausblenden."
L["Show Buttons"] = "Schaltflächen anzeigen"
L["Configure which buttons to show."] = "Festlegen, welche Schaltflächen angezeigt werden."

-- Minimap
L["Shape"] = "Form"
L["Minimap shape (square or round)."] = "Form der Minikarte (quadratisch oder rund)."
L["Square"] = "Quadratisch"
L["Round"] = "Rund"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Zoom-Schaltflächen aktivieren."

-- Plates Auras
L["Show Buffs"] = "Buffs anzeigen"
L["Display buffs on nameplates."] = "Buffs auf Namensplaketten anzeigen."
L["Show Debuffs"] = "Debuffs anzeigen"
L["Display debuffs on nameplates."] = "Debuffs auf Namensplaketten anzeigen."
L["Max Icons"] = "Max. Symbole"
L["Maximum number of icons to display."] = "Maximale Anzahl anzuzeigender Symbole."
L["Only Mine"] = "Nur eigene"
L["Only show auras cast by you."] = "Nur von dir gewirkte Auren anzeigen."
L["Show Duration"] = "Dauer anzeigen"
L["Display remaining duration on auras."] = "Verbleibende Dauer von Auren anzeigen."
L["Spell Settings"] = "Zauber-Einstellungen"
L["Visibility"] = "Sichtbarkeit"
L["Show this spell on nameplates"] = "Diesen Zauber auf Namensplaketten anzeigen"
L["Spell Type"] = "Zaubertyp"
L["Type"] = "Typ"
L["Spell Priority"] = "Zauberpriorität"
L["Custom Priority"] = "Benutzerdefinierte Priorität"
L["Priority"] = "Priorität"
L["Higher priority spells will take precedence regardless of duration"] = "Zauber mit höherer Priorität haben Vorrang, unabhängig von der Dauer"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC als OK"
L["Allow ESC key to confirm dialogs."] = "ESC-Taste zum Bestätigen von Dialogen erlauben."
L["No Combat Errors"] = "Keine Fehler im Kampf"
L["Hide errors during combat."] = "Fehler während des Kampfes ausblenden."
L["Speedy Load"] = "Schnelles Laden"
L["Faster addon loading."] = "Schnelleres Laden von Addons."

-- Positions
L["Top"] = "Oben"
L["Bottom"] = "Unten"
L["Left"] = "Links"
L["Right"] = "Rechts"
L["Center"] = "Mitte"
L["Top Left"] = "Oben links"
L["Top Right"] = "Oben rechts"
L["Bottom Left"] = "Unten links"
L["Bottom Right"] = "Unten rechts"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Strg+Klick auf Tab – |cFFFFD700Kopierfenster|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Chat-Kopieren per Strg+Klick auf den Chat-Tab aktivieren"
L["Messages"] = "Nachrichten: %d"
L["Drag_to_size"] = "Ziehen zum Anpassen der Größe | Rechtsklick zum Schließen"

-- Tooltip Settings
L["Tooltip_Settings"] = "Fenstereinstellungen"
L["Enable_Tooltip_Position"] = "Fensterposition ändern"
L["Enable_Tooltip_Position_Desc"] = "Benutzerdefinierte Positionierung des Tooltip-Fensters aktivieren"
L["Tooltip_Base_Offset"] = "Basisversatz"
L["Tooltip_Base_Offset_Desc"] = "Basisversatz für das Tooltip-Fenster"
L["Tooltip_Pet_Offset"] = "Begleiterversatz"
L["Tooltip_Pet_Offset_Desc"] = "Zusätzlicher Versatz des Tooltip-Fensters bei aktivem Begleiter"
L["Enable_Chat_Icons"] = "Symbole im Tooltip-Fenster anzeigen"
L["Enable_Chat_Icons_Desc"] = "Symbole für Gegenstände, Zauber und Erfolge in Chatnachrichten anzeigen"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Freunde-Schaltfläche ausblenden"
L["Enable_Friends_Button_Mod_Desc"] = "Freunde-Schaltfläche im Chat ausblenden"
L["Enable_Hide_Chat_Frame_Button"] = "Kommunikations-Schaltfläche ausblenden"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Kommunikations-Schaltfläche ausblenden"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Kommunikations-Schaltfläche im Chat ausblenden"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Pfeile nach oben und unten ausblenden"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Scrollpfeile nach oben und unten im Chat ausblenden"
L["Enable_Hide_Chat_Bottom_Button"] = "Zum-Ende-Pfeil ausblenden"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Zum-Ende-Pfeil im Chat ausblenden"

-- Chat Animations
L["Chat_Animations"] = "Chat-Animationen"
L["Enable_Chat_Animations"] = "Chat-Animationen aktivieren"
L["Enable_Chat_Animations_Desc"] = "Benutzerdefinierte Chat-Animationen aktivieren"
L["Chat_Tab_Show_Delay"] = "Verzögerung Tab-Anzeige (Sek)"
L["Chat_Tab_Show_Delay_Desc"] = "Verzögerung vor dem Anzeigen der Chat-Tabs"
L["Chat_Tab_Hide_Delay"] = "Verzögerung Tab-Ausblenden (Sek)"
L["Chat_Tab_Hide_Delay_Desc"] = "Verzögerung vor dem Ausblenden der Chat-Tabs"
L["Chat_Frame_Fade_Time"] = "Einblenddauer (Sek)"
L["Chat_Frame_Fade_Time_Desc"] = "Dauer der Chat-Erscheinungsanimation"
L["Chat_Frame_Fade_Out_Time"] = "Ausblenddauer (Sek)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Dauer der Chat-Verschwindungsanimation"

-- Messages
L["Profile reset to defaults."] = "Profil auf Standardeinstellungen zurückgesetzt."
L["Module enabled."] = "Modul aktiviert."
L["Module disabled."] = "Modul deaktiviert."

SarychUI.RegisterLocale("deDE", L)
