-- SarychUI English Localization (enUS) — default / fallback pack

local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "General"
L["Enable"] = "Enable"
L["Disable"] = "Disable"
L["Enabled"] = "Enabled"
L["Settings"] = "Settings"
L["Options"] = "Options"
L["Reset"] = "Reset"
L["Default"] = "Default"

-- System / wow_optimize compatibility
L["System"] = "System"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Optional compatibility mode for wow_optimize.dll. When active, SarychUI avoids duplicating GC/combat log fixes and throttles heavy nameplate and chat bubble scans."
L["WowOptimize_Mode"] = "Compatibility mode"
L["WowOptimize_Mode_Desc"] = "Auto — detect via DLL globals (LUABOOST_DLL_*). Enabled — force on. Disabled — normal SarychUI."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Enabled"
L["WowOptimize_Mode_Disabled"] = "Disabled"
L["WowOptimize_Debug"] = "Compatibility debug log"
L["WowOptimize_Debug_Desc"] = "Print applied adaptations to chat (or set DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Overview"
L["Dll_Detection_Header"] = "DLL Detection"
L["Dll_Status_Detected"] = "Detected"
L["Dll_Status_NotDetected"] = "Not detected"
L["Dll_Status_Checking"] = "Checking..."
L["Dll_Status_NoMarker"] = "No Lua marker"
L["Dll_Status_ApiDetected"] = "API detected"
L["Dll_Status_WaitingNameplates"] = "Waiting for nameplates"
L["Runtime_LuaOptimize"] = "Lua Optimization"
L["Runtime_EnableGC"] = "Enable garbage collection manager"
L["Runtime_EnableGC_Desc"] = "Incremental GC by mode (normal / combat / idle / loading). When wow_optimize.dll is active, GC is owned by the DLL."
L["Runtime_Preset"] = "GC profile"
L["Runtime_Preset_Light"] = "Light"
L["Runtime_Preset_Standard"] = "Standard"
L["Runtime_Preset_Heavy"] = "Heavy"
L["Runtime_Preset_Custom"] = "Custom"
L["Runtime_StepNormal"] = "GC step (normal), KB"
L["Runtime_StepCombat"] = "GC step (combat), KB"
L["Runtime_StepIdle"] = "GC step (idle), KB"
L["Runtime_StepLoading"] = "GC step (loading), KB"
L["Runtime_EmergencyMB"] = "Emergency full GC threshold, MB"
L["Runtime_IdleTimeout"] = "Idle timeout, sec"
L["Runtime_SpeedyLoad"] = "Loading screen optimization"
L["Runtime_SpeedyLoadMode"] = "Loading mode"
L["Runtime_SpeedyLoadSafe"] = "Safe"
L["Runtime_SpeedyLoadAggressive"] = "Aggressive"
L["Runtime_Debug"] = "Diagnostic output"
L["Runtime_DllStatus"] = "wow_optimize.dll status"
L["Runtime_DllOwnsGC"] = "GC is owned by wow_optimize.dll — Lua stepping is disabled."
L["Runtime_ForceGC"] = "Full collect now (out of combat)"
L["Runtime_ForceGC_Desc"] = "Runs a full garbage collect outside combat. Unavailable in combat."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost detected. SarychUI GC management is disabled to avoid conflicts. Disable or remove !LuaBoost to use this option."
L["Runtime_NotLoaded"] = "Runtime module is not loaded"
L["Runtime_Controller"] = "GC controller"
L["Runtime_Mode"] = "Mode"
L["Runtime_Memory"] = "Lua memory"
L["Runtime_Settings"] = "Operating mode"
L["Runtime_Preset_Desc"] = "A ready-made balance between frame smoothness and memory cleanup speed."
L["Runtime_UICache"] = "Redundant StatusBar update cache"
L["Runtime_UICache_Desc"] = "Skips repeated engine calls when health, resource, or progress bars receive the same value."
L["Runtime_UICacheDLL"] = "handled by DLL"
L["Runtime_UICacheActive"] = "active, %d redundant calls skipped"
L["Runtime_UICacheDisabled"] = "disabled"
L["Runtime_UICacheWaiting"] = "waiting to activate"
L["Runtime_AutomaticNote"] = "Combat, idle, and loading steps are selected by the profile automatically. The emergency threshold raises itself if a full collection takes too long."


-- Modules
L["Modules"] = "Modules"
L["Auto Confirm"] = "Auto Confirm"
L["Crowd Control"] = "Crowd Control"
L["Cooldown Text"] = "Cooldowns and Timers"
L["Font_Path"] = "Font Path"
L["Font_Path_Desc"] = "Full path to .ttf (e.g. Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Font Style"
L["Font_Flags_Desc"] = "Options: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Text Size (< 60s)"
L["Font_Size_Small_Desc"] = "Text size for remaining time under 60 seconds"
L["Font_Size_Medium"] = "Text Size (1–10 min)"
L["Font_Size_Medium_Desc"] = "Text size for 1:00–9:59 and ≥10 minutes"
L["Font_Size_Large"] = "Text Size (>10 min)"
L["Font_Size_Large_Desc"] = "Text size for minute values ≥ 10"
L["Default_Color"] = "Default Text Color"
L["Appearance"] = "Appearance"
L["Display_Conditions"] = "Display Conditions"
L["Behavior"] = "Behavior"
L["Min_Scale"] = "Minimum Scale"
L["Min_Scale_Desc"] = "Hide text when effective icon scale is lower"
L["Min_Icon_Size"] = "Minimum Icon Size"
L["Min_Icon_Size_Desc"] = "Hide text if icon width/height is smaller"
L["Hide_On_GCD"] = "Hide on GCD"
L["Hide_On_GCD_Desc"] = "Hide cooldown text on abilities with global cooldown (GCD ~1.5 sec)"
L["Chat"] = "Chat"
L["Error Filter"] = "Error Filter"
L["Frame"] = "Frames"
L["Frames"] = "Frames"
L["Auras"] = "Auras"
L["Frame Auras"] = "Frame Auras"
L["Character Auras"] = "Character Auras"
L["MainMenuBar"] = "Action Bar"
L["MainMenuBar_Description"] = "Customize the action bar with hotkey management and macro name settings."
L["Enable_Module"] = "Enable Module"
L["Enable_Module_Desc"] = "Enable or disable the Action Bar module completely."
L["Hotkeys"] = "Hotkeys"
L["Color Indication"] = "Color Indication"
L["Color_Indication_Enabled"] = "Enable Color Indication"
L["Color_Indication_Enabled_Desc"] = "Enable or disable color indication for action bar buttons"
L["Color_Cooldown_Enabled"] = "Grayed Out on Cooldown"
L["Color_Cooldown_Enabled_Desc"] = "Make buttons gray when on cooldown for more than 1.5 seconds"
L["Color_Cooldown_Alpha"] = "Cooldown Alpha"
L["Color_Cooldown_Alpha_Desc"] = "Alpha value for buttons on cooldown (0 - invisible, 1 - default)"
L["Color_Mana_Enabled"] = "Blue Color for Insufficient Resources"
L["Color_Mana_Enabled_Desc"] = "Make buttons blue when lacking mana, energy, or rage"
L["Color_Range_Enabled"] = "Red Color Out of Range"
L["Color_Range_Enabled_Desc"] = "Make buttons red when target is out of range"
L["Color_Unusable_Enabled"] = "Dark Gray Color When Unusable"
L["Color_Unusable_Enabled_Desc"] = "Make buttons dark gray when ability is unusable"
L["Interface"] = "Interface"
L["Visual"] = "Text"
L["Hide_Hotkeys"] = "Hide Hotkeys"
L["Hide_Hotkeys_Desc"] = "Hide hotkey text on action bar buttons"
L["Show_In_Combat"] = "Show in Combat"
L["Show_In_Combat_Desc"] = "Show hotkeys during combat, even if they are hidden"
L["Show_On_Alt"] = "Show on |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Show hotkeys when |cFFFFD700Alt|r key is held down"
L["Show_With_Target"] = "Show when target is selected"
L["Show_With_Target_Desc"] = "While you have a target, show hotkeys (when hotkeys are set to hidden); they hide again when you clear target. Works with combat and Alt visibility. Does not affect macro names."
L["Fade_After_Combat"] = "Fade After Combat"
L["Fade_After_Combat_Desc"] = "Smooth fade in/out of hotkeys after combat"
L["Fade_Time"] = "Fade Time"
L["Fade_Time_Desc"] = "Time for smooth hotkey fade in/out (in seconds)"
L["Macros"] = "Macros"
L["Hide_Macro_Names"] = "Hide Macro Names"
L["Hide_Macro_Names_Desc"] = "Hide macro names on action bar buttons"
L["Hide Hotkeys"] = "Hide Hotkeys"
L["Show in Combat"] = "Show in Combat"
L["Show on Alt"] = "Show on |cFFFFD700Alt|r"
L["Fade After Combat"] = "Fade After Combat"
L["Fade Time"] = "Fade Time"
L["Hide Macro Names"] = "Hide Macro Names"
L["Color Indication Enabled"] = "Enable Color Indication"
L["Cooldown Color"] = "Cooldown Color"
L["Cooldown Alpha"] = "Cooldown Alpha"
L["Mana Color"] = "Mana Color"
L["Range Color"] = "Range Color"
L["Unusable Color"] = "Unusable Color"
L["Show Panels on Alt"] = "Show Panels on |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Hide Gryphons"
L["Hide Decorative Elements"] = "Hide Decorative Elements"
L["Hide Action Bar Backgrounds"] = "Hide Action Bar Backgrounds"
L["Hide Shapeshift Backgrounds"] = "Hide Shapeshift Backgrounds"
L["Hide Pet Bar Backgrounds"] = "Hide Pet Bar Backgrounds"
L["Hide Possess Bar Backgrounds"] = "Hide Possess Bar Backgrounds"
L["Hide Bonus Bar Textures"] = "Hide Bonus Bar Textures"
L["Hide Keyring Button"] = "Hide Keyring Button"
L["Hide Page Buttons"] = "Hide Page Buttons"
L["Hide Max Level Bar"] = "Hide Max Level Bar"
L["Hide Page Numbers"] = "Hide Page Numbers"
L["Show Page Numbers in Combat"] = "Show Page Numbers in Combat"
L["Show Page Numbers on Alt"] = "Show Page Numbers on |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Page Numbers Fade After Combat"
L["Page Numbers Fade Time"] = "Page Numbers Fade Time"
L["Hide Exp Bar"] = "Hide Exp Bar"
L["Show Exp Bar on Alt"] = "Show Exp Bar on |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Show Exp Bar on Gain"
L["Exp Bar Fade Time"] = "Exp Bar Fade Time"
L["Exp Bar Show Time"] = "Exp Bar Show Time"
L["Hide Rep Bar"] = "Hide Rep Bar"
L["Show Rep Bar on Alt"] = "Show Rep Bar on |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Gain"] = "Show on reputation change"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Temporarily shows the reputation bar when reputation is gained or lost."
L["Reputation_Bar_Fade_Time"] = "Reputation bar fade duration"
L["Reputation_Bar_Fade_Time_Desc"] = "Duration of the reputation bar fade in/out animation."
L["Reputation_Bar_Show_Time"] = "Reputation bar display time"
L["Reputation_Bar_Show_Time_Desc"] = "How long the reputation bar stays visible after a reputation change."
L["Button Border Alpha"] = "Button Border Alpha"
L["Micro Menu Alpha"] = "Micro Menu Alpha"
L["Button Border Alpha Enabled"] = "Enable Button Border Alpha"
L["Micro Menu Alpha Enabled"] = "Enable Micro Menu Alpha"
L["Minimap"] = "Minimap"
L["Nameplates"] = "Nameplates"
L["Plates Auras"] = "Plates Auras"
L["Health Indicators"] = "Health Indicators"
L["Health Indicators Desc"] = "Choose the health indicator / nameplate system."
L["Health Indicator Type"] = "Health indicator type"
L["Health Indicator Type Desc"] = "ElvUI uses embedded ElvUI nameplates. Classic WoW uses default Blizzard nameplates."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Editing display settings for: %s"
L["Health Indicators Reload Notice"] = "A UI reload is required to fully apply the health indicator type change."
L["Open ElvUI NamePlates Settings"] = "Settings"
L["Open ElvUI NamePlates Settings Desc"] = "Open the ElvUI NamePlates configuration window (/enp)."
L["Arena Frame Type"] = "Arena frame type"
L["Arena Frame Type Desc"] = "GladiusEx uses embedded GladiusEx arena frames. Classic WoW uses the default SarychUI arena module."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "Open GladiusEx Settings"
L["Open GladiusEx Settings Desc"] = "Open the GladiusEx configuration window (/gex ui)."
L["Arena Classic Settings Disabled"] = "These settings are only available in Classic WoW mode."
L["Map"] = "World Map"
L["World Map"] = "World Map"
L["Map Module Desc"] = "Choose which map addon to use."
L["Map Type"] = "Map type"
L["Map Type Desc"] = "Choose which map addon to use."
L["Classic WoW Map"] = "Classic WoW map"
L["Open Mapster Settings"] = "Open Mapster Settings"
L["Open Mapster Settings Desc"] = "Open the Mapster configuration window (/mapster)."
L["Open Carbonite Settings"] = "Open Carbonite Settings"
L["Open Carbonite Settings Desc"] = "Open the Carbonite configuration window (/carb options)."
L["Map Type Reload"] = "A UI reload is required to apply the map type change."
L["Nameplate Distance"] = "Enable distance display"
L["Nameplate Distance Desc"] = "Requires nameplate_range.dll. Status: System -> Overview."
L["Nameplate Distance Tab"] = "Nameplate distance"
L["Nameplate Distance Font Desc"] = "Font for the distance text on nameplates."
L["Nameplate Distance Font Size Desc"] = "Font size for the distance text."
L["Nameplate Distance Offset X Desc"] = "Horizontal offset for the distance text."
L["Nameplate Distance Offset Y Desc"] = "Vertical offset for the distance text."
L["Font Size"] = "Font size"
L["Position X"] = "Position X"
L["Position Y"] = "Position Y"
L["Font Outline"] = "Font outline"
L["Nameplate Distance Font Outline Desc"] = "Text outline style for the distance label (same options as ElvUI NamePlates)."
L["Shadow X"] = "Shadow X"
L["Shadow Y"] = "Shadow Y"
L["Nameplate Distance Shadow X Desc"] = "Horizontal shadow offset for the distance text."
L["Nameplate Distance Shadow Y Desc"] = "Vertical shadow offset for the distance text."
L["None"] = "None"
L["Reload UI"] = "Reload UI"
L["Reload UI Desc"] = "Run /reload to apply changes."
L["Tools"] = "Other"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "Auto Confirm module automatically confirms various dialogs."
L["Crowd Control module displays CC effects on your screen."] = "Crowd Control module displays CC effects on your screen."
L["Chat module enhances the chat interface with additional features."] = "Chat module enhances the chat interface with additional features."
L["Error Filter module filters out annoying error messages."] = "Error Filter module filters out annoying error messages."
L["Frame module allows you to move and customize unit frames."] = "Frame module allows you to move and customize unit frames."
L["Main Menu Bar module customizes the main action bar."] = "Main Menu Bar module customizes the main action bar."
L["Minimap module enhances and customizes the minimap."] = "Minimap module enhances and customizes the minimap."
L["Plates Auras module displays auras on nameplates."] = "Plates Auras module displays auras on nameplates."
L["Tools module provides various utility functions."] = "Tools module provides various utility functions."

-- Module description keys for options
L["Frames_Description"] = "Unit frame modification settings"
L["Auras_Description"] = "Aura hiding, dispel highlight, and player buff frame management"
L["Minimap_Description"] = "Minimap settings"
L["Chat_Description"] = "Chat and message settings"
L["Tools_Description"] = "Various tools and utilities"
L["MainMenuBar_Description"] = "Main command bar and action bars settings"
L["CooldownText_Description"] = "Cooldown text and timer display settings"
L["Automation_Description"] = "Automation of various game actions"

-- Auto Confirm
L["Confirm Loot"] = "Confirm Loot"
L["Automatically confirm loot rolls."] = "Automatically confirm loot rolls."
L["Confirm Bind"] = "Confirm Bind"
L["Automatically confirm binding items."] = "Automatically confirm binding items."
L["Confirm Delete"] = "Confirm Delete"
L["Automatically confirm item deletion."] = "Automatically confirm item deletion."
L["Confirm Quest"] = "Confirm Quest"
L["Automatically confirm quest dialogs."] = "Automatically confirm quest dialogs."

-- Crowd Control
L["Show Icon"] = "Show Icon"
L["Show CC icon when you are affected by crowd control."] = "Show CC icon when you are affected by crowd control."
L["Icon Size"] = "Icon Size"
L["Size of the CC icon."] = "Size of the CC icon."
L["Icon Position"] = "Icon Position"
L["Position of the CC icon on screen."] = "Position of the CC icon on screen."
L["Show Timer"] = "Show Timer"
L["Show remaining time on CC effects."] = "Show remaining time on CC effects."

-- Chat
L["Chat Bar"] = "Chat Bar"
L["Enable chat bar with quick channel buttons."] = "Enable chat bar with quick channel buttons."
L["Position"] = "Position"
L["Chat bar position."] = "Chat bar position."
L["Timestamps"] = "Timestamps"
L["Show timestamps in chat."] = "Show timestamps in chat."
L["Class Colors"] = "Class Colors"
L["Color player names by class."] = "Color player names by class."
L["Short Channel Names"] = "Short Channel Names"
L["Use abbreviated channel names."] = "Use abbreviated channel names."

-- Error Filter
L["Filters"] = "Filters"
L["Configure which errors to filter."] = "Configure which errors to filter."

-- Frame
L["Move Frames"] = "Move Frames"
L["Allow moving unit frames."] = "Allow moving unit frames."
L["Combat Indicator"] = "Combat Indicator"
L["Show combat indicator on frames."] = "Show combat indicator on frames."
L["Size"] = "Size"
L["Frame Text"] = "Frame Text"
L["Show Name"] = "Show Name"
L["Show Level"] = "Show Level"
L["Show Class"] = "Show Class"

-- Main Menu Bar
L["Hide Art"] = "Hide Art"
L["Hide background art from the main menu bar."] = "Hide background art from the main menu bar."
L["Hide Gryphons"] = "Hide Gryphons"
L["Hide the gryphon decorations."] = "Hide the gryphon decorations."
L["Show Buttons"] = "Show Buttons"
L["Configure which buttons to show."] = "Configure which buttons to show."

-- Minimap
L["Shape"] = "Shape"
L["Minimap shape (square or round)."] = "Minimap shape (square or round)."
L["Square"] = "Square"
L["Round"] = "Round"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Enable zoom buttons."

-- Plates Auras
L["Show Buffs"] = "Show Buffs"
L["Display buffs on nameplates."] = "Display buffs on nameplates."
L["Show Debuffs"] = "Show Debuffs"
L["Display debuffs on nameplates."] = "Display debuffs on nameplates."
L["Max Icons"] = "Max Icons"
L["Maximum number of icons to display."] = "Maximum number of icons to display."
L["Only Mine"] = "Only Mine"
L["Only show auras cast by you."] = "Only show auras cast by you."
L["Show Duration"] = "Show Duration"
L["Display remaining duration on auras."] = "Display remaining duration on auras."
L["Spell Settings"] = "Spell Settings"
L["Visibility"] = "Visibility"
L["Show this spell on nameplates"] = "Show this spell on nameplates"
L["Spell Type"] = "Spell Type"
L["Type"] = "Type"
L["Spell Priority"] = "Spell Priority"
L["Custom Priority"] = "Custom Priority"
L["Priority"] = "Priority"
L["Higher priority spells will take precedence regardless of duration"] = "Higher priority spells will take precedence regardless of duration"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC to OK"
L["Allow ESC key to confirm dialogs."] = "Allow ESC key to confirm dialogs."
L["No Combat Errors"] = "No Combat Errors"
L["Hide errors during combat."] = "Hide errors during combat."
L["Speedy Load"] = "Speedy Load"
L["Faster addon loading."] = "Faster addon loading."

-- Positions
L["Top"] = "Top"
L["Bottom"] = "Bottom"
L["Left"] = "Left"
L["Right"] = "Right"
L["Center"] = "Center"
L["Top Left"] = "Top Left"
L["Top Right"] = "Top Right"
L["Bottom Left"] = "Bottom Left"
L["Bottom Right"] = "Bottom Right"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+Click tab – |cFFFFD700copy window|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Enable chat copying on Ctrl+Click on chat tab"
L["Messages"] = "Messages: %d"
L["Drag_to_size"] = "Drag to size | Right-click to close"

-- Tooltip Settings
L["Tooltip_Settings"] = "Window Settings"
L["Enable_Tooltip_Position"] = "Change window position"
L["Enable_Tooltip_Position_Desc"] = "Enable custom tooltip window positioning"
L["Tooltip_Base_Offset"] = "Base offset"
L["Tooltip_Base_Offset_Desc"] = "Base offset for tooltip window"
L["Tooltip_Pet_Offset"] = "Pet offset"
L["Tooltip_Pet_Offset_Desc"] = "Additional offset for tooltip window when pet is active"
L["Enable_Chat_Icons"] = "Show icons in tooltip window"
L["Enable_Chat_Icons_Desc"] = "Show icons for items, spells and achievements in chat messages"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Hide friends button"
L["Enable_Friends_Button_Mod_Desc"] = "Hide friends button in chat"
L["Enable_Hide_Chat_Frame_Button"] = "Hide communication button"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Hide communication button"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Hide communication button in chat"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Hide up and down arrows"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Hide up and down scroll arrows in chat"
L["Enable_Hide_Chat_Bottom_Button"] = "Hide move to bottom arrow"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Hide move to bottom arrow in chat"

-- Chat Animations
L["Chat_Animations"] = "Chat Animations"
L["Enable_Chat_Animations"] = "Enable Chat Animations"
L["Enable_Chat_Animations_Desc"] = "Enable custom chat animations"
L["Chat_Tab_Show_Delay"] = "Tab Show Delay (sec)"
L["Chat_Tab_Show_Delay_Desc"] = "Delay before showing chat tabs"
L["Chat_Tab_Hide_Delay"] = "Tab Hide Delay (sec)"
L["Chat_Tab_Hide_Delay_Desc"] = "Delay before hiding chat tabs"
L["Chat_Frame_Fade_Time"] = "Fade In Duration (sec)"
L["Chat_Frame_Fade_Time_Desc"] = "Duration of chat appearance animation"
L["Chat_Frame_Fade_Out_Time"] = "Fade Out Duration (sec)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Duration of chat disappearance animation"

-- Messages
L["Profile reset to defaults."] = "Profile reset to defaults."
L["Module enabled."] = "Module enabled."
L["Module disabled."] = "Module disabled."

SarychUI.RegisterLocale("enUS", L)

