-- SarychUI esES Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "General"
L["Enable"] = "Activar"
L["Disable"] = "Desactivar"
L["Enabled"] = "Activado"
L["Settings"] = "Ajustes"
L["Options"] = "Opciones"
L["Reset"] = "Restablecer"
L["Default"] = "Predeterminado"

-- System / wow_optimize compatibility
L["System"] = "Sistema"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Modo de compatibilidad opcional con wow_optimize.dll. Cuando está activo, SarychUI evita duplicar correcciones de GC/combat log y reduce los escaneos pesados de nameplates y bocadillos de chat."
L["WowOptimize_Mode"] = "Modo de compatibilidad"
L["WowOptimize_Mode_Desc"] = "Auto — detectar mediante globales de la DLL (LUABOOST_DLL_*). Activado — forzar. Desactivado — SarychUI normal."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Activado"
L["WowOptimize_Mode_Disabled"] = "Desactivado"
L["WowOptimize_Debug"] = "Registro de depuración de compatibilidad"
L["WowOptimize_Debug_Desc"] = "Mostrar en el chat las adaptaciones aplicadas (o define DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Resumen"
L["Dll_Detection_Header"] = "Detección de DLL"
L["Dll_Status_Detected"] = "Detectada"
L["Dll_Status_NotDetected"] = "No detectada"
L["Dll_Status_Checking"] = "Comprobando..."
L["Dll_Status_NoMarker"] = "Sin marcador Lua"
L["Dll_Status_ApiDetected"] = "API detectada"
L["Dll_Status_WaitingNameplates"] = "Esperando nameplates"
L["Runtime_LuaOptimize"] = "Optimización Lua"
L["Runtime_EnableGC"] = "Activar gestor de recolección de basura"
L["Runtime_EnableGC_Desc"] = "GC incremental por modo (normal / combate / inactivo / carga). Con wow_optimize.dll activa, el GC lo controla la DLL."
L["Runtime_Preset"] = "Perfil de GC"
L["Runtime_Preset_Light"] = "Ligero"
L["Runtime_Preset_Standard"] = "Estándar"
L["Runtime_Preset_Heavy"] = "Pesado"
L["Runtime_Preset_Custom"] = "Personalizado"
L["Runtime_StepNormal"] = "GC step (normal), KB"
L["Runtime_StepCombat"] = "GC step (combate), KB"
L["Runtime_StepIdle"] = "GC step (inactivo), KB"
L["Runtime_StepLoading"] = "GC step (carga), KB"
L["Runtime_EmergencyMB"] = "Umbral de GC total de emergencia, MB"
L["Runtime_IdleTimeout"] = "Tiempo de inactividad, seg"
L["Runtime_SpeedyLoad"] = "Optimización de la pantalla de carga"
L["Runtime_SpeedyLoadMode"] = "Modo de carga"
L["Runtime_SpeedyLoadSafe"] = "Seguro"
L["Runtime_SpeedyLoadAggressive"] = "Agresivo"
L["Runtime_Debug"] = "Salida de diagnóstico"
L["Runtime_DllStatus"] = "Estado de wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "El GC lo controla wow_optimize.dll — el stepping de Lua está desactivado."
L["Runtime_ForceGC"] = "Recolección completa ahora (fuera de combate)"
L["Runtime_ForceGC_Desc"] = "Ejecuta una recolección de basura completa fuera de combate. No disponible en combate."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost detectado. La gestión de GC de SarychUI está desactivada para evitar conflictos. Desactiva o elimina !LuaBoost para usar esta opción."

-- Modules
L["Modules"] = "Módulos"
L["Auto Confirm"] = "Confirmación automática"
L["Crowd Control"] = "Control de masas"
L["Cooldown Text"] = "Reutilizaciones y temporizadores"
L["Font_Path"] = "Ruta de la fuente"
L["Font_Path_Desc"] = "Ruta completa al .ttf (p. ej. Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Estilo de fuente"
L["Font_Flags_Desc"] = "Opciones: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Tamaño del texto (< 60s)"
L["Font_Size_Small_Desc"] = "Tamaño del texto para el tiempo restante inferior a 60 segundos"
L["Font_Size_Medium"] = "Tamaño del texto (1–10 min)"
L["Font_Size_Medium_Desc"] = "Tamaño del texto para 1:00–9:59 y ≥10 minutos"
L["Font_Size_Large"] = "Tamaño del texto (>10 min)"
L["Font_Size_Large_Desc"] = "Tamaño del texto para valores en minutos ≥ 10"
L["Default_Color"] = "Color de texto predeterminado"
L["Appearance"] = "Apariencia"
L["Display_Conditions"] = "Condiciones de visualización"
L["Behavior"] = "Comportamiento"
L["Min_Scale"] = "Escala mínima"
L["Min_Scale_Desc"] = "Ocultar el texto cuando la escala efectiva del icono sea menor"
L["Min_Icon_Size"] = "Tamaño mínimo del icono"
L["Min_Icon_Size_Desc"] = "Ocultar el texto si el ancho/alto del icono es menor"
L["Hide_On_GCD"] = "Ocultar en GCD"
L["Hide_On_GCD_Desc"] = "Ocultar el texto de reutilización en habilidades con tiempo de reutilización global (GCD ~1.5 s)"
L["Chat"] = "Chat"
L["Error Filter"] = "Filtro de errores"
L["Frame"] = "Marcos"
L["Frames"] = "Marcos"
L["Auras"] = "Auras"
L["Frame Auras"] = "Auras de marcos"
L["Character Auras"] = "Auras del personaje"
L["MainMenuBar"] = "Barra de acción"
L["MainMenuBar_Description"] = "Personaliza la barra de acción con gestión de atajos y nombres de macros."
L["Enable_Module"] = "Activar módulo"
L["Enable_Module_Desc"] = "Activar o desactivar por completo el módulo de la barra de acción."
L["Hotkeys"] = "Atajos"
L["Color Indication"] = "Indicación por color"
L["Color_Indication_Enabled"] = "Activar indicación por color"
L["Color_Indication_Enabled_Desc"] = "Activar o desactivar la indicación por color de los botones de la barra de acción"
L["Color_Cooldown_Enabled"] = "Atenuar en reutilización"
L["Color_Cooldown_Enabled_Desc"] = "Hacer grises los botones cuando estén en reutilización más de 1.5 segundos"
L["Color_Cooldown_Alpha"] = "Alpha de reutilización"
L["Color_Cooldown_Alpha_Desc"] = "Valor de alpha de los botones en reutilización (0 - invisible, 1 - predeterminado)"
L["Color_Mana_Enabled"] = "Azul por recursos insuficientes"
L["Color_Mana_Enabled_Desc"] = "Hacer azules los botones cuando falte maná, energía o ira"
L["Color_Range_Enabled"] = "Rojo fuera de alcance"
L["Color_Range_Enabled_Desc"] = "Hacer rojos los botones cuando el objetivo esté fuera de alcance"
L["Color_Unusable_Enabled"] = "Gris oscuro cuando no se pueda usar"
L["Color_Unusable_Enabled_Desc"] = "Hacer gris oscuro los botones cuando la habilidad no se pueda usar"
L["Interface"] = "Interfaz"
L["Visual"] = "Texto"
L["Hide_Hotkeys"] = "Ocultar atajos"
L["Hide_Hotkeys_Desc"] = "Ocultar el texto de los atajos en los botones de la barra de acción"
L["Show_In_Combat"] = "Mostrar en combate"
L["Show_In_Combat_Desc"] = "Mostrar los atajos durante el combate, aunque estén ocultos"
L["Show_On_Alt"] = "Mostrar con |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Mostrar los atajos al mantener pulsada la tecla |cFFFFD700Alt|r"
L["Show_With_Target"] = "Mostrar con objetivo seleccionado"
L["Show_With_Target_Desc"] = "Mientras tengas un objetivo, mostrar los atajos (si están ocultos); se ocultan de nuevo al quitar el objetivo. Funciona con visibilidad en combate y Alt. No afecta a los nombres de macros."
L["Fade_After_Combat"] = "Desvanecer tras el combate"
L["Fade_After_Combat_Desc"] = "Aparición/desaparición suave de los atajos tras el combate"
L["Fade_Time"] = "Tiempo de desvanecimiento"
L["Fade_Time_Desc"] = "Tiempo de la transición suave de los atajos (en segundos)"
L["Macros"] = "Macros"
L["Hide_Macro_Names"] = "Ocultar nombres de macros"
L["Hide_Macro_Names_Desc"] = "Ocultar los nombres de macros en los botones de la barra de acción"
L["Hide Hotkeys"] = "Ocultar atajos"
L["Show in Combat"] = "Mostrar en combate"
L["Show on Alt"] = "Mostrar con |cFFFFD700Alt|r"
L["Fade After Combat"] = "Desvanecer tras el combate"
L["Fade Time"] = "Tiempo de desvanecimiento"
L["Hide Macro Names"] = "Ocultar nombres de macros"
L["Color Indication Enabled"] = "Activar indicación por color"
L["Cooldown Color"] = "Color de reutilización"
L["Cooldown Alpha"] = "Alpha de reutilización"
L["Mana Color"] = "Color de maná"
L["Range Color"] = "Color de alcance"
L["Unusable Color"] = "Color inutilizable"
L["Show Panels on Alt"] = "Mostrar paneles con |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Ocultar grifos"
L["Hide Decorative Elements"] = "Ocultar elementos decorativos"
L["Hide Action Bar Backgrounds"] = "Ocultar fondos de las barras de acción"
L["Hide Shapeshift Backgrounds"] = "Ocultar fondos de la barra de formas"
L["Hide Pet Bar Backgrounds"] = "Ocultar fondos de la barra de mascota"
L["Hide Possess Bar Backgrounds"] = "Ocultar fondos de la barra de posesión"
L["Hide Bonus Bar Textures"] = "Ocultar texturas de la barra adicional"
L["Hide Keyring Button"] = "Ocultar botón del llavero"
L["Hide Page Buttons"] = "Ocultar botones de página"
L["Hide Max Level Bar"] = "Ocultar barra de nivel máximo"
L["Hide Page Numbers"] = "Ocultar números de página"
L["Show Page Numbers in Combat"] = "Mostrar números de página en combate"
L["Show Page Numbers on Alt"] = "Mostrar números de página con |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Desvanecer números de página tras el combate"
L["Page Numbers Fade Time"] = "Tiempo de desvanecimiento de números de página"
L["Hide Exp Bar"] = "Ocultar barra de experiencia"
L["Show Exp Bar on Alt"] = "Mostrar barra de experiencia con |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Mostrar barra de experiencia al ganar"
L["Exp Bar Fade Time"] = "Tiempo de desvanecimiento de la barra de EXP"
L["Exp Bar Show Time"] = "Tiempo de visualización de la barra de EXP"
L["Hide Rep Bar"] = "Ocultar barra de reputación"
L["Show Rep Bar on Alt"] = "Mostrar barra de reputación con |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Gain"] = "Mostrar al cambiar la reputación"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Muestra temporalmente la barra de reputación al ganar o perder reputación."
L["Reputation_Bar_Fade_Time"] = "Duración del desvanecimiento de la barra de reputación"
L["Reputation_Bar_Fade_Time_Desc"] = "Duración de la animación de aparición/desaparición de la barra de reputación."
L["Reputation_Bar_Show_Time"] = "Tiempo de visualización de la barra de reputación"
L["Reputation_Bar_Show_Time_Desc"] = "Cuánto tiempo permanece visible la barra de reputación tras un cambio."
L["Button Border Alpha"] = "Alpha del borde de botones"
L["Micro Menu Alpha"] = "Alpha del micromenú"
L["Button Border Alpha Enabled"] = "Activar alpha del borde de botones"
L["Micro Menu Alpha Enabled"] = "Activar alpha del micromenú"
L["Minimap"] = "Minimapa"
L["Nameplates"] = "Placas de nombre"
L["Plates Auras"] = "Auras en placas"
L["Health Indicators"] = "Indicadores de salud"
L["Health Indicators Desc"] = "Elige el sistema de indicadores de salud / placas de nombre."
L["Health Indicator Type"] = "Tipo de indicador de salud"
L["Health Indicator Type Desc"] = "ElvUI usa las placas de nombre integradas de ElvUI. Classic WoW usa las placas de nombre predeterminadas de Blizzard."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Editando ajustes de visualización para: %s"
L["Health Indicators Reload Notice"] = "Es necesario recargar la interfaz para aplicar por completo el cambio de tipo de indicador de salud."
L["Open ElvUI NamePlates Settings"] = "Ajustes"
L["Open ElvUI NamePlates Settings Desc"] = "Abrir la ventana de configuración de ElvUI NamePlates (/enp)."
L["Arena Frame Type"] = "Tipo de marco de arena"
L["Arena Frame Type Desc"] = "GladiusEx usa los marcos de arena integrados de GladiusEx. Classic WoW usa el módulo de arena predeterminado de SarychUI."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "Abrir ajustes de GladiusEx"
L["Open GladiusEx Settings Desc"] = "Abrir la ventana de configuración de GladiusEx (/gex ui)."
L["Arena Classic Settings Disabled"] = "Estos ajustes solo están disponibles en el modo Classic WoW."
L["Map"] = "Mapa del mundo"
L["World Map"] = "Mapa del mundo"
L["Map Module Desc"] = "Elige qué addon de mapa usar."
L["Map Type"] = "Tipo de mapa"
L["Map Type Desc"] = "Elige qué addon de mapa usar."
L["Classic WoW Map"] = "Mapa Classic WoW"
L["Open Mapster Settings"] = "Abrir ajustes de Mapster"
L["Open Mapster Settings Desc"] = "Abrir la ventana de configuración de Mapster (/mapster)."
L["Open Carbonite Settings"] = "Abrir ajustes de Carbonite"
L["Open Carbonite Settings Desc"] = "Abrir la ventana de configuración de Carbonite (/carb options)."
L["Map Type Reload"] = "Es necesario recargar la interfaz para aplicar el cambio de tipo de mapa."
L["Nameplate Distance"] = "Activar visualización de distancia"
L["Nameplate Distance Desc"] = "Requiere nameplate_range.dll. Estado: Sistema -> Resumen."
L["Nameplate Distance Tab"] = "Distancia de placas"
L["Nameplate Distance Font Desc"] = "Fuente del texto de distancia en las placas de nombre."
L["Nameplate Distance Font Size Desc"] = "Tamaño de fuente del texto de distancia."
L["Nameplate Distance Offset X Desc"] = "Desplazamiento horizontal del texto de distancia."
L["Nameplate Distance Offset Y Desc"] = "Desplazamiento vertical del texto de distancia."
L["Font Size"] = "Tamaño de fuente"
L["Position X"] = "Posición X"
L["Position Y"] = "Posición Y"
L["Font Outline"] = "Contorno de fuente"
L["Nameplate Distance Font Outline Desc"] = "Estilo de contorno del texto de distancia (mismas opciones que ElvUI NamePlates)."
L["Shadow X"] = "Sombra X"
L["Shadow Y"] = "Sombra Y"
L["Nameplate Distance Shadow X Desc"] = "Desplazamiento horizontal de la sombra del texto de distancia."
L["Nameplate Distance Shadow Y Desc"] = "Desplazamiento vertical de la sombra del texto de distancia."
L["None"] = "Ninguno"
L["Reload UI"] = "Recargar interfaz"
L["Reload UI Desc"] = "Ejecuta /reload para aplicar los cambios."
L["Tools"] = "Otros"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "El módulo de confirmación automática confirma varios diálogos."
L["Crowd Control module displays CC effects on your screen."] = "El módulo de control de masas muestra efectos de CC en pantalla."
L["Chat module enhances the chat interface with additional features."] = "El módulo de chat mejora la interfaz del chat con funciones adicionales."
L["Error Filter module filters out annoying error messages."] = "El módulo de filtro de errores oculta mensajes de error molestos."
L["Frame module allows you to move and customize unit frames."] = "El módulo de marcos permite mover y personalizar los marcos de unidad."
L["Main Menu Bar module customizes the main action bar."] = "El módulo de la barra principal personaliza la barra de acción principal."
L["Minimap module enhances and customizes the minimap."] = "El módulo del minimapa mejora y personaliza el minimapa."
L["Plates Auras module displays auras on nameplates."] = "El módulo de auras en placas muestra auras en las placas de nombre."
L["Tools module provides various utility functions."] = "El módulo Otros ofrece varias funciones de utilidad."

-- Module description keys for options
L["Frames_Description"] = "Ajustes de modificación de marcos de unidad"
L["Auras_Description"] = "Ocultación de auras, resaltado de disipar y gestión del marco de beneficios del jugador"
L["Minimap_Description"] = "Ajustes del minimapa"
L["Chat_Description"] = "Ajustes de chat y mensajes"
L["Tools_Description"] = "Varias herramientas y utilidades"
L["MainMenuBar_Description"] = "Ajustes de la barra de comandos principal y de las barras de acción"
L["CooldownText_Description"] = "Ajustes de texto de reutilización y temporizadores"
L["Automation_Description"] = "Automatización de varias acciones del juego"

-- Auto Confirm
L["Confirm Loot"] = "Confirmar botín"
L["Automatically confirm loot rolls."] = "Confirmar automáticamente las tiradas de botín."
L["Confirm Bind"] = "Confirmar vinculación"
L["Automatically confirm binding items."] = "Confirmar automáticamente la vinculación de objetos."
L["Confirm Delete"] = "Confirmar eliminación"
L["Automatically confirm item deletion."] = "Confirmar automáticamente la eliminación de objetos."
L["Confirm Quest"] = "Confirmar misión"
L["Automatically confirm quest dialogs."] = "Confirmar automáticamente los diálogos de misión."

-- Crowd Control
L["Show Icon"] = "Mostrar icono"
L["Show CC icon when you are affected by crowd control."] = "Mostrar el icono de CC cuando estés afectado por control de masas."
L["Icon Size"] = "Tamaño del icono"
L["Size of the CC icon."] = "Tamaño del icono de CC."
L["Icon Position"] = "Posición del icono"
L["Position of the CC icon on screen."] = "Posición del icono de CC en pantalla."
L["Show Timer"] = "Mostrar temporizador"
L["Show remaining time on CC effects."] = "Mostrar el tiempo restante de los efectos de CC."

-- Chat
L["Chat Bar"] = "Barra de chat"
L["Enable chat bar with quick channel buttons."] = "Activar la barra de chat con botones rápidos de canal."
L["Position"] = "Posición"
L["Chat bar position."] = "Posición de la barra de chat."
L["Timestamps"] = "Marcas de tiempo"
L["Show timestamps in chat."] = "Mostrar marcas de tiempo en el chat."
L["Class Colors"] = "Colores de clase"
L["Color player names by class."] = "Colorear los nombres de los jugadores según su clase."
L["Short Channel Names"] = "Nombres cortos de canal"
L["Use abbreviated channel names."] = "Usar nombres abreviados de canales."

-- Error Filter
L["Filters"] = "Filtros"
L["Configure which errors to filter."] = "Configurar qué errores filtrar."

-- Frame
L["Move Frames"] = "Mover marcos"
L["Allow moving unit frames."] = "Permitir mover los marcos de unidad."
L["Combat Indicator"] = "Indicador de combate"
L["Show combat indicator on frames."] = "Mostrar el indicador de combate en los marcos."
L["Size"] = "Tamaño"
L["Frame Text"] = "Texto del marco"
L["Show Name"] = "Mostrar nombre"
L["Show Level"] = "Mostrar nivel"
L["Show Class"] = "Mostrar clase"

-- Main Menu Bar
L["Hide Art"] = "Ocultar arte"
L["Hide background art from the main menu bar."] = "Ocultar el arte de fondo de la barra principal."
L["Hide Gryphons"] = "Ocultar grifos"
L["Hide the gryphon decorations."] = "Ocultar las decoraciones de grifos."
L["Show Buttons"] = "Mostrar botones"
L["Configure which buttons to show."] = "Configurar qué botones mostrar."

-- Minimap
L["Shape"] = "Forma"
L["Minimap shape (square or round)."] = "Forma del minimapa (cuadrado o redondo)."
L["Square"] = "Cuadrado"
L["Round"] = "Redondo"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Activar botones de zoom."

-- Plates Auras
L["Show Buffs"] = "Mostrar beneficios"
L["Display buffs on nameplates."] = "Mostrar beneficios en las placas de nombre."
L["Show Debuffs"] = "Mostrar perjuicios"
L["Display debuffs on nameplates."] = "Mostrar perjuicios en las placas de nombre."
L["Max Icons"] = "Máx. de iconos"
L["Maximum number of icons to display."] = "Número máximo de iconos a mostrar."
L["Only Mine"] = "Solo míos"
L["Only show auras cast by you."] = "Mostrar solo auras lanzadas por ti."
L["Show Duration"] = "Mostrar duración"
L["Display remaining duration on auras."] = "Mostrar la duración restante de las auras."
L["Spell Settings"] = "Ajustes de hechizo"
L["Visibility"] = "Visibilidad"
L["Show this spell on nameplates"] = "Mostrar este hechizo en las placas de nombre"
L["Spell Type"] = "Tipo de hechizo"
L["Type"] = "Tipo"
L["Spell Priority"] = "Prioridad del hechizo"
L["Custom Priority"] = "Prioridad personalizada"
L["Priority"] = "Prioridad"
L["Higher priority spells will take precedence regardless of duration"] = "Los hechizos de mayor prioridad tienen preferencia independientemente de la duración"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC como Aceptar"
L["Allow ESC key to confirm dialogs."] = "Permitir que la tecla ESC confirme diálogos."
L["No Combat Errors"] = "Sin errores en combate"
L["Hide errors during combat."] = "Ocultar errores durante el combate."
L["Speedy Load"] = "Carga rápida"
L["Faster addon loading."] = "Carga de addons más rápida."

-- Positions
L["Top"] = "Arriba"
L["Bottom"] = "Abajo"
L["Left"] = "Izquierda"
L["Right"] = "Derecha"
L["Center"] = "Centro"
L["Top Left"] = "Arriba a la izquierda"
L["Top Right"] = "Arriba a la derecha"
L["Bottom Left"] = "Abajo a la izquierda"
L["Bottom Right"] = "Abajo a la derecha"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+Clic en pestaña – |cFFFFD700ventana de copia|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Activar la copia del chat con Ctrl+Clic en la pestaña del chat"
L["Messages"] = "Mensajes: %d"
L["Drag_to_size"] = "Arrastra para cambiar el tamaño | Clic derecho para cerrar"

-- Tooltip Settings
L["Tooltip_Settings"] = "Ajustes de ventana"
L["Enable_Tooltip_Position"] = "Cambiar posición de la ventana"
L["Enable_Tooltip_Position_Desc"] = "Activar el posicionamiento personalizado de la ventana de descripción emergente"
L["Tooltip_Base_Offset"] = "Desplazamiento base"
L["Tooltip_Base_Offset_Desc"] = "Desplazamiento base de la ventana emergente"
L["Tooltip_Pet_Offset"] = "Desplazamiento de mascota"
L["Tooltip_Pet_Offset_Desc"] = "Desplazamiento adicional de la ventana emergente cuando la mascota está activa"
L["Enable_Chat_Icons"] = "Mostrar iconos en la ventana emergente"
L["Enable_Chat_Icons_Desc"] = "Mostrar iconos de objetos, hechizos y logros en los mensajes del chat"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Ocultar botón de amigos"
L["Enable_Friends_Button_Mod_Desc"] = "Ocultar el botón de amigos en el chat"
L["Enable_Hide_Chat_Frame_Button"] = "Ocultar botón de comunicación"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Ocultar botón de comunicación"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Ocultar el botón de comunicación en el chat"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Ocultar flechas arriba y abajo"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Ocultar las flechas de desplazamiento arriba y abajo en el chat"
L["Enable_Hide_Chat_Bottom_Button"] = "Ocultar flecha ir al final"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Ocultar la flecha de ir al final en el chat"

-- Chat Animations
L["Chat_Animations"] = "Animaciones del chat"
L["Enable_Chat_Animations"] = "Activar animaciones del chat"
L["Enable_Chat_Animations_Desc"] = "Activar animaciones personalizadas del chat"
L["Chat_Tab_Show_Delay"] = "Retraso al mostrar pestañas (seg)"
L["Chat_Tab_Show_Delay_Desc"] = "Retraso antes de mostrar las pestañas del chat"
L["Chat_Tab_Hide_Delay"] = "Retraso al ocultar pestañas (seg)"
L["Chat_Tab_Hide_Delay_Desc"] = "Retraso antes de ocultar las pestañas del chat"
L["Chat_Frame_Fade_Time"] = "Duración de aparición (seg)"
L["Chat_Frame_Fade_Time_Desc"] = "Duración de la animación de aparición del chat"
L["Chat_Frame_Fade_Out_Time"] = "Duración de desaparición (seg)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Duración de la animación de desaparición del chat"

-- Messages
L["Profile reset to defaults."] = "Perfil restablecido a los valores predeterminados."
L["Module enabled."] = "Módulo activado."
L["Module disabled."] = "Módulo desactivado."

SarychUI.RegisterLocale("esES", L)
