-- SarychUI frFR Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "Général"
L["Enable"] = "Activer"
L["Disable"] = "Désactiver"
L["Enabled"] = "Activé"
L["Settings"] = "Réglages"
L["Options"] = "Options"
L["Reset"] = "Réinitialiser"
L["Default"] = "Par défaut"

-- System / wow_optimize compatibility
L["System"] = "Système"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Mode de compatibilité optionnel pour wow_optimize.dll. Lorsqu’il est actif, SarychUI évite de dupliquer les correctifs GC/journal de combat et limite les scans lourds des barres de nom et des bulles de discussion."
L["WowOptimize_Mode"] = "Mode de compatibilité"
L["WowOptimize_Mode_Desc"] = "Auto — détection via les globales DLL (LUABOOST_DLL_*). Activé — forcer. Désactivé — SarychUI normal."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Activé"
L["WowOptimize_Mode_Disabled"] = "Désactivé"
L["WowOptimize_Debug"] = "Journal de débogage de compatibilité"
L["WowOptimize_Debug_Desc"] = "Afficher dans la discussion les adaptations appliquées (ou définir DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Aperçu"
L["Dll_Detection_Header"] = "Détection DLL"
L["Dll_Status_Detected"] = "Détectée"
L["Dll_Status_NotDetected"] = "Non détectée"
L["Dll_Status_Checking"] = "Vérification..."
L["Dll_Status_NoMarker"] = "Aucun marqueur Lua"
L["Dll_Status_ApiDetected"] = "API détectée"
L["Dll_Status_WaitingNameplates"] = "En attente des barres de nom"
L["Runtime_LuaOptimize"] = "Optimisation Lua"
L["Runtime_EnableGC"] = "Activer le gestionnaire de ramasse-miettes"
L["Runtime_EnableGC_Desc"] = "GC incrémental par mode (normal / combat / inactif / chargement). Si wow_optimize.dll est active, le GC est géré par la DLL."
L["Runtime_Preset"] = "Profil GC"
L["Runtime_Preset_Light"] = "Léger"
L["Runtime_Preset_Standard"] = "Standard"
L["Runtime_Preset_Heavy"] = "Lourd"
L["Runtime_Preset_Custom"] = "Personnalisé"
L["Runtime_StepNormal"] = "GC step (normal), KB"
L["Runtime_StepCombat"] = "GC step (combat), KB"
L["Runtime_StepIdle"] = "GC step (inactif), KB"
L["Runtime_StepLoading"] = "GC step (chargement), KB"
L["Runtime_EmergencyMB"] = "Seuil de GC complet d’urgence, MB"
L["Runtime_IdleTimeout"] = "Délai d’inactivité, sec"
L["Runtime_SpeedyLoad"] = "Optimisation de l’écran de chargement"
L["Runtime_SpeedyLoadMode"] = "Mode de chargement"
L["Runtime_SpeedyLoadSafe"] = "Sûr"
L["Runtime_SpeedyLoadAggressive"] = "Agressif"
L["Runtime_Debug"] = "Sortie diagnostique"
L["Runtime_DllStatus"] = "État de wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "Le GC est géré par wow_optimize.dll — le stepping Lua est désactivé."
L["Runtime_ForceGC"] = "Collecte complète maintenant (hors combat)"
L["Runtime_ForceGC_Desc"] = "Exécute une collecte de garbage complète hors combat. Indisponible en combat."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost détecté. La gestion GC de SarychUI est désactivée pour éviter les conflits. Désactivez ou supprimez !LuaBoost pour utiliser cette option."

-- Modules
L["Modules"] = "Modules"
L["Auto Confirm"] = "Confirmation auto"
L["Crowd Control"] = "Contrôle de foule"
L["Cooldown Text"] = "Temps de recharge et timers"
L["Font_Path"] = "Chemin de la police"
L["Font_Path_Desc"] = "Chemin complet vers le .ttf (ex. Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Style de police"
L["Font_Flags_Desc"] = "Options : NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Taille du texte (< 60s)"
L["Font_Size_Small_Desc"] = "Taille du texte pour le temps restant inférieur à 60 secondes"
L["Font_Size_Medium"] = "Taille du texte (1–10 min)"
L["Font_Size_Medium_Desc"] = "Taille du texte pour 1:00–9:59 et ≥10 minutes"
L["Font_Size_Large"] = "Taille du texte (>10 min)"
L["Font_Size_Large_Desc"] = "Taille du texte pour les valeurs en minutes ≥ 10"
L["Default_Color"] = "Couleur de texte par défaut"
L["Appearance"] = "Apparence"
L["Display_Conditions"] = "Conditions d’affichage"
L["Behavior"] = "Comportement"
L["Min_Scale"] = "Échelle minimale"
L["Min_Scale_Desc"] = "Masquer le texte lorsque l’échelle effective de l’icône est inférieure"
L["Min_Icon_Size"] = "Taille minimale de l’icône"
L["Min_Icon_Size_Desc"] = "Masquer le texte si la largeur/hauteur de l’icône est inférieure"
L["Hide_On_GCD"] = "Masquer pendant le GCD"
L["Hide_On_GCD_Desc"] = "Masquer le texte de recharge sur les techniques avec temps de recharge global (GCD ~1.5 s)"
L["Chat"] = "Discussion"
L["Error Filter"] = "Filtre d’erreurs"
L["Frame"] = "Cadres"
L["Frames"] = "Cadres"
L["Auras"] = "Auras"
L["Frame Auras"] = "Auras des cadres"
L["Character Auras"] = "Auras du personnage"
L["MainMenuBar"] = "Barre d’actions"
L["MainMenuBar_Description"] = "Personnalisez la barre d’actions avec la gestion des raccourcis et des noms de macros."
L["Enable_Module"] = "Activer le module"
L["Enable_Module_Desc"] = "Activer ou désactiver complètement le module Barre d’actions."
L["Hotkeys"] = "Raccourcis"
L["Color Indication"] = "Indication par couleur"
L["Color_Indication_Enabled"] = "Activer l’indication par couleur"
L["Color_Indication_Enabled_Desc"] = "Activer ou désactiver l’indication par couleur des boutons de la barre d’actions"
L["Color_Cooldown_Enabled"] = "Grisé en recharge"
L["Color_Cooldown_Enabled_Desc"] = "Rendre les boutons gris lorsqu’ils sont en recharge plus de 1.5 secondes"
L["Color_Cooldown_Alpha"] = "Alpha de recharge"
L["Color_Cooldown_Alpha_Desc"] = "Valeur d’alpha des boutons en recharge (0 - invisible, 1 - par défaut)"
L["Color_Mana_Enabled"] = "Bleu pour ressources insuffisantes"
L["Color_Mana_Enabled_Desc"] = "Rendre les boutons bleus en cas de manque de mana, d’énergie ou de rage"
L["Color_Range_Enabled"] = "Rouge hors de portée"
L["Color_Range_Enabled_Desc"] = "Rendre les boutons rouges lorsque la cible est hors de portée"
L["Color_Unusable_Enabled"] = "Gris foncé si inutilisable"
L["Color_Unusable_Enabled_Desc"] = "Rendre les boutons gris foncé lorsque la technique est inutilisable"
L["Interface"] = "Interface"
L["Visual"] = "Texte"
L["Hide_Hotkeys"] = "Masquer les raccourcis"
L["Hide_Hotkeys_Desc"] = "Masquer le texte des raccourcis sur les boutons de la barre d’actions"
L["Show_In_Combat"] = "Afficher en combat"
L["Show_In_Combat_Desc"] = "Afficher les raccourcis en combat, même s’ils sont masqués"
L["Show_On_Alt"] = "Afficher avec |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Afficher les raccourcis lorsque la touche |cFFFFD700Alt|r est maintenue"
L["Show_With_Target"] = "Afficher avec une cible sélectionnée"
L["Show_With_Target_Desc"] = "Tant que vous avez une cible, afficher les raccourcis (s’ils sont masqués) ; ils se cachent à nouveau à la suppression de la cible. Fonctionne avec la visibilité combat et Alt. N’affecte pas les noms de macros."
L["Fade_After_Combat"] = "Fondu après le combat"
L["Fade_After_Combat_Desc"] = "Apparition/disparition progressive des raccourcis après le combat"
L["Fade_Time"] = "Durée du fondu"
L["Fade_Time_Desc"] = "Durée du fondu des raccourcis (en secondes)"
L["Macros"] = "Macros"
L["Hide_Macro_Names"] = "Masquer les noms de macros"
L["Hide_Macro_Names_Desc"] = "Masquer les noms de macros sur les boutons de la barre d’actions"
L["Hide Hotkeys"] = "Masquer les raccourcis"
L["Show in Combat"] = "Afficher en combat"
L["Show on Alt"] = "Afficher avec |cFFFFD700Alt|r"
L["Fade After Combat"] = "Fondu après le combat"
L["Fade Time"] = "Durée du fondu"
L["Hide Macro Names"] = "Masquer les noms de macros"
L["Color Indication Enabled"] = "Activer l’indication par couleur"
L["Cooldown Color"] = "Couleur de recharge"
L["Cooldown Alpha"] = "Alpha de recharge"
L["Mana Color"] = "Couleur de mana"
L["Range Color"] = "Couleur de portée"
L["Unusable Color"] = "Couleur inutilisable"
L["Show Panels on Alt"] = "Afficher les barres avec |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Masquer les griffons"
L["Hide Decorative Elements"] = "Masquer les éléments décoratifs"
L["Hide Action Bar Backgrounds"] = "Masquer les fonds des barres d’actions"
L["Hide Shapeshift Backgrounds"] = "Masquer les fonds de la barre de formes"
L["Hide Pet Bar Backgrounds"] = "Masquer les fonds de la barre de familier"
L["Hide Possess Bar Backgrounds"] = "Masquer les fonds de la barre de possession"
L["Hide Bonus Bar Textures"] = "Masquer les textures de la barre bonus"
L["Hide Keyring Button"] = "Masquer le bouton du trousseau"
L["Hide Page Buttons"] = "Masquer les boutons de page"
L["Hide Max Level Bar"] = "Masquer la barre de niveau maximum"
L["Hide Page Numbers"] = "Masquer les numéros de page"
L["Show Page Numbers in Combat"] = "Afficher les numéros de page en combat"
L["Show Page Numbers on Alt"] = "Afficher les numéros de page avec |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Fondu des numéros de page après combat"
L["Page Numbers Fade Time"] = "Durée du fondu des numéros de page"
L["Hide Exp Bar"] = "Masquer la barre d’XP"
L["Show Exp Bar on Alt"] = "Afficher la barre d’XP avec |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Afficher la barre d’XP au gain"
L["Exp Bar Fade Time"] = "Durée du fondu de la barre d’XP"
L["Exp Bar Show Time"] = "Durée d’affichage de la barre d’XP"
L["Hide Rep Bar"] = "Masquer la barre de réputation"
L["Show Rep Bar on Alt"] = "Afficher la barre de réputation avec |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Gain"] = "Afficher au changement de réputation"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Affiche temporairement la barre de réputation lors d’un gain ou d’une perte de réputation."
L["Reputation_Bar_Fade_Time"] = "Durée du fondu de la barre de réputation"
L["Reputation_Bar_Fade_Time_Desc"] = "Durée de l’animation d’apparition/disparition de la barre de réputation."
L["Reputation_Bar_Show_Time"] = "Durée d’affichage de la barre de réputation"
L["Reputation_Bar_Show_Time_Desc"] = "Combien de temps la barre de réputation reste visible après un changement."
L["Button Border Alpha"] = "Alpha de la bordure des boutons"
L["Micro Menu Alpha"] = "Alpha du micromenu"
L["Button Border Alpha Enabled"] = "Activer l’alpha de la bordure des boutons"
L["Micro Menu Alpha Enabled"] = "Activer l’alpha du micromenu"
L["Minimap"] = "Minicarte"
L["Nameplates"] = "Barres de nom"
L["Plates Auras"] = "Auras sur barres"
L["Health Indicators"] = "Indicateurs de vie"
L["Health Indicators Desc"] = "Choisissez le système d’indicateurs de vie / barres de nom."
L["Health Indicator Type"] = "Type d’indicateur de vie"
L["Health Indicator Type Desc"] = "ElvUI utilise les barres de nom intégrées d’ElvUI. Classic WoW utilise les barres de nom Blizzard par défaut."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Modification des réglages d’affichage pour : %s"
L["Health Indicators Reload Notice"] = "Un rechargement de l’interface est nécessaire pour appliquer pleinement le changement de type d’indicateur de vie."
L["Open ElvUI NamePlates Settings"] = "Réglages"
L["Open ElvUI NamePlates Settings Desc"] = "Ouvrir la fenêtre de configuration ElvUI NamePlates (/enp)."
L["Arena Frame Type"] = "Type de cadres d’arène"
L["Arena Frame Type Desc"] = "GladiusEx utilise les cadres d’arène intégrés de GladiusEx. Classic WoW utilise le module d’arène par défaut de SarychUI."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "Ouvrir les réglages GladiusEx"
L["Open GladiusEx Settings Desc"] = "Ouvrir la fenêtre de configuration GladiusEx (/gex ui)."
L["Arena Classic Settings Disabled"] = "Ces réglages ne sont disponibles qu’en mode Classic WoW."
L["Map"] = "Carte du monde"
L["World Map"] = "Carte du monde"
L["Map Module Desc"] = "Choisissez quel addon de carte utiliser."
L["Map Type"] = "Type de carte"
L["Map Type Desc"] = "Choisissez quel addon de carte utiliser."
L["Classic WoW Map"] = "Carte Classic WoW"
L["Open Mapster Settings"] = "Ouvrir les réglages Mapster"
L["Open Mapster Settings Desc"] = "Ouvrir la fenêtre de configuration Mapster (/mapster)."
L["Open Carbonite Settings"] = "Ouvrir les réglages Carbonite"
L["Open Carbonite Settings Desc"] = "Ouvrir la fenêtre de configuration Carbonite (/carb options)."
L["Map Type Reload"] = "Un rechargement de l’interface est nécessaire pour appliquer le changement de type de carte."
L["Nameplate Distance"] = "Activer l’affichage de la distance"
L["Nameplate Distance Desc"] = "Nécessite nameplate_range.dll. État : Système -> Aperçu."
L["Nameplate Distance Tab"] = "Distance des barres de nom"
L["Nameplate Distance Font Desc"] = "Police du texte de distance sur les barres de nom."
L["Nameplate Distance Font Size Desc"] = "Taille de police du texte de distance."
L["Nameplate Distance Offset X Desc"] = "Décalage horizontal du texte de distance."
L["Nameplate Distance Offset Y Desc"] = "Décalage vertical du texte de distance."
L["Font Size"] = "Taille de police"
L["Position X"] = "Position X"
L["Position Y"] = "Position Y"
L["Font Outline"] = "Contour de police"
L["Nameplate Distance Font Outline Desc"] = "Style de contour du texte de distance (mêmes options qu’ElvUI NamePlates)."
L["Shadow X"] = "Ombre X"
L["Shadow Y"] = "Ombre Y"
L["Nameplate Distance Shadow X Desc"] = "Décalage horizontal de l’ombre du texte de distance."
L["Nameplate Distance Shadow Y Desc"] = "Décalage vertical de l’ombre du texte de distance."
L["None"] = "Aucun"
L["Reload UI"] = "Recharger l’interface"
L["Reload UI Desc"] = "Exécutez /reload pour appliquer les changements."
L["Tools"] = "Autres"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "Le module Confirmation auto confirme automatiquement divers dialogues."
L["Crowd Control module displays CC effects on your screen."] = "Le module Contrôle de foule affiche les effets de CC à l’écran."
L["Chat module enhances the chat interface with additional features."] = "Le module Discussion enrichit l’interface de chat avec des fonctions supplémentaires."
L["Error Filter module filters out annoying error messages."] = "Le module Filtre d’erreurs filtre les messages d’erreur gênants."
L["Frame module allows you to move and customize unit frames."] = "Le module Cadres permet de déplacer et personnaliser les cadres d’unité."
L["Main Menu Bar module customizes the main action bar."] = "Le module Barre d’actions personnalise la barre d’actions principale."
L["Minimap module enhances and customizes the minimap."] = "Le module Minicarte améliore et personnalise la minicarte."
L["Plates Auras module displays auras on nameplates."] = "Le module Auras sur barres affiche les auras sur les barres de nom."
L["Tools module provides various utility functions."] = "Le module Autres fournit diverses fonctions utilitaires."

-- Module description keys for options
L["Frames_Description"] = "Réglages de modification des cadres d’unité"
L["Auras_Description"] = "Masquage des auras, surbrillance de dissipation et gestion du cadre de buffs du joueur"
L["Minimap_Description"] = "Réglages de la minicarte"
L["Chat_Description"] = "Réglages de discussion et de messages"
L["Tools_Description"] = "Divers outils et utilitaires"
L["MainMenuBar_Description"] = "Réglages de la barre de commandes principale et des barres d’actions"
L["CooldownText_Description"] = "Réglages du texte de recharge et des timers"
L["Automation_Description"] = "Automatisation de diverses actions du jeu"

-- Auto Confirm
L["Confirm Loot"] = "Confirmer le butin"
L["Automatically confirm loot rolls."] = "Confirmer automatiquement les jets de butin."
L["Confirm Bind"] = "Confirmer la liaison"
L["Automatically confirm binding items."] = "Confirmer automatiquement la liaison des objets."
L["Confirm Delete"] = "Confirmer la suppression"
L["Automatically confirm item deletion."] = "Confirmer automatiquement la suppression des objets."
L["Confirm Quest"] = "Confirmer la quête"
L["Automatically confirm quest dialogs."] = "Confirmer automatiquement les dialogues de quête."

-- Crowd Control
L["Show Icon"] = "Afficher l’icône"
L["Show CC icon when you are affected by crowd control."] = "Afficher l’icône de CC lorsque vous êtes sous contrôle de foule."
L["Icon Size"] = "Taille de l’icône"
L["Size of the CC icon."] = "Taille de l’icône de CC."
L["Icon Position"] = "Position de l’icône"
L["Position of the CC icon on screen."] = "Position de l’icône de CC à l’écran."
L["Show Timer"] = "Afficher le timer"
L["Show remaining time on CC effects."] = "Afficher le temps restant des effets de CC."

-- Chat
L["Chat Bar"] = "Barre de discussion"
L["Enable chat bar with quick channel buttons."] = "Activer la barre de discussion avec des boutons de canaux rapides."
L["Position"] = "Position"
L["Chat bar position."] = "Position de la barre de discussion."
L["Timestamps"] = "Horodatages"
L["Show timestamps in chat."] = "Afficher les horodatages dans la discussion."
L["Class Colors"] = "Couleurs de classe"
L["Color player names by class."] = "Colorer les noms des joueurs selon leur classe."
L["Short Channel Names"] = "Noms de canaux courts"
L["Use abbreviated channel names."] = "Utiliser des noms de canaux abrégés."

-- Error Filter
L["Filters"] = "Filtres"
L["Configure which errors to filter."] = "Configurer les erreurs à filtrer."

-- Frame
L["Move Frames"] = "Déplacer les cadres"
L["Allow moving unit frames."] = "Autoriser le déplacement des cadres d’unité."
L["Combat Indicator"] = "Indicateur de combat"
L["Show combat indicator on frames."] = "Afficher l’indicateur de combat sur les cadres."
L["Size"] = "Taille"
L["Frame Text"] = "Texte du cadre"
L["Show Name"] = "Afficher le nom"
L["Show Level"] = "Afficher le niveau"
L["Show Class"] = "Afficher la classe"

-- Main Menu Bar
L["Hide Art"] = "Masquer l’habillage"
L["Hide background art from the main menu bar."] = "Masquer l’habillage de fond de la barre principale."
L["Hide Gryphons"] = "Masquer les griffons"
L["Hide the gryphon decorations."] = "Masquer les décorations de griffons."
L["Show Buttons"] = "Afficher les boutons"
L["Configure which buttons to show."] = "Configurer les boutons à afficher."

-- Minimap
L["Shape"] = "Forme"
L["Minimap shape (square or round)."] = "Forme de la minicarte (carrée ou ronde)."
L["Square"] = "Carrée"
L["Round"] = "Ronde"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Activer les boutons de zoom."

-- Plates Auras
L["Show Buffs"] = "Afficher les buffs"
L["Display buffs on nameplates."] = "Afficher les buffs sur les barres de nom."
L["Show Debuffs"] = "Afficher les debuffs"
L["Display debuffs on nameplates."] = "Afficher les debuffs sur les barres de nom."
L["Max Icons"] = "Icônes max"
L["Maximum number of icons to display."] = "Nombre maximum d’icônes à afficher."
L["Only Mine"] = "Uniquement les miens"
L["Only show auras cast by you."] = "N’afficher que les auras lancées par vous."
L["Show Duration"] = "Afficher la durée"
L["Display remaining duration on auras."] = "Afficher la durée restante des auras."
L["Spell Settings"] = "Réglages de sort"
L["Visibility"] = "Visibilité"
L["Show this spell on nameplates"] = "Afficher ce sort sur les barres de nom"
L["Spell Type"] = "Type de sort"
L["Type"] = "Type"
L["Spell Priority"] = "Priorité du sort"
L["Custom Priority"] = "Priorité personnalisée"
L["Priority"] = "Priorité"
L["Higher priority spells will take precedence regardless of duration"] = "Les sorts de priorité plus élevée priment indépendamment de la durée"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC comme OK"
L["Allow ESC key to confirm dialogs."] = "Autoriser la touche ESC à confirmer les dialogues."
L["No Combat Errors"] = "Pas d’erreurs en combat"
L["Hide errors during combat."] = "Masquer les erreurs pendant le combat."
L["Speedy Load"] = "Chargement rapide"
L["Faster addon loading."] = "Chargement plus rapide des addons."

-- Positions
L["Top"] = "Haut"
L["Bottom"] = "Bas"
L["Left"] = "Gauche"
L["Right"] = "Droite"
L["Center"] = "Centre"
L["Top Left"] = "Haut gauche"
L["Top Right"] = "Haut droite"
L["Bottom Left"] = "Bas gauche"
L["Bottom Right"] = "Bas droite"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+Clic sur l’onglet – |cFFFFD700fenêtre de copie|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Activer la copie de discussion via Ctrl+Clic sur l’onglet de discussion"
L["Messages"] = "Messages : %d"
L["Drag_to_size"] = "Glisser pour redimensionner | Clic droit pour fermer"

-- Tooltip Settings
L["Tooltip_Settings"] = "Réglages de fenêtre"
L["Enable_Tooltip_Position"] = "Changer la position de la fenêtre"
L["Enable_Tooltip_Position_Desc"] = "Activer le positionnement personnalisé de la fenêtre d’info-bulle"
L["Tooltip_Base_Offset"] = "Décalage de base"
L["Tooltip_Base_Offset_Desc"] = "Décalage de base de la fenêtre d’info-bulle"
L["Tooltip_Pet_Offset"] = "Décalage du familier"
L["Tooltip_Pet_Offset_Desc"] = "Décalage supplémentaire de la fenêtre d’info-bulle lorsque le familier est actif"
L["Enable_Chat_Icons"] = "Afficher les icônes dans la fenêtre d’info-bulle"
L["Enable_Chat_Icons_Desc"] = "Afficher les icônes d’objets, sorts et hauts faits dans les messages de discussion"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Masquer le bouton des amis"
L["Enable_Friends_Button_Mod_Desc"] = "Masquer le bouton des amis dans la discussion"
L["Enable_Hide_Chat_Frame_Button"] = "Masquer le bouton de communication"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Masquer le bouton de communication"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Masquer le bouton de communication dans la discussion"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Masquer les flèches haut et bas"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Masquer les flèches de défilement haut et bas dans la discussion"
L["Enable_Hide_Chat_Bottom_Button"] = "Masquer la flèche aller en bas"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Masquer la flèche aller en bas dans la discussion"

-- Chat Animations
L["Chat_Animations"] = "Animations de discussion"
L["Enable_Chat_Animations"] = "Activer les animations de discussion"
L["Enable_Chat_Animations_Desc"] = "Activer les animations personnalisées de discussion"
L["Chat_Tab_Show_Delay"] = "Délai d’affichage des onglets (sec)"
L["Chat_Tab_Show_Delay_Desc"] = "Délai avant l’affichage des onglets de discussion"
L["Chat_Tab_Hide_Delay"] = "Délai de masquage des onglets (sec)"
L["Chat_Tab_Hide_Delay_Desc"] = "Délai avant le masquage des onglets de discussion"
L["Chat_Frame_Fade_Time"] = "Durée d’apparition (sec)"
L["Chat_Frame_Fade_Time_Desc"] = "Durée de l’animation d’apparition de la discussion"
L["Chat_Frame_Fade_Out_Time"] = "Durée de disparition (sec)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Durée de l’animation de disparition de la discussion"

-- Messages
L["Profile reset to defaults."] = "Profil réinitialisé aux valeurs par défaut."
L["Module enabled."] = "Module activé."
L["Module disabled."] = "Module désactivé."

SarychUI.RegisterLocale("frFR", L)
