-- SarychUI itIT Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "Generale"
L["Enable"] = "Abilita"
L["Disable"] = "Disabilita"
L["Enabled"] = "Abilitato"
L["Settings"] = "Impostazioni"
L["Options"] = "Opzioni"
L["Reset"] = "Reimposta"
L["Default"] = "Predefinito"

-- System / wow_optimize compatibility
L["System"] = "Sistema"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Modalità di compatibilità opzionale per wow_optimize.dll. Quando è attiva, SarychUI evita di duplicare le correzioni GC/combat log e riduce le scansioni pesanti di nameplate e fumetti della chat."
L["WowOptimize_Mode"] = "Modalità di compatibilità"
L["WowOptimize_Mode_Desc"] = "Auto — rileva tramite globali DLL (LUABOOST_DLL_*). Abilitato — forza attiva. Disabilitato — SarychUI normale."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Abilitato"
L["WowOptimize_Mode_Disabled"] = "Disabilitato"
L["WowOptimize_Debug"] = "Log di debug compatibilità"
L["WowOptimize_Debug_Desc"] = "Mostra in chat le adattazioni applicate (oppure imposta DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Panoramica"
L["Dll_Detection_Header"] = "Rilevamento DLL"
L["Dll_Status_Detected"] = "Rilevata"
L["Dll_Status_NotDetected"] = "Non rilevata"
L["Dll_Status_Checking"] = "Controllo..."
L["Dll_Status_NoMarker"] = "Nessun marker Lua"
L["Dll_Status_ApiDetected"] = "API rilevata"
L["Dll_Status_WaitingNameplates"] = "In attesa dei nameplate"
L["Runtime_LuaOptimize"] = "Ottimizzazione Lua"
L["Runtime_EnableGC"] = "Abilita gestore garbage collection"
L["Runtime_EnableGC_Desc"] = "GC incrementale per modalità (normale / combattimento / inattivo / caricamento). Con wow_optimize.dll attiva, il GC è gestito dalla DLL."
L["Runtime_Preset"] = "Profilo GC"
L["Runtime_Preset_Light"] = "Leggero"
L["Runtime_Preset_Standard"] = "Standard"
L["Runtime_Preset_Heavy"] = "Pesante"
L["Runtime_Preset_Custom"] = "Personalizzato"
L["Runtime_StepNormal"] = "GC step (normale), KB"
L["Runtime_StepCombat"] = "GC step (combattimento), KB"
L["Runtime_StepIdle"] = "GC step (inattivo), KB"
L["Runtime_StepLoading"] = "GC step (caricamento), KB"
L["Runtime_EmergencyMB"] = "Soglia GC completa di emergenza, MB"
L["Runtime_IdleTimeout"] = "Timeout inattività, sec"
L["Runtime_SpeedyLoad"] = "Ottimizzazione schermata di caricamento"
L["Runtime_SpeedyLoadMode"] = "Modalità di caricamento"
L["Runtime_SpeedyLoadSafe"] = "Sicura"
L["Runtime_SpeedyLoadAggressive"] = "Aggressiva"
L["Runtime_Debug"] = "Output diagnostico"
L["Runtime_DllStatus"] = "Stato di wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "Il GC è gestito da wow_optimize.dll — lo stepping Lua è disabilitato."
L["Runtime_ForceGC"] = "Raccolta completa ora (fuori combattimento)"
L["Runtime_ForceGC_Desc"] = "Esegue una garbage collection completa fuori combattimento. Non disponibile in combattimento."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost rilevato. La gestione GC di SarychUI è disabilitata per evitare conflitti. Disabilita o rimuovi !LuaBoost per usare questa opzione."

-- Modules
L["Modules"] = "Moduli"
L["Auto Confirm"] = "Conferma automatica"
L["Crowd Control"] = "Controllo di massa"
L["Cooldown Text"] = "Recariche e timer"
L["Font_Path"] = "Percorso del font"
L["Font_Path_Desc"] = "Percorso completo del .ttf (es. Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Stile del font"
L["Font_Flags_Desc"] = "Opzioni: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Dimensione testo (< 60s)"
L["Font_Size_Small_Desc"] = "Dimensione del testo per il tempo rimanente sotto i 60 secondi"
L["Font_Size_Medium"] = "Dimensione testo (1–10 min)"
L["Font_Size_Medium_Desc"] = "Dimensione del testo per 1:00–9:59 e ≥10 minuti"
L["Font_Size_Large"] = "Dimensione testo (>10 min)"
L["Font_Size_Large_Desc"] = "Dimensione del testo per valori in minuti ≥ 10"
L["Default_Color"] = "Colore testo predefinito"
L["Appearance"] = "Aspetto"
L["Display_Conditions"] = "Condizioni di visualizzazione"
L["Behavior"] = "Comportamento"
L["Min_Scale"] = "Scala minima"
L["Min_Scale_Desc"] = "Nascondi il testo quando la scala effettiva dell’icona è inferiore"
L["Min_Icon_Size"] = "Dimensione minima icona"
L["Min_Icon_Size_Desc"] = "Nascondi il testo se larghezza/altezza dell’icona è inferiore"
L["Hide_On_GCD"] = "Nascondi durante GCD"
L["Hide_On_GCD_Desc"] = "Nascondi il testo di ricarica sulle abilità con ricarica globale (GCD ~1.5 sec)"
L["Chat"] = "Chat"
L["Error Filter"] = "Filtro errori"
L["Frame"] = "Riquadri"
L["Frames"] = "Riquadri"
L["Auras"] = "Aure"
L["Frame Auras"] = "Aure dei riquadri"
L["Character Auras"] = "Aure del personaggio"
L["MainMenuBar"] = "Barra delle azioni"
L["MainMenuBar_Description"] = "Personalizza la barra delle azioni con gestione dei tasti di scelta rapida e nomi delle macro."
L["Enable_Module"] = "Abilita modulo"
L["Enable_Module_Desc"] = "Abilita o disabilita completamente il modulo Barra delle azioni."
L["Hotkeys"] = "Tasti di scelta rapida"
L["Color Indication"] = "Indicazione a colori"
L["Color_Indication_Enabled"] = "Abilita indicazione a colori"
L["Color_Indication_Enabled_Desc"] = "Abilita o disabilita l’indicazione a colori dei pulsanti della barra delle azioni"
L["Color_Cooldown_Enabled"] = "Ingrigisci in ricarica"
L["Color_Cooldown_Enabled_Desc"] = "Rendi i pulsanti grigi quando sono in ricarica per più di 1.5 secondi"
L["Color_Cooldown_Alpha"] = "Alpha ricarica"
L["Color_Cooldown_Alpha_Desc"] = "Valore alpha dei pulsanti in ricarica (0 - invisibile, 1 - predefinito)"
L["Color_Mana_Enabled"] = "Blu per risorse insufficienti"
L["Color_Mana_Enabled_Desc"] = "Rendi i pulsanti blu in caso di mancanza di mana, energia o rabbia"
L["Color_Range_Enabled"] = "Rosso fuori portata"
L["Color_Range_Enabled_Desc"] = "Rendi i pulsanti rossi quando il bersaglio è fuori portata"
L["Color_Unusable_Enabled"] = "Grigio scuro se inutilizzabile"
L["Color_Unusable_Enabled_Desc"] = "Rendi i pulsanti grigio scuro quando l’abilità non è utilizzabile"
L["Interface"] = "Interfaccia"
L["Visual"] = "Testo"
L["Hide_Hotkeys"] = "Nascondi tasti di scelta rapida"
L["Hide_Hotkeys_Desc"] = "Nascondi il testo dei tasti di scelta rapida sui pulsanti della barra delle azioni"
L["Show_In_Combat"] = "Mostra in combattimento"
L["Show_In_Combat_Desc"] = "Mostra i tasti di scelta rapida in combattimento, anche se nascosti"
L["Show_On_Alt"] = "Mostra con |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Mostra i tasti di scelta rapida tenendo premuto |cFFFFD700Alt|r"
L["Show_With_Target"] = "Mostra con bersaglio selezionato"
L["Show_With_Target_Desc"] = "Finché hai un bersaglio, mostra i tasti di scelta rapida (se nascosti); si nascondono di nuovo quando rimuovi il bersaglio. Funziona con visibilità in combattimento e Alt. Non influisce sui nomi delle macro."
L["Fade_After_Combat"] = "Dissolvenza dopo il combattimento"
L["Fade_After_Combat_Desc"] = "Comparsa/scomparsa graduale dei tasti di scelta rapida dopo il combattimento"
L["Fade_Time"] = "Tempo di dissolvenza"
L["Fade_Time_Desc"] = "Durata della dissolvenza dei tasti di scelta rapida (in secondi)"
L["Macros"] = "Macro"
L["Hide_Macro_Names"] = "Nascondi nomi delle macro"
L["Hide_Macro_Names_Desc"] = "Nascondi i nomi delle macro sui pulsanti della barra delle azioni"
L["Hide Hotkeys"] = "Nascondi tasti di scelta rapida"
L["Show in Combat"] = "Mostra in combattimento"
L["Show on Alt"] = "Mostra con |cFFFFD700Alt|r"
L["Fade After Combat"] = "Dissolvenza dopo il combattimento"
L["Fade Time"] = "Tempo di dissolvenza"
L["Hide Macro Names"] = "Nascondi nomi delle macro"
L["Color Indication Enabled"] = "Abilita indicazione a colori"
L["Cooldown Color"] = "Colore ricarica"
L["Cooldown Alpha"] = "Alpha ricarica"
L["Mana Color"] = "Colore mana"
L["Range Color"] = "Colore portata"
L["Unusable Color"] = "Colore inutilizzabile"
L["Show Panels on Alt"] = "Mostra barre con |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Nascondi grifoni"
L["Hide Decorative Elements"] = "Nascondi elementi decorativi"
L["Hide Action Bar Backgrounds"] = "Nascondi sfondi delle barre delle azioni"
L["Hide Shapeshift Backgrounds"] = "Nascondi sfondi della barra delle forme"
L["Hide Pet Bar Backgrounds"] = "Nascondi sfondi della barra del famiglio"
L["Hide Possess Bar Backgrounds"] = "Nascondi sfondi della barra di possessione"
L["Hide Bonus Bar Textures"] = "Nascondi texture della barra bonus"
L["Hide Keyring Button"] = "Nascondi pulsante del portachiavi"
L["Hide Page Buttons"] = "Nascondi pulsanti pagina"
L["Hide Max Level Bar"] = "Nascondi barra livello massimo"
L["Hide Page Numbers"] = "Nascondi numeri di pagina"
L["Show Page Numbers in Combat"] = "Mostra numeri di pagina in combattimento"
L["Show Page Numbers on Alt"] = "Mostra numeri di pagina con |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Dissolvenza numeri di pagina dopo combattimento"
L["Page Numbers Fade Time"] = "Tempo di dissolvenza numeri di pagina"
L["Hide Exp Bar"] = "Nascondi barra EXP"
L["Show Exp Bar on Alt"] = "Mostra barra EXP con |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Mostra barra EXP al guadagno"
L["Exp Bar Fade Time"] = "Tempo di dissolvenza barra EXP"
L["Exp Bar Show Time"] = "Tempo di visualizzazione barra EXP"
L["Hide Rep Bar"] = "Nascondi barra reputazione"
L["Show Rep Bar on Alt"] = "Mostra barra reputazione con |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Gain"] = "Mostra al cambio di reputazione"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Mostra temporaneamente la barra della reputazione quando si guadagna o si perde reputazione."
L["Reputation_Bar_Fade_Time"] = "Durata dissolvenza barra reputazione"
L["Reputation_Bar_Fade_Time_Desc"] = "Durata dell’animazione di comparsa/scomparsa della barra della reputazione."
L["Reputation_Bar_Show_Time"] = "Tempo di visualizzazione barra reputazione"
L["Reputation_Bar_Show_Time_Desc"] = "Per quanto tempo la barra della reputazione resta visibile dopo un cambiamento."
L["Button Border Alpha"] = "Alpha bordo pulsanti"
L["Micro Menu Alpha"] = "Alpha micromenu"
L["Button Border Alpha Enabled"] = "Abilita alpha bordo pulsanti"
L["Micro Menu Alpha Enabled"] = "Abilita alpha micromenu"
L["Minimap"] = "Minimappa"
L["Nameplates"] = "Nameplate"
L["Plates Auras"] = "Aure sui nameplate"
L["Health Indicators"] = "Indicatori di salute"
L["Health Indicators Desc"] = "Scegli il sistema di indicatori di salute / nameplate."
L["Health Indicator Type"] = "Tipo di indicatore di salute"
L["Health Indicator Type Desc"] = "ElvUI usa i nameplate integrati di ElvUI. Classic WoW usa i nameplate predefiniti di Blizzard."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Modifica delle impostazioni di visualizzazione per: %s"
L["Health Indicators Reload Notice"] = "È necessario ricaricare l’interfaccia per applicare completamente il cambio del tipo di indicatore di salute."
L["Open ElvUI NamePlates Settings"] = "Impostazioni"
L["Open ElvUI NamePlates Settings Desc"] = "Apri la finestra di configurazione di ElvUI NamePlates (/enp)."
L["Arena Frame Type"] = "Tipo di riquadri arena"
L["Arena Frame Type Desc"] = "GladiusEx usa i riquadri arena integrati di GladiusEx. Classic WoW usa il modulo arena predefinito di SarychUI."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "Apri impostazioni GladiusEx"
L["Open GladiusEx Settings Desc"] = "Apri la finestra di configurazione di GladiusEx (/gex ui)."
L["Arena Classic Settings Disabled"] = "Queste impostazioni sono disponibili solo in modalità Classic WoW."
L["Map"] = "Mappa del mondo"
L["World Map"] = "Mappa del mondo"
L["Map Module Desc"] = "Scegli quale addon mappa usare."
L["Map Type"] = "Tipo di mappa"
L["Map Type Desc"] = "Scegli quale addon mappa usare."
L["Classic WoW Map"] = "Mappa Classic WoW"
L["Open Mapster Settings"] = "Apri impostazioni Mapster"
L["Open Mapster Settings Desc"] = "Apri la finestra di configurazione di Mapster (/mapster)."
L["Open Carbonite Settings"] = "Apri impostazioni Carbonite"
L["Open Carbonite Settings Desc"] = "Apri la finestra di configurazione di Carbonite (/carb options)."
L["Map Type Reload"] = "È necessario ricaricare l’interfaccia per applicare il cambio del tipo di mappa."
L["Nameplate Distance"] = "Abilita visualizzazione distanza"
L["Nameplate Distance Desc"] = "Richiede nameplate_range.dll. Stato: Sistema -> Panoramica."
L["Nameplate Distance Tab"] = "Distanza nameplate"
L["Nameplate Distance Font Desc"] = "Font del testo della distanza sui nameplate."
L["Nameplate Distance Font Size Desc"] = "Dimensione del font del testo della distanza."
L["Nameplate Distance Offset X Desc"] = "Offset orizzontale del testo della distanza."
L["Nameplate Distance Offset Y Desc"] = "Offset verticale del testo della distanza."
L["Font Size"] = "Dimensione font"
L["Position X"] = "Posizione X"
L["Position Y"] = "Posizione Y"
L["Font Outline"] = "Contorno font"
L["Nameplate Distance Font Outline Desc"] = "Stile del contorno del testo della distanza (stesse opzioni di ElvUI NamePlates)."
L["Shadow X"] = "Ombra X"
L["Shadow Y"] = "Ombra Y"
L["Nameplate Distance Shadow X Desc"] = "Offset orizzontale dell’ombra del testo della distanza."
L["Nameplate Distance Shadow Y Desc"] = "Offset verticale dell’ombra del testo della distanza."
L["None"] = "Nessuno"
L["Reload UI"] = "Ricarica interfaccia"
L["Reload UI Desc"] = "Esegui /reload per applicare le modifiche."
L["Tools"] = "Altro"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "Il modulo Conferma automatica conferma automaticamente vari dialoghi."
L["Crowd Control module displays CC effects on your screen."] = "Il modulo Controllo di massa mostra gli effetti di CC sullo schermo."
L["Chat module enhances the chat interface with additional features."] = "Il modulo Chat migliora l’interfaccia della chat con funzioni aggiuntive."
L["Error Filter module filters out annoying error messages."] = "Il modulo Filtro errori filtra i messaggi di errore fastidiosi."
L["Frame module allows you to move and customize unit frames."] = "Il modulo Riquadri consente di spostare e personalizzare i riquadri unità."
L["Main Menu Bar module customizes the main action bar."] = "Il modulo Barra delle azioni personalizza la barra delle azioni principale."
L["Minimap module enhances and customizes the minimap."] = "Il modulo Minimappa migliora e personalizza la minimappa."
L["Plates Auras module displays auras on nameplates."] = "Il modulo Aure sui nameplate mostra le aure sui nameplate."
L["Tools module provides various utility functions."] = "Il modulo Altro fornisce varie funzioni di utilità."

-- Module description keys for options
L["Frames_Description"] = "Impostazioni di modifica dei riquadri unità"
L["Auras_Description"] = "Nascondere aure, evidenziare dissoluzione e gestire il riquadro buff del giocatore"
L["Minimap_Description"] = "Impostazioni della minimappa"
L["Chat_Description"] = "Impostazioni di chat e messaggi"
L["Tools_Description"] = "Vari strumenti e utilità"
L["MainMenuBar_Description"] = "Impostazioni della barra comandi principale e delle barre delle azioni"
L["CooldownText_Description"] = "Impostazioni del testo di ricarica e dei timer"
L["Automation_Description"] = "Automazione di varie azioni di gioco"

-- Auto Confirm
L["Confirm Loot"] = "Conferma bottino"
L["Automatically confirm loot rolls."] = "Conferma automaticamente i tiri sul bottino."
L["Confirm Bind"] = "Conferma vincolo"
L["Automatically confirm binding items."] = "Conferma automaticamente il vincolo degli oggetti."
L["Confirm Delete"] = "Conferma eliminazione"
L["Automatically confirm item deletion."] = "Conferma automaticamente l’eliminazione degli oggetti."
L["Confirm Quest"] = "Conferma missione"
L["Automatically confirm quest dialogs."] = "Conferma automaticamente i dialoghi delle missioni."

-- Crowd Control
L["Show Icon"] = "Mostra icona"
L["Show CC icon when you are affected by crowd control."] = "Mostra l’icona CC quando sei sotto controllo di massa."
L["Icon Size"] = "Dimensione icona"
L["Size of the CC icon."] = "Dimensione dell’icona CC."
L["Icon Position"] = "Posizione icona"
L["Position of the CC icon on screen."] = "Posizione dell’icona CC sullo schermo."
L["Show Timer"] = "Mostra timer"
L["Show remaining time on CC effects."] = "Mostra il tempo rimanente degli effetti di CC."

-- Chat
L["Chat Bar"] = "Barra chat"
L["Enable chat bar with quick channel buttons."] = "Abilita la barra chat con pulsanti rapidi dei canali."
L["Position"] = "Posizione"
L["Chat bar position."] = "Posizione della barra chat."
L["Timestamps"] = "Timestamp"
L["Show timestamps in chat."] = "Mostra i timestamp in chat."
L["Class Colors"] = "Colori di classe"
L["Color player names by class."] = "Colora i nomi dei giocatori in base alla classe."
L["Short Channel Names"] = "Nomi canali brevi"
L["Use abbreviated channel names."] = "Usa nomi di canale abbreviati."

-- Error Filter
L["Filters"] = "Filtri"
L["Configure which errors to filter."] = "Configura quali errori filtrare."

-- Frame
L["Move Frames"] = "Sposta riquadri"
L["Allow moving unit frames."] = "Consenti di spostare i riquadri unità."
L["Combat Indicator"] = "Indicatore di combattimento"
L["Show combat indicator on frames."] = "Mostra l’indicatore di combattimento sui riquadri."
L["Size"] = "Dimensione"
L["Frame Text"] = "Testo del riquadro"
L["Show Name"] = "Mostra nome"
L["Show Level"] = "Mostra livello"
L["Show Class"] = "Mostra classe"

-- Main Menu Bar
L["Hide Art"] = "Nascondi grafica"
L["Hide background art from the main menu bar."] = "Nascondi la grafica di sfondo della barra principale."
L["Hide Gryphons"] = "Nascondi grifoni"
L["Hide the gryphon decorations."] = "Nascondi le decorazioni dei grifoni."
L["Show Buttons"] = "Mostra pulsanti"
L["Configure which buttons to show."] = "Configura quali pulsanti mostrare."

-- Minimap
L["Shape"] = "Forma"
L["Minimap shape (square or round)."] = "Forma della minimappa (quadrata o rotonda)."
L["Square"] = "Quadrata"
L["Round"] = "Rotonda"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Abilita i pulsanti dello zoom."

-- Plates Auras
L["Show Buffs"] = "Mostra buff"
L["Display buffs on nameplates."] = "Mostra i buff sui nameplate."
L["Show Debuffs"] = "Mostra debuff"
L["Display debuffs on nameplates."] = "Mostra i debuff sui nameplate."
L["Max Icons"] = "Max icone"
L["Maximum number of icons to display."] = "Numero massimo di icone da mostrare."
L["Only Mine"] = "Solo miei"
L["Only show auras cast by you."] = "Mostra solo le aure lanciate da te."
L["Show Duration"] = "Mostra durata"
L["Display remaining duration on auras."] = "Mostra la durata rimanente delle aure."
L["Spell Settings"] = "Impostazioni incantesimo"
L["Visibility"] = "Visibilità"
L["Show this spell on nameplates"] = "Mostra questo incantesimo sui nameplate"
L["Spell Type"] = "Tipo di incantesimo"
L["Type"] = "Tipo"
L["Spell Priority"] = "Priorità incantesimo"
L["Custom Priority"] = "Priorità personalizzata"
L["Priority"] = "Priorità"
L["Higher priority spells will take precedence regardless of duration"] = "Gli incantesimi con priorità più alta hanno la precedenza indipendentemente dalla durata"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC come OK"
L["Allow ESC key to confirm dialogs."] = "Consenti al tasto ESC di confermare i dialoghi."
L["No Combat Errors"] = "Niente errori in combattimento"
L["Hide errors during combat."] = "Nascondi gli errori durante il combattimento."
L["Speedy Load"] = "Caricamento rapido"
L["Faster addon loading."] = "Caricamento addon più veloce."

-- Positions
L["Top"] = "Alto"
L["Bottom"] = "Basso"
L["Left"] = "Sinistra"
L["Right"] = "Destra"
L["Center"] = "Centro"
L["Top Left"] = "In alto a sinistra"
L["Top Right"] = "In alto a destra"
L["Bottom Left"] = "In basso a sinistra"
L["Bottom Right"] = "In basso a destra"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+Clic sulla scheda – |cFFFFD700finestra di copia|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Abilita la copia della chat con Ctrl+Clic sulla scheda chat"
L["Messages"] = "Messaggi: %d"
L["Drag_to_size"] = "Trascina per ridimensionare | Clic destro per chiudere"

-- Tooltip Settings
L["Tooltip_Settings"] = "Impostazioni finestra"
L["Enable_Tooltip_Position"] = "Cambia posizione della finestra"
L["Enable_Tooltip_Position_Desc"] = "Abilita il posizionamento personalizzato della finestra tooltip"
L["Tooltip_Base_Offset"] = "Offset base"
L["Tooltip_Base_Offset_Desc"] = "Offset base della finestra tooltip"
L["Tooltip_Pet_Offset"] = "Offset famiglio"
L["Tooltip_Pet_Offset_Desc"] = "Offset aggiuntivo della finestra tooltip quando il famiglio è attivo"
L["Enable_Chat_Icons"] = "Mostra icone nella finestra tooltip"
L["Enable_Chat_Icons_Desc"] = "Mostra icone di oggetti, incantesimi e imprese nei messaggi della chat"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Nascondi pulsante amici"
L["Enable_Friends_Button_Mod_Desc"] = "Nascondi il pulsante amici nella chat"
L["Enable_Hide_Chat_Frame_Button"] = "Nascondi pulsante comunicazione"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Nascondi pulsante comunicazione"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Nascondi il pulsante comunicazione nella chat"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Nascondi frecce su e giù"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Nascondi le frecce di scorrimento su e giù nella chat"
L["Enable_Hide_Chat_Bottom_Button"] = "Nascondi freccia vai in fondo"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Nascondi la freccia vai in fondo nella chat"

-- Chat Animations
L["Chat_Animations"] = "Animazioni chat"
L["Enable_Chat_Animations"] = "Abilita animazioni chat"
L["Enable_Chat_Animations_Desc"] = "Abilita le animazioni personalizzate della chat"
L["Chat_Tab_Show_Delay"] = "Ritardo mostra schede (sec)"
L["Chat_Tab_Show_Delay_Desc"] = "Ritardo prima di mostrare le schede della chat"
L["Chat_Tab_Hide_Delay"] = "Ritardo nascondi schede (sec)"
L["Chat_Tab_Hide_Delay_Desc"] = "Ritardo prima di nascondere le schede della chat"
L["Chat_Frame_Fade_Time"] = "Durata comparsa (sec)"
L["Chat_Frame_Fade_Time_Desc"] = "Durata dell’animazione di comparsa della chat"
L["Chat_Frame_Fade_Out_Time"] = "Durata scomparsa (sec)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Durata dell’animazione di scomparsa della chat"

-- Messages
L["Profile reset to defaults."] = "Profilo reimpostato ai valori predefiniti."
L["Module enabled."] = "Modulo abilitato."
L["Module disabled."] = "Modulo disabilitato."

SarychUI.RegisterLocale("itIT", L)
