-- SarychUI koKR Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "일반"
L["Enable"] = "사용"
L["Disable"] = "사용 안 함"
L["Enabled"] = "사용 중"
L["Settings"] = "설정"
L["Options"] = "옵션"
L["Reset"] = "초기화"
L["Default"] = "기본값"

-- System / wow_optimize compatibility
L["System"] = "시스템"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "wow_optimize.dll용 선택적 호환 모드입니다. 활성화되면 SarychUI는 GC/전투 기록 수정을 중복하지 않으며, 무거운 이름표 및 말풍선 스캔을 줄입니다."
L["WowOptimize_Mode"] = "호환 모드"
L["WowOptimize_Mode_Desc"] = "자동 — DLL 전역 변수로 감지 (LUABOOST_DLL_*). 사용 — 강제 켜기. 사용 안 함 — 일반 SarychUI."
L["WowOptimize_Mode_Auto"] = "자동"
L["WowOptimize_Mode_Enabled"] = "사용"
L["WowOptimize_Mode_Disabled"] = "사용 안 함"
L["WowOptimize_Debug"] = "호환성 디버그 로그"
L["WowOptimize_Debug_Desc"] = "적용된 적응 내용을 대화창에 출력합니다 (또는 DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "개요"
L["Dll_Detection_Header"] = "DLL 감지"
L["Dll_Status_Detected"] = "감지됨"
L["Dll_Status_NotDetected"] = "감지되지 않음"
L["Dll_Status_Checking"] = "확인 중..."
L["Dll_Status_NoMarker"] = "Lua 마커 없음"
L["Dll_Status_ApiDetected"] = "API 감지됨"
L["Dll_Status_WaitingNameplates"] = "이름표 대기 중"
L["Runtime_LuaOptimize"] = "Lua 최적화"
L["Runtime_EnableGC"] = "가비지 컬렉션 관리자 사용"
L["Runtime_EnableGC_Desc"] = "모드별 증분 GC (일반 / 전투 / 대기 / 로딩). wow_optimize.dll이 활성화되면 GC는 DLL이 담당합니다."
L["Runtime_Preset"] = "GC 프로필"
L["Runtime_Preset_Light"] = "가벼움"
L["Runtime_Preset_Standard"] = "표준"
L["Runtime_Preset_Heavy"] = "무거움"
L["Runtime_Preset_Custom"] = "사용자 지정"
L["Runtime_StepNormal"] = "GC step (일반), KB"
L["Runtime_StepCombat"] = "GC step (전투), KB"
L["Runtime_StepIdle"] = "GC step (대기), KB"
L["Runtime_StepLoading"] = "GC step (로딩), KB"
L["Runtime_EmergencyMB"] = "긴급 전체 GC 임계값, MB"
L["Runtime_IdleTimeout"] = "대기 시간 초과, 초"
L["Runtime_SpeedyLoad"] = "로딩 화면 최적화"
L["Runtime_SpeedyLoadMode"] = "로딩 모드"
L["Runtime_SpeedyLoadSafe"] = "안전"
L["Runtime_SpeedyLoadAggressive"] = "적극적"
L["Runtime_Debug"] = "진단 출력"
L["Runtime_DllStatus"] = "wow_optimize.dll 상태"
L["Runtime_DllOwnsGC"] = "GC는 wow_optimize.dll이 담당합니다 — Lua 스테핑이 비활성화됩니다."
L["Runtime_ForceGC"] = "지금 전체 수집 (비전투)"
L["Runtime_ForceGC_Desc"] = "전투 중이 아닐 때 전체 가비지 컬렉션을 실행합니다. 전투 중에는 사용할 수 없습니다."
L["Runtime_BlockedByLuaBoost"] = "!LuaBoost 애드온이 감지되었습니다. 충돌을 피하기 위해 SarychUI GC 관리가 비활성화되었습니다. 이 옵션을 사용하려면 !LuaBoost를 끄거나 제거하세요."

-- Modules
L["Modules"] = "모듈"
L["Auto Confirm"] = "자동 확인"
L["Crowd Control"] = "군중 제어"
L["Cooldown Text"] = "재사용 대기시간 및 타이머"
L["Font_Path"] = "글꼴 경로"
L["Font_Path_Desc"] = ".ttf 전체 경로 (예: Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "글꼴 스타일"
L["Font_Flags_Desc"] = "옵션: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "글자 크기 (< 60초)"
L["Font_Size_Small_Desc"] = "남은 시간이 60초 미만일 때의 글자 크기"
L["Font_Size_Medium"] = "글자 크기 (1–10분)"
L["Font_Size_Medium_Desc"] = "1:00–9:59 및 ≥10분일 때의 글자 크기"
L["Font_Size_Large"] = "글자 크기 (>10분)"
L["Font_Size_Large_Desc"] = "분 단위 값이 ≥ 10일 때의 글자 크기"
L["Default_Color"] = "기본 글자 색"
L["Appearance"] = "외형"
L["Display_Conditions"] = "표시 조건"
L["Behavior"] = "동작"
L["Min_Scale"] = "최소 배율"
L["Min_Scale_Desc"] = "아이콘 유효 배율이 더 낮으면 텍스트를 숨깁니다"
L["Min_Icon_Size"] = "최소 아이콘 크기"
L["Min_Icon_Size_Desc"] = "아이콘 너비/높이가 더 작으면 텍스트를 숨깁니다"
L["Hide_On_GCD"] = "GCD 중 숨기기"
L["Hide_On_GCD_Desc"] = "전역 재사용 대기시간(GCD ~1.5초)이 있는 기술의 재사용 대기시간 텍스트를 숨깁니다"
L["Chat"] = "대화"
L["Error Filter"] = "오류 필터"
L["Frame"] = "프레임"
L["Frames"] = "프레임"
L["Auras"] = "오라"
L["Frame Auras"] = "프레임 오라"
L["Character Auras"] = "캐릭터 오라"
L["MainMenuBar"] = "행동 단축바"
L["MainMenuBar_Description"] = "단축키 관리와 매크로 이름 설정으로 행동 단축바를 사용자 지정합니다."
L["Enable_Module"] = "모듈 사용"
L["Enable_Module_Desc"] = "행동 단축바 모듈을 완전히 켜거나 끕니다."
L["Hotkeys"] = "단축키"
L["Color Indication"] = "색상 표시"
L["Color_Indication_Enabled"] = "색상 표시 사용"
L["Color_Indication_Enabled_Desc"] = "행동 단축바 버튼의 색상 표시를 켜거나 끕니다"
L["Color_Cooldown_Enabled"] = "재사용 대기 중 회색 처리"
L["Color_Cooldown_Enabled_Desc"] = "재사용 대기시간이 1.5초를 넘으면 버튼을 회색으로 만듭니다"
L["Color_Cooldown_Alpha"] = "재사용 대기 Alpha"
L["Color_Cooldown_Alpha_Desc"] = "재사용 대기 중 버튼의 Alpha 값 (0 - 투명, 1 - 기본)"
L["Color_Mana_Enabled"] = "자원 부족 시 파란색"
L["Color_Mana_Enabled_Desc"] = "마나, 기력 또는 분노가 부족할 때 버튼을 파란색으로 만듭니다"
L["Color_Range_Enabled"] = "사거리 밖 빨간색"
L["Color_Range_Enabled_Desc"] = "대상이 사거리 밖일 때 버튼을 빨간색으로 만듭니다"
L["Color_Unusable_Enabled"] = "사용 불가 시 어두운 회색"
L["Color_Unusable_Enabled_Desc"] = "기술을 사용할 수 없을 때 버튼을 어두운 회색으로 만듭니다"
L["Interface"] = "인터페이스"
L["Visual"] = "텍스트"
L["Hide_Hotkeys"] = "단축키 숨기기"
L["Hide_Hotkeys_Desc"] = "행동 단축바 버튼의 단축키 텍스트를 숨깁니다"
L["Show_In_Combat"] = "전투 중 표시"
L["Show_In_Combat_Desc"] = "단축키가 숨겨져 있어도 전투 중에는 표시합니다"
L["Show_On_Alt"] = "|cFFFFD700Alt|r 누를 때 표시"
L["Show_On_Alt_Desc"] = "|cFFFFD700Alt|r 키를 누르고 있을 때 단축키를 표시합니다"
L["Show_With_Target"] = "대상 선택 시 표시"
L["Show_With_Target_Desc"] = "대상이 있을 때 단축키를 표시합니다(숨김 설정일 때). 대상을 해제하면 다시 숨깁니다. 전투 및 Alt 표시와 함께 동작합니다. 매크로 이름에는 영향을 주지 않습니다."
L["Fade_After_Combat"] = "전투 후 페이드"
L["Fade_After_Combat_Desc"] = "전투 후 단축키의 부드러운 나타남/사라짐"
L["Fade_Time"] = "페이드 시간"
L["Fade_Time_Desc"] = "단축키 부드러운 페이드 시간(초)"
L["Macros"] = "매크로"
L["Hide_Macro_Names"] = "매크로 이름 숨기기"
L["Hide_Macro_Names_Desc"] = "행동 단축바 버튼의 매크로 이름을 숨깁니다"
L["Hide Hotkeys"] = "단축키 숨기기"
L["Show in Combat"] = "전투 중 표시"
L["Show on Alt"] = "|cFFFFD700Alt|r 누를 때 표시"
L["Fade After Combat"] = "전투 후 페이드"
L["Fade Time"] = "페이드 시간"
L["Hide Macro Names"] = "매크로 이름 숨기기"
L["Color Indication Enabled"] = "색상 표시 사용"
L["Cooldown Color"] = "재사용 대기 색"
L["Cooldown Alpha"] = "재사용 대기 Alpha"
L["Mana Color"] = "마나 색"
L["Range Color"] = "사거리 색"
L["Unusable Color"] = "사용 불가 색"
L["Show Panels on Alt"] = "|cFFFFD700Alt|r 누를 때 패널 표시"
L["Hide Gryphons"] = "그리폰 숨기기"
L["Hide Decorative Elements"] = "장식 요소 숨기기"
L["Hide Action Bar Backgrounds"] = "행동 단축바 배경 숨기기"
L["Hide Shapeshift Backgrounds"] = "변신 바 배경 숨기기"
L["Hide Pet Bar Backgrounds"] = "소환수 바 배경 숨기기"
L["Hide Possess Bar Backgrounds"] = "빙의 바 배경 숨기기"
L["Hide Bonus Bar Textures"] = "보너스 바 텍스처 숨기기"
L["Hide Keyring Button"] = "열쇠고리 버튼 숨기기"
L["Hide Page Buttons"] = "페이지 버튼 숨기기"
L["Hide Max Level Bar"] = "최대 레벨 바 숨기기"
L["Hide Page Numbers"] = "페이지 번호 숨기기"
L["Show Page Numbers in Combat"] = "전투 중 페이지 번호 표시"
L["Show Page Numbers on Alt"] = "|cFFFFD700Alt|r 누를 때 페이지 번호 표시"
L["Page Numbers Fade After Combat"] = "전투 후 페이지 번호 페이드"
L["Page Numbers Fade Time"] = "페이지 번호 페이드 시간"
L["Hide Exp Bar"] = "경험치 바 숨기기"
L["Show Exp Bar on Alt"] = "|cFFFFD700Alt|r 누를 때 경험치 바 표시"
L["Show Exp Bar on Gain"] = "획득 시 경험치 바 표시"
L["Exp Bar Fade Time"] = "경험치 바 페이드 시간"
L["Exp Bar Show Time"] = "경험치 바 표시 시간"
L["Hide Rep Bar"] = "평판 바 숨기기"
L["Show Rep Bar on Alt"] = "|cFFFFD700Alt|r 누를 때 평판 바 표시"
L["Show_Reputation_Bar_On_Gain"] = "평판 변경 시 표시"
L["Show_Reputation_Bar_On_Gain_Desc"] = "평판을 얻거나 잃을 때 평판 바를 잠시 표시합니다."
L["Reputation_Bar_Fade_Time"] = "평판 바 페이드 지속 시간"
L["Reputation_Bar_Fade_Time_Desc"] = "평판 바 나타남/사라짐 애니메이션 지속 시간입니다."
L["Reputation_Bar_Show_Time"] = "평판 바 표시 시간"
L["Reputation_Bar_Show_Time_Desc"] = "평판 변경 후 평판 바가 보이는 시간입니다."
L["Button Border Alpha"] = "버튼 테두리 Alpha"
L["Micro Menu Alpha"] = "마이크로 메뉴 Alpha"
L["Button Border Alpha Enabled"] = "버튼 테두리 Alpha 사용"
L["Micro Menu Alpha Enabled"] = "마이크로 메뉴 Alpha 사용"
L["Minimap"] = "미니맵"
L["Nameplates"] = "이름표"
L["Plates Auras"] = "이름표 오라"
L["Health Indicators"] = "생명력 표시"
L["Health Indicators Desc"] = "생명력 표시 / 이름표 시스템을 선택합니다."
L["Health Indicator Type"] = "생명력 표시 유형"
L["Health Indicator Type Desc"] = "ElvUI는 내장 ElvUI 이름표를 사용합니다. Classic WoW는 기본 블리자드 이름표를 사용합니다."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "표시 설정 편집 중: %s"
L["Health Indicators Reload Notice"] = "생명력 표시 유형 변경을 완전히 적용하려면 UI를 다시 불러와야 합니다."
L["Open ElvUI NamePlates Settings"] = "설정"
L["Open ElvUI NamePlates Settings Desc"] = "ElvUI NamePlates 설정 창을 엽니다 (/enp)."
L["Arena Frame Type"] = "투기장 프레임 유형"
L["Arena Frame Type Desc"] = "GladiusEx는 내장 GladiusEx 투기장 프레임을 사용합니다. Classic WoW는 기본 SarychUI 투기장 모듈을 사용합니다."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "GladiusEx 설정 열기"
L["Open GladiusEx Settings Desc"] = "GladiusEx 설정 창을 엽니다 (/gex ui)."
L["Arena Classic Settings Disabled"] = "이 설정은 Classic WoW 모드에서만 사용할 수 있습니다."
L["Map"] = "세계 지도"
L["World Map"] = "세계 지도"
L["Map Module Desc"] = "사용할 지도 애드온을 선택합니다."
L["Map Type"] = "지도 유형"
L["Map Type Desc"] = "사용할 지도 애드온을 선택합니다."
L["Classic WoW Map"] = "Classic WoW 지도"
L["Open Mapster Settings"] = "Mapster 설정 열기"
L["Open Mapster Settings Desc"] = "Mapster 설정 창을 엽니다 (/mapster)."
L["Open Carbonite Settings"] = "Carbonite 설정 열기"
L["Open Carbonite Settings Desc"] = "Carbonite 설정 창을 엽니다 (/carb options)."
L["Map Type Reload"] = "지도 유형 변경을 적용하려면 UI를 다시 불러와야 합니다."
L["Nameplate Distance"] = "거리 표시 사용"
L["Nameplate Distance Desc"] = "nameplate_range.dll이 필요합니다. 상태: 시스템 -> 개요."
L["Nameplate Distance Tab"] = "이름표 거리"
L["Nameplate Distance Font Desc"] = "이름표 거리 텍스트의 글꼴입니다."
L["Nameplate Distance Font Size Desc"] = "거리 텍스트의 글꼴 크기입니다."
L["Nameplate Distance Offset X Desc"] = "거리 텍스트의 가로 오프셋입니다."
L["Nameplate Distance Offset Y Desc"] = "거리 텍스트의 세로 오프셋입니다."
L["Font Size"] = "글꼴 크기"
L["Position X"] = "위치 X"
L["Position Y"] = "위치 Y"
L["Font Outline"] = "글꼴 외곽선"
L["Nameplate Distance Font Outline Desc"] = "거리 텍스트의 외곽선 스타일입니다 (ElvUI NamePlates와 동일한 옵션)."
L["Shadow X"] = "그림자 X"
L["Shadow Y"] = "그림자 Y"
L["Nameplate Distance Shadow X Desc"] = "거리 텍스트 그림자의 가로 오프셋입니다."
L["Nameplate Distance Shadow Y Desc"] = "거리 텍스트 그림자의 세로 오프셋입니다."
L["None"] = "없음"
L["Reload UI"] = "UI 다시 불러오기"
L["Reload UI Desc"] = "변경 사항을 적용하려면 /reload를 실행하세요."
L["Tools"] = "기타"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "자동 확인 모듈은 다양한 대화 상자를 자동으로 확인합니다."
L["Crowd Control module displays CC effects on your screen."] = "군중 제어 모듈은 CC 효과를 화면에 표시합니다."
L["Chat module enhances the chat interface with additional features."] = "대화 모듈은 대화 인터페이스에 추가 기능을 제공합니다."
L["Error Filter module filters out annoying error messages."] = "오류 필터 모듈은 성가신 오류 메시지를 걸러냅니다."
L["Frame module allows you to move and customize unit frames."] = "프레임 모듈은 유닛 프레임을 이동하고 사용자 지정할 수 있게 합니다."
L["Main Menu Bar module customizes the main action bar."] = "행동 단축바 모듈은 주 행동 단축바를 사용자 지정합니다."
L["Minimap module enhances and customizes the minimap."] = "미니맵 모듈은 미니맵을 개선하고 사용자 지정합니다."
L["Plates Auras module displays auras on nameplates."] = "이름표 오라 모듈은 이름표에 오라를 표시합니다."
L["Tools module provides various utility functions."] = "기타 모듈은 다양한 유틸리티 기능을 제공합니다."

-- Module description keys for options
L["Frames_Description"] = "유닛 프레임 수정 설정"
L["Auras_Description"] = "오라 숨기기, 해제 강조, 플레이어 버프 프레임 관리"
L["Minimap_Description"] = "미니맵 설정"
L["Chat_Description"] = "대화 및 메시지 설정"
L["Tools_Description"] = "다양한 도구 및 유틸리티"
L["MainMenuBar_Description"] = "주 명령 바와 행동 단축바 설정"
L["CooldownText_Description"] = "재사용 대기시간 텍스트 및 타이머 표시 설정"
L["Automation_Description"] = "다양한 게임 동작 자동화"

-- Auto Confirm
L["Confirm Loot"] = "전리품 확인"
L["Automatically confirm loot rolls."] = "전리품 주사위를 자동으로 확인합니다."
L["Confirm Bind"] = "귀속 확인"
L["Automatically confirm binding items."] = "아이템 귀속을 자동으로 확인합니다."
L["Confirm Delete"] = "삭제 확인"
L["Automatically confirm item deletion."] = "아이템 삭제를 자동으로 확인합니다."
L["Confirm Quest"] = "퀘스트 확인"
L["Automatically confirm quest dialogs."] = "퀘스트 대화 상자를 자동으로 확인합니다."

-- Crowd Control
L["Show Icon"] = "아이콘 표시"
L["Show CC icon when you are affected by crowd control."] = "군중 제어에 걸렸을 때 CC 아이콘을 표시합니다."
L["Icon Size"] = "아이콘 크기"
L["Size of the CC icon."] = "CC 아이콘의 크기입니다."
L["Icon Position"] = "아이콘 위치"
L["Position of the CC icon on screen."] = "화면상 CC 아이콘 위치입니다."
L["Show Timer"] = "타이머 표시"
L["Show remaining time on CC effects."] = "CC 효과의 남은 시간을 표시합니다."

-- Chat
L["Chat Bar"] = "대화 바"
L["Enable chat bar with quick channel buttons."] = "빠른 채널 버튼이 있는 대화 바를 사용합니다."
L["Position"] = "위치"
L["Chat bar position."] = "대화 바 위치입니다."
L["Timestamps"] = "시간 표시"
L["Show timestamps in chat."] = "대화에 시간 표시를 보여줍니다."
L["Class Colors"] = "직업 색상"
L["Color player names by class."] = "플레이어 이름을 직업색으로 표시합니다."
L["Short Channel Names"] = "짧은 채널 이름"
L["Use abbreviated channel names."] = "축약된 채널 이름을 사용합니다."

-- Error Filter
L["Filters"] = "필터"
L["Configure which errors to filter."] = "필터링할 오류를 설정합니다."

-- Frame
L["Move Frames"] = "프레임 이동"
L["Allow moving unit frames."] = "유닛 프레임 이동을 허용합니다."
L["Combat Indicator"] = "전투 표시"
L["Show combat indicator on frames."] = "프레임에 전투 표시를 보여줍니다."
L["Size"] = "크기"
L["Frame Text"] = "프레임 텍스트"
L["Show Name"] = "이름 표시"
L["Show Level"] = "레벨 표시"
L["Show Class"] = "직업 표시"

-- Main Menu Bar
L["Hide Art"] = "장식 숨기기"
L["Hide background art from the main menu bar."] = "주 메뉴 바의 배경 장식을 숨깁니다."
L["Hide Gryphons"] = "그리폰 숨기기"
L["Hide the gryphon decorations."] = "그리폰 장식을 숨깁니다."
L["Show Buttons"] = "버튼 표시"
L["Configure which buttons to show."] = "표시할 버튼을 설정합니다."

-- Minimap
L["Shape"] = "모양"
L["Minimap shape (square or round)."] = "미니맵 모양 (사각형 또는 원형)."
L["Square"] = "사각형"
L["Round"] = "원형"
L["Zoom"] = "확대/축소"
L["Enable zoom buttons."] = "확대/축소 버튼을 사용합니다."

-- Plates Auras
L["Show Buffs"] = "버프 표시"
L["Display buffs on nameplates."] = "이름표에 버프를 표시합니다."
L["Show Debuffs"] = "디버프 표시"
L["Display debuffs on nameplates."] = "이름표에 디버프를 표시합니다."
L["Max Icons"] = "최대 아이콘"
L["Maximum number of icons to display."] = "표시할 최대 아이콘 수입니다."
L["Only Mine"] = "내 것만"
L["Only show auras cast by you."] = "내가 시전한 오라만 표시합니다."
L["Show Duration"] = "지속 시간 표시"
L["Display remaining duration on auras."] = "오라의 남은 지속 시간을 표시합니다."
L["Spell Settings"] = "주문 설정"
L["Visibility"] = "표시"
L["Show this spell on nameplates"] = "이 주문을 이름표에 표시"
L["Spell Type"] = "주문 유형"
L["Type"] = "유형"
L["Spell Priority"] = "주문 우선순위"
L["Custom Priority"] = "사용자 지정 우선순위"
L["Priority"] = "우선순위"
L["Higher priority spells will take precedence regardless of duration"] = "우선순위가 높은 주문이 지속 시간과 관계없이 우선합니다"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC로 확인"
L["Allow ESC key to confirm dialogs."] = "ESC 키로 대화 상자를 확인할 수 있게 합니다."
L["No Combat Errors"] = "전투 중 오류 숨기기"
L["Hide errors during combat."] = "전투 중 오류를 숨깁니다."
L["Speedy Load"] = "빠른 로딩"
L["Faster addon loading."] = "애드온을 더 빠르게 불러옵니다."

-- Positions
L["Top"] = "위"
L["Bottom"] = "아래"
L["Left"] = "왼쪽"
L["Right"] = "오른쪽"
L["Center"] = "가운데"
L["Top Left"] = "왼쪽 위"
L["Top Right"] = "오른쪽 위"
L["Bottom Left"] = "왼쪽 아래"
L["Bottom Right"] = "오른쪽 아래"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "탭 Ctrl+클릭 – |cFFFFD700복사 창|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "대화 탭을 Ctrl+클릭하여 대화 복사를 사용합니다"
L["Messages"] = "메시지: %d"
L["Drag_to_size"] = "드래그하여 크기 조절 | 오른쪽 클릭으로 닫기"

-- Tooltip Settings
L["Tooltip_Settings"] = "창 설정"
L["Enable_Tooltip_Position"] = "창 위치 변경"
L["Enable_Tooltip_Position_Desc"] = "툴팁 창의 사용자 지정 위치를 사용합니다"
L["Tooltip_Base_Offset"] = "기본 오프셋"
L["Tooltip_Base_Offset_Desc"] = "툴팁 창의 기본 오프셋"
L["Tooltip_Pet_Offset"] = "소환수 오프셋"
L["Tooltip_Pet_Offset_Desc"] = "소환수가 활성일 때 툴팁 창의 추가 오프셋"
L["Enable_Chat_Icons"] = "툴팁 창에 아이콘 표시"
L["Enable_Chat_Icons_Desc"] = "대화 메시지에 아이템, 주문, 업적 아이콘을 표시합니다"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "친구 버튼 숨기기"
L["Enable_Friends_Button_Mod_Desc"] = "대화의 친구 버튼을 숨깁니다"
L["Enable_Hide_Chat_Frame_Button"] = "대화 버튼 숨기기"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "대화 버튼 숨기기"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "대화의 대화 버튼을 숨깁니다"
L["Enable_Hide_Chat_Scroll_Buttons"] = "위/아래 화살표 숨기기"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "대화의 위/아래 스크롤 화살표를 숨깁니다"
L["Enable_Hide_Chat_Bottom_Button"] = "맨 아래로 화살표 숨기기"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "대화의 맨 아래로 화살표를 숨깁니다"

-- Chat Animations
L["Chat_Animations"] = "대화 애니메이션"
L["Enable_Chat_Animations"] = "대화 애니메이션 사용"
L["Enable_Chat_Animations_Desc"] = "사용자 지정 대화 애니메이션을 사용합니다"
L["Chat_Tab_Show_Delay"] = "탭 표시 지연 (초)"
L["Chat_Tab_Show_Delay_Desc"] = "대화 탭을 표시하기 전 지연 시간"
L["Chat_Tab_Hide_Delay"] = "탭 숨김 지연 (초)"
L["Chat_Tab_Hide_Delay_Desc"] = "대화 탭을 숨기기 전 지연 시간"
L["Chat_Frame_Fade_Time"] = "나타남 지속 시간 (초)"
L["Chat_Frame_Fade_Time_Desc"] = "대화 나타남 애니메이션 지속 시간"
L["Chat_Frame_Fade_Out_Time"] = "사라짐 지속 시간 (초)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "대화 사라짐 애니메이션 지속 시간"

-- Messages
L["Profile reset to defaults."] = "프로필이 기본값으로 초기화되었습니다."
L["Module enabled."] = "모듈이 사용되었습니다."
L["Module disabled."] = "모듈이 사용 안 함으로 설정되었습니다."

SarychUI.RegisterLocale("koKR", L)
