-- SarychUI ptBR Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "Geral"
L["Enable"] = "Ativar"
L["Disable"] = "Desativar"
L["Enabled"] = "Ativado"
L["Settings"] = "Configurações"
L["Options"] = "Opções"
L["Reset"] = "Redefinir"
L["Default"] = "Padrão"

-- System / wow_optimize compatibility
L["System"] = "Sistema"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Modo de compatibilidade opcional com wow_optimize.dll. Quando ativo, o SarychUI evita duplicar correções de GC/combat log e reduz varreduras pesadas de nameplates e balões de bate-papo."
L["WowOptimize_Mode"] = "Modo de compatibilidade"
L["WowOptimize_Mode_Desc"] = "Auto — detectar via globais da DLL (LUABOOST_DLL_*). Ativado — forçar ligado. Desativado — SarychUI normal."
L["WowOptimize_Mode_Auto"] = "Auto"
L["WowOptimize_Mode_Enabled"] = "Ativado"
L["WowOptimize_Mode_Disabled"] = "Desativado"
L["WowOptimize_Debug"] = "Log de depuração de compatibilidade"
L["WowOptimize_Debug_Desc"] = "Exibir no bate-papo as adaptações aplicadas (ou defina DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Visão geral"
L["Dll_Detection_Header"] = "Detecção de DLL"
L["Dll_Status_Detected"] = "Detectada"
L["Dll_Status_NotDetected"] = "Não detectada"
L["Dll_Status_Checking"] = "Verificando..."
L["Dll_Status_NoMarker"] = "Sem marcador Lua"
L["Dll_Status_ApiDetected"] = "API detectada"
L["Dll_Status_WaitingNameplates"] = "Aguardando nameplates"
L["Runtime_LuaOptimize"] = "Otimização Lua"
L["Runtime_EnableGC"] = "Ativar gerenciador de coleta de lixo"
L["Runtime_EnableGC_Desc"] = "GC incremental por modo (normal / combate / ocioso / carregamento). Com wow_optimize.dll ativa, o GC fica a cargo da DLL."
L["Runtime_Preset"] = "Perfil de GC"
L["Runtime_Preset_Light"] = "Leve"
L["Runtime_Preset_Standard"] = "Padrão"
L["Runtime_Preset_Heavy"] = "Pesado"
L["Runtime_Preset_Custom"] = "Personalizado"
L["Runtime_StepNormal"] = "GC step (normal), KB"
L["Runtime_StepCombat"] = "GC step (combate), KB"
L["Runtime_StepIdle"] = "GC step (ocioso), KB"
L["Runtime_StepLoading"] = "GC step (carregamento), KB"
L["Runtime_EmergencyMB"] = "Limite de GC total de emergência, MB"
L["Runtime_IdleTimeout"] = "Tempo ocioso, seg"
L["Runtime_SpeedyLoad"] = "Otimização da tela de carregamento"
L["Runtime_SpeedyLoadMode"] = "Modo de carregamento"
L["Runtime_SpeedyLoadSafe"] = "Seguro"
L["Runtime_SpeedyLoadAggressive"] = "Agressivo"
L["Runtime_Debug"] = "Saída diagnóstica"
L["Runtime_DllStatus"] = "Status do wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "O GC é controlado pelo wow_optimize.dll — o stepping em Lua está desativado."
L["Runtime_ForceGC"] = "Coleta total agora (fora de combate)"
L["Runtime_ForceGC_Desc"] = "Executa uma coleta de lixo completa fora de combate. Indisponível em combate."
L["Runtime_BlockedByLuaBoost"] = "Addon !LuaBoost detectado. O gerenciamento de GC do SarychUI está desativado para evitar conflitos. Desative ou remova o !LuaBoost para usar esta opção."

-- Modules
L["Modules"] = "Módulos"
L["Auto Confirm"] = "Confirmação automática"
L["Crowd Control"] = "Controle de multidão"
L["Cooldown Text"] = "Recargas e temporizadores"
L["Font_Path"] = "Caminho da fonte"
L["Font_Path_Desc"] = "Caminho completo do .ttf (ex.: Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Estilo da fonte"
L["Font_Flags_Desc"] = "Opções: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Tamanho do texto (< 60s)"
L["Font_Size_Small_Desc"] = "Tamanho do texto para tempo restante abaixo de 60 segundos"
L["Font_Size_Medium"] = "Tamanho do texto (1–10 min)"
L["Font_Size_Medium_Desc"] = "Tamanho do texto para 1:00–9:59 e ≥10 minutos"
L["Font_Size_Large"] = "Tamanho do texto (>10 min)"
L["Font_Size_Large_Desc"] = "Tamanho do texto para valores em minutos ≥ 10"
L["Default_Color"] = "Cor padrão do texto"
L["Appearance"] = "Aparência"
L["Display_Conditions"] = "Condições de exibição"
L["Behavior"] = "Comportamento"
L["Min_Scale"] = "Escala mínima"
L["Min_Scale_Desc"] = "Ocultar texto quando a escala efetiva do ícone for menor"
L["Min_Icon_Size"] = "Tamanho mínimo do ícone"
L["Min_Icon_Size_Desc"] = "Ocultar texto se a largura/altura do ícone for menor"
L["Hide_On_GCD"] = "Ocultar no GCD"
L["Hide_On_GCD_Desc"] = "Ocultar texto de recarga em habilidades com cooldown global (GCD ~1.5 s)"
L["Chat"] = "Bate-papo"
L["Error Filter"] = "Filtro de erros"
L["Frame"] = "Quadros"
L["Frames"] = "Quadros"
L["Auras"] = "Auras"
L["Frame Auras"] = "Auras dos quadros"
L["Character Auras"] = "Auras do personagem"
L["MainMenuBar"] = "Barra de ações"
L["MainMenuBar_Description"] = "Personalize a barra de ações com gerenciamento de atalhos e nomes de macros."
L["Enable_Module"] = "Ativar módulo"
L["Enable_Module_Desc"] = "Ativar ou desativar completamente o módulo da Barra de ações."
L["Hotkeys"] = "Atalhos"
L["Color Indication"] = "Indicação por cor"
L["Color_Indication_Enabled"] = "Ativar indicação por cor"
L["Color_Indication_Enabled_Desc"] = "Ativar ou desativar a indicação por cor nos botões da barra de ações"
L["Color_Cooldown_Enabled"] = "Acinzentar em recarga"
L["Color_Cooldown_Enabled_Desc"] = "Deixar os botões cinza quando estiverem em recarga por mais de 1.5 segundos"
L["Color_Cooldown_Alpha"] = "Alpha da recarga"
L["Color_Cooldown_Alpha_Desc"] = "Valor de alpha dos botões em recarga (0 - invisível, 1 - padrão)"
L["Color_Mana_Enabled"] = "Azul por recursos insuficientes"
L["Color_Mana_Enabled_Desc"] = "Deixar os botões azuis quando faltar mana, energia ou raiva"
L["Color_Range_Enabled"] = "Vermelho fora de alcance"
L["Color_Range_Enabled_Desc"] = "Deixar os botões vermelhos quando o alvo estiver fora de alcance"
L["Color_Unusable_Enabled"] = "Cinza escuro quando inutilizável"
L["Color_Unusable_Enabled_Desc"] = "Deixar os botões cinza escuro quando a habilidade não puder ser usada"
L["Interface"] = "Interface"
L["Visual"] = "Texto"
L["Hide_Hotkeys"] = "Ocultar atalhos"
L["Hide_Hotkeys_Desc"] = "Ocultar o texto dos atalhos nos botões da barra de ações"
L["Show_In_Combat"] = "Mostrar em combate"
L["Show_In_Combat_Desc"] = "Mostrar atalhos durante o combate, mesmo se estiverem ocultos"
L["Show_On_Alt"] = "Mostrar com |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Mostrar atalhos enquanto a tecla |cFFFFD700Alt|r estiver pressionada"
L["Show_With_Target"] = "Mostrar com alvo selecionado"
L["Show_With_Target_Desc"] = "Enquanto houver um alvo, mostrar os atalhos (quando ocultos); eles somem de novo ao limpar o alvo. Funciona com visibilidade em combate e Alt. Não afeta nomes de macros."
L["Fade_After_Combat"] = "Suavizar após o combate"
L["Fade_After_Combat_Desc"] = "Aparecimento/desaparecimento suave dos atalhos após o combate"
L["Fade_Time"] = "Tempo de transição"
L["Fade_Time_Desc"] = "Tempo da transição suave dos atalhos (em segundos)"
L["Macros"] = "Macros"
L["Hide_Macro_Names"] = "Ocultar nomes das macros"
L["Hide_Macro_Names_Desc"] = "Ocultar nomes das macros nos botões da barra de ações"
L["Hide Hotkeys"] = "Ocultar atalhos"
L["Show in Combat"] = "Mostrar em combate"
L["Show on Alt"] = "Mostrar com |cFFFFD700Alt|r"
L["Fade After Combat"] = "Suavizar após o combate"
L["Fade Time"] = "Tempo de transição"
L["Hide Macro Names"] = "Ocultar nomes das macros"
L["Color Indication Enabled"] = "Ativar indicação por cor"
L["Cooldown Color"] = "Cor da recarga"
L["Cooldown Alpha"] = "Alpha da recarga"
L["Mana Color"] = "Cor de mana"
L["Range Color"] = "Cor de alcance"
L["Unusable Color"] = "Cor inutilizável"
L["Show Panels on Alt"] = "Mostrar painéis com |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Ocultar grifos"
L["Hide Decorative Elements"] = "Ocultar elementos decorativos"
L["Hide Action Bar Backgrounds"] = "Ocultar fundos das barras de ações"
L["Hide Shapeshift Backgrounds"] = "Ocultar fundos da barra de formas"
L["Hide Pet Bar Backgrounds"] = "Ocultar fundos da barra do pet"
L["Hide Possess Bar Backgrounds"] = "Ocultar fundos da barra de possessão"
L["Hide Bonus Bar Textures"] = "Ocultar texturas da barra bônus"
L["Hide Keyring Button"] = "Ocultar botão do chaveiro"
L["Hide Page Buttons"] = "Ocultar botões de página"
L["Hide Max Level Bar"] = "Ocultar barra de nível máximo"
L["Hide Page Numbers"] = "Ocultar números de página"
L["Show Page Numbers in Combat"] = "Mostrar números de página em combate"
L["Show Page Numbers on Alt"] = "Mostrar números de página com |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Números de página suavizam após combate"
L["Page Numbers Fade Time"] = "Tempo de transição dos números de página"
L["Hide Exp Bar"] = "Ocultar barra de EXP"
L["Show Exp Bar on Alt"] = "Mostrar barra de EXP com |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Mostrar barra de EXP ao ganhar"
L["Exp Bar Fade Time"] = "Tempo de transição da barra de EXP"
L["Exp Bar Show Time"] = "Tempo de exibição da barra de EXP"
L["Hide Rep Bar"] = "Ocultar barra de reputação"
L["Show Rep Bar on Alt"] = "Mostrar barra de reputação com |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Gain"] = "Mostrar ao mudar a reputação"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Mostra temporariamente a barra de reputação ao ganhar ou perder reputação."
L["Reputation_Bar_Fade_Time"] = "Duração da transição da barra de reputação"
L["Reputation_Bar_Fade_Time_Desc"] = "Duração da animação de aparecer/desaparecer da barra de reputação."
L["Reputation_Bar_Show_Time"] = "Tempo de exibição da barra de reputação"
L["Reputation_Bar_Show_Time_Desc"] = "Por quanto tempo a barra de reputação permanece visível após uma mudança."
L["Button Border Alpha"] = "Alpha da borda dos botões"
L["Micro Menu Alpha"] = "Alpha do micromenu"
L["Button Border Alpha Enabled"] = "Ativar alpha da borda dos botões"
L["Micro Menu Alpha Enabled"] = "Ativar alpha do micromenu"
L["Minimap"] = "Minimapa"
L["Nameplates"] = "Nameplates"
L["Plates Auras"] = "Auras nos nameplates"
L["Health Indicators"] = "Indicadores de vida"
L["Health Indicators Desc"] = "Escolha o sistema de indicadores de vida / nameplates."
L["Health Indicator Type"] = "Tipo de indicador de vida"
L["Health Indicator Type Desc"] = "ElvUI usa nameplates embutidos do ElvUI. Classic WoW usa os nameplates padrão da Blizzard."
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "Editando configurações de exibição para: %s"
L["Health Indicators Reload Notice"] = "É necessário recarregar a interface para aplicar totalmente a alteração do tipo de indicador de vida."
L["Open ElvUI NamePlates Settings"] = "Configurações"
L["Open ElvUI NamePlates Settings Desc"] = "Abrir a janela de configuração do ElvUI NamePlates (/enp)."
L["Arena Frame Type"] = "Tipo de quadro de arena"
L["Arena Frame Type Desc"] = "GladiusEx usa os quadros de arena embutidos do GladiusEx. Classic WoW usa o módulo de arena padrão do SarychUI."
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "Abrir configurações do GladiusEx"
L["Open GladiusEx Settings Desc"] = "Abrir a janela de configuração do GladiusEx (/gex ui)."
L["Arena Classic Settings Disabled"] = "Estas configurações só estão disponíveis no modo Classic WoW."
L["Map"] = "Mapa-múndi"
L["World Map"] = "Mapa-múndi"
L["Map Module Desc"] = "Escolha qual addon de mapa usar."
L["Map Type"] = "Tipo de mapa"
L["Map Type Desc"] = "Escolha qual addon de mapa usar."
L["Classic WoW Map"] = "Mapa Classic WoW"
L["Open Mapster Settings"] = "Abrir configurações do Mapster"
L["Open Mapster Settings Desc"] = "Abrir a janela de configuração do Mapster (/mapster)."
L["Open Carbonite Settings"] = "Abrir configurações do Carbonite"
L["Open Carbonite Settings Desc"] = "Abrir a janela de configuração do Carbonite (/carb options)."
L["Map Type Reload"] = "É necessário recarregar a interface para aplicar a alteração do tipo de mapa."
L["Nameplate Distance"] = "Ativar exibição de distância"
L["Nameplate Distance Desc"] = "Requer nameplate_range.dll. Status: Sistema -> Visão geral."
L["Nameplate Distance Tab"] = "Distância do nameplate"
L["Nameplate Distance Font Desc"] = "Fonte do texto de distância nos nameplates."
L["Nameplate Distance Font Size Desc"] = "Tamanho da fonte do texto de distância."
L["Nameplate Distance Offset X Desc"] = "Deslocamento horizontal do texto de distância."
L["Nameplate Distance Offset Y Desc"] = "Deslocamento vertical do texto de distância."
L["Font Size"] = "Tamanho da fonte"
L["Position X"] = "Posição X"
L["Position Y"] = "Posição Y"
L["Font Outline"] = "Contorno da fonte"
L["Nameplate Distance Font Outline Desc"] = "Estilo de contorno do texto de distância (mesmas opções do ElvUI NamePlates)."
L["Shadow X"] = "Sombra X"
L["Shadow Y"] = "Sombra Y"
L["Nameplate Distance Shadow X Desc"] = "Deslocamento horizontal da sombra do texto de distância."
L["Nameplate Distance Shadow Y Desc"] = "Deslocamento vertical da sombra do texto de distância."
L["None"] = "Nenhum"
L["Reload UI"] = "Recarregar interface"
L["Reload UI Desc"] = "Execute /reload para aplicar as alterações."
L["Tools"] = "Outros"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "O módulo Confirmação automática confirma vários diálogos automaticamente."
L["Crowd Control module displays CC effects on your screen."] = "O módulo Controle de multidão exibe efeitos de CC na tela."
L["Chat module enhances the chat interface with additional features."] = "O módulo de bate-papo aprimora a interface do chat com recursos extras."
L["Error Filter module filters out annoying error messages."] = "O módulo Filtro de erros oculta mensagens de erro irritantes."
L["Frame module allows you to move and customize unit frames."] = "O módulo de quadros permite mover e personalizar unit frames."
L["Main Menu Bar module customizes the main action bar."] = "O módulo da barra principal personaliza a barra de ações principal."
L["Minimap module enhances and customizes the minimap."] = "O módulo do minimapa aprimora e personaliza o minimapa."
L["Plates Auras module displays auras on nameplates."] = "O módulo Auras nos nameplates exibe auras nos nameplates."
L["Tools module provides various utility functions."] = "O módulo Outros fornece várias funções utilitárias."

-- Module description keys for options
L["Frames_Description"] = "Configurações de modificação dos unit frames"
L["Auras_Description"] = "Ocultação de auras, destaque de dissipação e gerenciamento do quadro de buffs do jogador"
L["Minimap_Description"] = "Configurações do minimapa"
L["Chat_Description"] = "Configurações de bate-papo e mensagens"
L["Tools_Description"] = "Diversas ferramentas e utilitários"
L["MainMenuBar_Description"] = "Configurações da barra de comandos principal e das barras de ações"
L["CooldownText_Description"] = "Configurações de texto de recarga e temporizadores"
L["Automation_Description"] = "Automação de várias ações do jogo"

-- Auto Confirm
L["Confirm Loot"] = "Confirmar saque"
L["Automatically confirm loot rolls."] = "Confirmar automaticamente as rolagens de saque."
L["Confirm Bind"] = "Confirmar vínculo"
L["Automatically confirm binding items."] = "Confirmar automaticamente o vínculo de itens."
L["Confirm Delete"] = "Confirmar exclusão"
L["Automatically confirm item deletion."] = "Confirmar automaticamente a exclusão de itens."
L["Confirm Quest"] = "Confirmar missão"
L["Automatically confirm quest dialogs."] = "Confirmar automaticamente os diálogos de missão."

-- Crowd Control
L["Show Icon"] = "Mostrar ícone"
L["Show CC icon when you are affected by crowd control."] = "Mostrar ícone de CC quando você estiver sob controle de multidão."
L["Icon Size"] = "Tamanho do ícone"
L["Size of the CC icon."] = "Tamanho do ícone de CC."
L["Icon Position"] = "Posição do ícone"
L["Position of the CC icon on screen."] = "Posição do ícone de CC na tela."
L["Show Timer"] = "Mostrar temporizador"
L["Show remaining time on CC effects."] = "Mostrar o tempo restante dos efeitos de CC."

-- Chat
L["Chat Bar"] = "Barra de bate-papo"
L["Enable chat bar with quick channel buttons."] = "Ativar barra de bate-papo com botões rápidos de canal."
L["Position"] = "Posição"
L["Chat bar position."] = "Posição da barra de bate-papo."
L["Timestamps"] = "Carimbos de tempo"
L["Show timestamps in chat."] = "Mostrar carimbos de tempo no bate-papo."
L["Class Colors"] = "Cores de classe"
L["Color player names by class."] = "Colorir nomes dos jogadores pela classe."
L["Short Channel Names"] = "Nomes curtos de canal"
L["Use abbreviated channel names."] = "Usar nomes abreviados de canais."

-- Error Filter
L["Filters"] = "Filtros"
L["Configure which errors to filter."] = "Configurar quais erros filtrar."

-- Frame
L["Move Frames"] = "Mover quadros"
L["Allow moving unit frames."] = "Permitir mover unit frames."
L["Combat Indicator"] = "Indicador de combate"
L["Show combat indicator on frames."] = "Mostrar indicador de combate nos quadros."
L["Size"] = "Tamanho"
L["Frame Text"] = "Texto do quadro"
L["Show Name"] = "Mostrar nome"
L["Show Level"] = "Mostrar nível"
L["Show Class"] = "Mostrar classe"

-- Main Menu Bar
L["Hide Art"] = "Ocultar arte"
L["Hide background art from the main menu bar."] = "Ocultar a arte de fundo da barra principal."
L["Hide Gryphons"] = "Ocultar grifos"
L["Hide the gryphon decorations."] = "Ocultar as decorações dos grifos."
L["Show Buttons"] = "Mostrar botões"
L["Configure which buttons to show."] = "Configurar quais botões exibir."

-- Minimap
L["Shape"] = "Formato"
L["Minimap shape (square or round)."] = "Formato do minimapa (quadrado ou redondo)."
L["Square"] = "Quadrado"
L["Round"] = "Redondo"
L["Zoom"] = "Zoom"
L["Enable zoom buttons."] = "Ativar botões de zoom."

-- Plates Auras
L["Show Buffs"] = "Mostrar buffs"
L["Display buffs on nameplates."] = "Exibir buffs nos nameplates."
L["Show Debuffs"] = "Mostrar debuffs"
L["Display debuffs on nameplates."] = "Exibir debuffs nos nameplates."
L["Max Icons"] = "Máx. de ícones"
L["Maximum number of icons to display."] = "Número máximo de ícones a exibir."
L["Only Mine"] = "Apenas meus"
L["Only show auras cast by you."] = "Mostrar apenas auras lançadas por você."
L["Show Duration"] = "Mostrar duração"
L["Display remaining duration on auras."] = "Exibir a duração restante das auras."
L["Spell Settings"] = "Configurações de feitiço"
L["Visibility"] = "Visibilidade"
L["Show this spell on nameplates"] = "Mostrar este feitiço nos nameplates"
L["Spell Type"] = "Tipo de feitiço"
L["Type"] = "Tipo"
L["Spell Priority"] = "Prioridade do feitiço"
L["Custom Priority"] = "Prioridade personalizada"
L["Priority"] = "Prioridade"
L["Higher priority spells will take precedence regardless of duration"] = "Feitiços de maior prioridade têm precedência independentemente da duração"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC como OK"
L["Allow ESC key to confirm dialogs."] = "Permitir que a tecla ESC confirme diálogos."
L["No Combat Errors"] = "Sem erros em combate"
L["Hide errors during combat."] = "Ocultar erros durante o combate."
L["Speedy Load"] = "Carregamento rápido"
L["Faster addon loading."] = "Carregamento mais rápido de addons."

-- Positions
L["Top"] = "Topo"
L["Bottom"] = "Base"
L["Left"] = "Esquerda"
L["Right"] = "Direita"
L["Center"] = "Centro"
L["Top Left"] = "Superior esquerdo"
L["Top Right"] = "Superior direito"
L["Bottom Left"] = "Inferior esquerdo"
L["Bottom Right"] = "Inferior direito"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+Clique na aba – |cFFFFD700janela de cópia|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Ativar cópia do bate-papo com Ctrl+Clique na aba do chat"
L["Messages"] = "Mensagens: %d"
L["Drag_to_size"] = "Arraste para redimensionar | Clique direito para fechar"

-- Tooltip Settings
L["Tooltip_Settings"] = "Configurações da janela"
L["Enable_Tooltip_Position"] = "Alterar posição da janela"
L["Enable_Tooltip_Position_Desc"] = "Ativar posicionamento personalizado da janela de dica"
L["Tooltip_Base_Offset"] = "Deslocamento base"
L["Tooltip_Base_Offset_Desc"] = "Deslocamento base da janela de dica"
L["Tooltip_Pet_Offset"] = "Deslocamento do pet"
L["Tooltip_Pet_Offset_Desc"] = "Deslocamento adicional da janela de dica quando o pet está ativo"
L["Enable_Chat_Icons"] = "Mostrar ícones na janela de dica"
L["Enable_Chat_Icons_Desc"] = "Mostrar ícones de itens, feitiços e conquistas nas mensagens do bate-papo"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "Ocultar botão de amigos"
L["Enable_Friends_Button_Mod_Desc"] = "Ocultar o botão de amigos no bate-papo"
L["Enable_Hide_Chat_Frame_Button"] = "Ocultar botão de comunicação"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Ocultar botão de comunicação"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Ocultar o botão de comunicação no bate-papo"
L["Enable_Hide_Chat_Scroll_Buttons"] = "Ocultar setas para cima e para baixo"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Ocultar as setas de rolagem para cima e para baixo no bate-papo"
L["Enable_Hide_Chat_Bottom_Button"] = "Ocultar seta ir para o final"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Ocultar a seta de ir para o final no bate-papo"

-- Chat Animations
L["Chat_Animations"] = "Animações do bate-papo"
L["Enable_Chat_Animations"] = "Ativar animações do bate-papo"
L["Enable_Chat_Animations_Desc"] = "Ativar animações personalizadas do bate-papo"
L["Chat_Tab_Show_Delay"] = "Atraso para mostrar abas (seg)"
L["Chat_Tab_Show_Delay_Desc"] = "Atraso antes de mostrar as abas do bate-papo"
L["Chat_Tab_Hide_Delay"] = "Atraso para ocultar abas (seg)"
L["Chat_Tab_Hide_Delay_Desc"] = "Atraso antes de ocultar as abas do bate-papo"
L["Chat_Frame_Fade_Time"] = "Duração do aparecer (seg)"
L["Chat_Frame_Fade_Time_Desc"] = "Duração da animação de aparição do bate-papo"
L["Chat_Frame_Fade_Out_Time"] = "Duração do desaparecer (seg)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Duração da animação de desaparecimento do bate-papo"

-- Messages
L["Profile reset to defaults."] = "Perfil redefinido para o padrão."
L["Module enabled."] = "Módulo ativado."
L["Module disabled."] = "Módulo desativado."

SarychUI.RegisterLocale("ptBR", L)
