-- SarychUI Russian Localization (ruRU)

local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "Общее"
L["Enable"] = "Включить"
L["Disable"] = "Отключить"
L["Enabled"] = "Включено"
L["Settings"] = "Настройки"
L["Options"] = "Опции"
L["Reset"] = "Сбросить"
L["Default"] = "По умолчанию"

-- System / wow_optimize compatibility
L["System"] = "Система"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "Необязательный режим совместимости с wow_optimize.dll. При активном режиме SarychUI не дублирует GC/combat log fix и смягчает тяжёлые Lua-сканы nameplates и chat bubbles."
L["WowOptimize_Mode"] = "Режим совместимости"
L["WowOptimize_Mode_Desc"] = "Авто — обнаружение по глобалам DLL (LUABOOST_DLL_*). Включено — принудительно. Выключено — обычный SarychUI."
L["WowOptimize_Mode_Auto"] = "Авто"
L["WowOptimize_Mode_Enabled"] = "Включено"
L["WowOptimize_Mode_Disabled"] = "Выключено"
L["WowOptimize_Debug"] = "Отладочный лог совместимости"
L["WowOptimize_Debug_Desc"] = "Писать в чат, какие адаптации применены (или установите DEBUG_WOW_OPTIMIZE_COMPAT = true)."
L["System_Overview"] = "Обзор"
L["Dll_Detection_Header"] = "Обнаружение DLL"
L["Dll_Status_Detected"] = "Обнаружен"
L["Dll_Status_NotDetected"] = "Не обнаружен"
L["Dll_Status_Checking"] = "Проверка..."
L["Dll_Status_NoMarker"] = "Нет Lua-маркера"
L["Dll_Status_ApiDetected"] = "API обнаружен"
L["Dll_Status_WaitingNameplates"] = "Ожидает неймплейты"
L["Runtime_LuaOptimize"] = "Оптимизация Lua"
L["Runtime_EnableGC"] = "Включить управление сборкой мусора"
L["Runtime_EnableGC_Desc"] = "Инкрементальная сборка мусора по режимам (обычный / бой / простой / загрузка). При активной wow_optimize.dll управление передаётся DLL."
L["Runtime_Preset"] = "Профиль GC"
L["Runtime_Preset_Light"] = "Лёгкий"
L["Runtime_Preset_Standard"] = "Стандартный"
L["Runtime_Preset_Heavy"] = "Тяжёлый"
L["Runtime_Preset_Custom"] = "Пользовательский"
L["Runtime_StepNormal"] = "GC step (обычный), KB"
L["Runtime_StepCombat"] = "GC step (бой), KB"
L["Runtime_StepIdle"] = "GC step (простой), KB"
L["Runtime_StepLoading"] = "GC step (загрузка), KB"
L["Runtime_EmergencyMB"] = "Порог аварийной полной очистки, MB"
L["Runtime_IdleTimeout"] = "Время до idle-режима, сек"
L["Runtime_SpeedyLoad"] = "Оптимизация экрана загрузки"
L["Runtime_SpeedyLoadMode"] = "Режим загрузки"
L["Runtime_SpeedyLoadSafe"] = "Безопасный"
L["Runtime_SpeedyLoadAggressive"] = "Агрессивный"
L["Runtime_Debug"] = "Диагностический вывод"
L["Runtime_DllStatus"] = "Статус wow_optimize.dll"
L["Runtime_DllOwnsGC"] = "Управление GC передано wow_optimize.dll — Lua-шаги отключены."
L["Runtime_ForceGC"] = "Полная очистка сейчас (вне боя)"
L["Runtime_ForceGC_Desc"] = "Запускает полную сборку мусора вне боя. В бою недоступно."
L["Runtime_BlockedByLuaBoost"] = "Обнаружен аддон !LuaBoost. Управление GC в SarychUI отключено, чтобы избежать конфликта. Отключите или удалите !LuaBoost, чтобы пользоваться этой опцией."
L["Runtime_NotLoaded"] = "Модуль Runtime не загружен"
L["Runtime_Controller"] = "Контроллер GC"
L["Runtime_Mode"] = "Режим"
L["Runtime_Memory"] = "Память Lua"
L["Runtime_Settings"] = "Режим работы"
L["Runtime_Preset_Desc"] = "Готовый баланс плавности кадров и скорости очистки памяти."
L["Runtime_UICache"] = "Кэш повторных обновлений StatusBar"
L["Runtime_UICache_Desc"] = "Не отправляет движку одинаковые значения полос здоровья, ресурсов и прогресса повторно."
L["Runtime_UICacheDLL"] = "обрабатывается DLL"
L["Runtime_UICacheActive"] = "активен, пропущено %d повторов"
L["Runtime_UICacheDisabled"] = "отключён"
L["Runtime_UICacheWaiting"] = "ожидает активации"
L["Runtime_AutomaticNote"] = "Шаги для боя, простоя и загрузки выбираются профилем автоматически. Аварийный порог сам повышается, если полная очистка заняла слишком много времени."


-- Modules
L["Modules"] = "Модули"
L["Auto Confirm"] = "Авто подтверждение"
L["Crowd Control"] = "Контроль"
L["Cooldown Text"] = "Перезарядка и таймеры"
L["Font_Path"] = "Путь к шрифту"
L["Font_Path_Desc"] = "Полный путь к .ttf (пример: Fonts\\FRIZQT__.TTF)"
L["Font_Flags"] = "Стиль шрифта"
L["Font_Flags_Desc"] = "Варианты: NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "Размер текста (< 60 сек)"
L["Font_Size_Small_Desc"] = "Размер текста для оставшегося времени менее 60 секунд"
L["Font_Size_Medium"] = "Размер текста (1–10 мин)"
L["Font_Size_Medium_Desc"] = "Размер текста для 1:00–9:59 и ≥10 минут"
L["Font_Size_Large"] = "Размер текста (>10 мин)"
L["Font_Size_Large_Desc"] = "Размер текста для значений в минутах ≥ 10"
L["Default_Color"] = "Цвет текста по умолчанию"
L["Appearance"] = "Внешний вид"
L["Display_Conditions"] = "Условия отображения"
L["Behavior"] = "Поведение"
L["Min_Scale"] = "Минимальный масштаб"
L["Min_Scale_Desc"] = "Не показывать текст, если итоговый масштаб иконки меньше"
L["Min_Icon_Size"] = "Минимальный размер иконки"
L["Min_Icon_Size_Desc"] = "Не показывать текст, если ширина/высота иконки меньше"
L["Hide_On_GCD"] = "Не отображать при ГКД"
L["Hide_On_GCD_Desc"] = "Скрывать текст кулдауна на способностях с глобальным временем восстановления (ГКД ~1.5 сек)"
L["Chat"] = "Окно чата"
L["Error Filter"] = "Фильтр ошибок"
L["Frame"] = "Фреймы"
L["Frames"] = "Фреймы"
L["Auras"] = "Ауры"
L["Frame Auras"] = "Ауры фреймов"
L["Character Auras"] = "Ауры персонажа"
L["MainMenuBar"] = "Панель действий"
L["MainMenuBar_Description"] = "Настройка панели действий с управлением горячими клавишами и названиями макросов."
L["Enable_Module"] = "Включить модуль"
L["Enable_Module_Desc"] = "Включить или отключить модуль панели действий полностью."
L["Hotkeys"] = "Горячие клавиши"
L["Color Indication"] = "Цветовая индикация"
L["Color_Indication_Enabled"] = "Включить цветовую индикацию"
L["Color_Indication_Enabled_Desc"] = "Включить или отключить цветовую индикацию кнопок панели действий"
L["Color_Cooldown_Enabled"] = "Обесцвеченный при кулдауне"
L["Color_Cooldown_Enabled_Desc"] = "Делать кнопки серыми при кулдауне больше 1.5 секунд"
L["Color_Cooldown_Alpha"] = "Прозрачность при кулдауне"
L["Color_Cooldown_Alpha_Desc"] = "Прозрачность кнопок при кулдауне (0 - невидимый, 1 - дефолт)"
L["Color_Mana_Enabled"] = "Синий цвет при недостатке ресурса"
L["Color_Mana_Enabled_Desc"] = "Делать кнопки синими при недостатке маны, энергии или ярости"
L["Color_Range_Enabled"] = "Красный цвет вне радиуса"
L["Color_Range_Enabled_Desc"] = "Делать кнопки красными когда цель вне радиуса действия"
L["Color_Unusable_Enabled"] = "Темно-серый цвет при недоступности"
L["Color_Unusable_Enabled_Desc"] = "Делать кнопки темно-серыми когда способность недоступна"
L["Interface"] = "Интерфейс"
L["Visual"] = "Текст"
L["Hide_Hotkeys"] = "Скрыть горячие клавиши"
L["Hide_Hotkeys_Desc"] = "Скрыть горячие клавиши на кнопках панели действий"
L["Show_In_Combat"] = "Показывать во время боя"
L["Show_In_Combat_Desc"] = "Показывать горячие клавиши во время боя, даже если они скрыты"
L["Show_On_Alt"] = "Показывать при нажатии |cFFFFD700Alt|r"
L["Show_On_Alt_Desc"] = "Показывать горячие клавиши при зажатой клавише |cFFFFD700Alt|r"
L["Show_With_Target"] = "Показывать при выбранной цели"
L["Show_With_Target_Desc"] = "Показывать горячие клавиши (при скрытии по настройке), пока выбрана цель; при снятии цели снова скрываются. Работает вместе с показом в бою и при Alt. На названия макросов не влияет."
L["Fade_After_Combat"] = "Плавное появление/исчезновение"
L["Fade_After_Combat_Desc"] = "Плавное появление горячих клавиш при входе в бой и плавное скрытие при выходе"
L["Fade_Time"] = "Время появления"
L["Fade_Time_Desc"] = "Время плавного появления/исчезновения горячих клавиш (в секундах)"
L["Macros"] = "Макросы"
L["Hide_Macro_Names"] = "Скрыть название макросов"
L["Hide_Macro_Names_Desc"] = "Скрыть названия макросов на кнопках панели действий"

-- Appearance settings
L["Appearance"] = "Внешний вид"
L["Hide_Gryphons"] = "Скрыть грифонов"
L["Hide_Gryphons_Desc"] = "Скрыть грифонов по бокам панели действий"
L["Hide_ActionBar_Backgrounds"] = "Скрыть фоновые текстуры панелей действий"
L["Hide_ActionBar_Backgrounds_Desc"] = "Скрыть фоновые текстуры основных панелей действий"
L["Hide_Secondary_Panels_Backgrounds"] = "Скрыть фоновые текстуры панелей: форм, питомца, обладания"
L["Hide_Secondary_Panels_Backgrounds_Desc"] = "Скрыть фоновые текстуры панелей смены форм, питомца и обладания"
L["Hide_MaxLevel_Bar"] = "Скрыть полосу максимального уровня"
L["Hide_MaxLevel_Bar_Desc"] = "Скрыть полосу максимального уровня"
L["Hide_Keyring_Button"] = "Скрыть кнопку связки ключей"
L["Hide_Keyring_Button_Desc"] = "Скрыть кнопку связки ключей"
L["Hide_Page_Buttons"] = "Скрыть кнопки переключения страниц"
L["Hide_Page_Buttons_Desc"] = "Скрыть кнопки переключения страниц (стрелки вверх/вниз)"
L["Hide_Page_Numbers"] = "Скрыть номера страниц по умолчанию"
L["Hide_Page_Numbers_Desc"] = "Скрыть номера страниц по умолчанию"
L["Show_Page_Numbers_In_Combat"] = "Показывать во время боя"
L["Show_Page_Numbers_In_Combat_Desc"] = "Показывать номера страниц во время боя"
L["Show_Page_Numbers_On_Alt"] = "Показывать при нажатии |cFFFFD700Alt|r"
L["Show_Page_Numbers_On_Alt_Desc"] = "Показывать номера страниц при зажатой клавише |cFFFFD700Alt|r"
L["Page_Numbers_Fade_After_Combat"] = "Плавное появление/исчезновение"
L["Page_Numbers_Fade_After_Combat_Desc"] = "Плавное появление номеров страниц при входе в бой и плавное скрытие при выходе"
L["Page_Numbers_Fade_Time"] = "Время появления"
L["Page_Numbers_Fade_Time_Desc"] = "Время плавного появления/исчезновения номеров страниц (в секундах)"

-- Additional appearance settings
L["Button_Border_Alpha"] = "Прозрачность обводки кнопок"
L["Button_Border_Alpha_Desc"] = "Прозрачность обводки кнопок панели действий"
L["MicroMenu_Alpha"] = "Прозрачность кнопок микроменю"
L["MicroMenu_Alpha_Desc"] = "Прозрачность кнопок микроменю (кнопки персонажа, талантов и т.д.)"
L["Hide_Reputation_Bar"] = "Скрыть полосу репутации"
L["Hide_Reputation_Bar_Desc"] = "Скрыть полосу репутации по умолчанию"
L["Show_Reputation_Bar_On_Alt"] = "Показывать при нажатии |cFFFFD700Alt|r"
L["Show_Reputation_Bar_On_Alt_Desc"] = "Показывать полосу репутации при зажатой клавише |cFFFFD700Alt|r (если отслеживается)"
L["Show_Reputation_Bar_On_Gain"] = "Показывать при изменении репутации"
L["Show_Reputation_Bar_On_Gain_Desc"] = "Временно показывает полосу репутации при получении или потере репутации."
L["Reputation_Bar_Fade_Time"] = "Плавность появления/исчезновения полосы репутации"
L["Reputation_Bar_Fade_Time_Desc"] = "Длительность анимации появления и исчезновения полосы репутации."
L["Reputation_Bar_Show_Time"] = "Время отображения полосы репутации"
L["Reputation_Bar_Show_Time_Desc"] = "Сколько секунд полоса репутации остается видимой после изменения репутации."
L["Hide_Experience_Bar"] = "Скрыть полосу опыта"
L["Hide_Experience_Bar_Desc"] = "Скрыть полосу опыта по умолчанию"
L["Show_Experience_Bar_On_Alt"] = "Показывать при нажатии |cFFFFD700Alt|r"
L["Show_Experience_Bar_On_Alt_Desc"] = "Показывать полосу опыта при зажатой клавише |cFFFFD700Alt|r"
L["Show_Experience_Bar_On_Gain"] = "Показывать при получении опыта"
L["Show_Experience_Bar_On_Gain_Desc"] = "Показывать полосу опыта при получении опыта"
L["Experience_Bar_Fade_Time"] = "Плавное появление/исчезновение"
L["Experience_Bar_Fade_Time_Desc"] = "Время плавного появления/исчезновения полосы опыта (в секундах)"
L["Experience_Bar_Show_Time"] = "Время отображения"
L["Experience_Bar_Show_Time_Desc"] = "Время отображения полосы опыта после получения опыта (в секундах)"

-- Side panels settings
L["Hide_Side_Panels"] = "Скрывать боковые панели"
L["Hide_Side_Panels_Desc"] = "Скрывать боковые панели и отображать при наведении курсора"
L["Show_Side_Panels_On_Alt"] = "Показывать при нажатии |cFFFFD700Alt|r"
L["Show_Side_Panels_On_Alt_Desc"] = "Показывать боковые панели при зажатой клавише |cFFFFD700Alt|r"

L["Hide Hotkeys"] = "Скрыть горячие клавиши"
L["Show in Combat"] = "Показывать в бою"
L["Show on Alt"] = "Показывать при |cFFFFD700Alt|r"
L["Fade After Combat"] = "Исчезать после боя"
L["Fade Time"] = "Время исчезновения"
L["Hide Macro Names"] = "Скрыть названия макросов"
L["Color Indication Enabled"] = "Включить цветовую индикацию"
L["Cooldown Color"] = "Цвет кулдауна"
L["Cooldown Alpha"] = "Прозрачность кулдауна"
L["Mana Color"] = "Цвет маны"
L["Range Color"] = "Цвет дистанции"
L["Unusable Color"] = "Цвет недоступности"
L["Show Panels on Alt"] = "Показывать панели при |cFFFFD700Alt|r"
L["Hide Gryphons"] = "Скрыть грифонов"
L["Hide Decorative Elements"] = "Скрыть декоративные элементы"
L["Hide Action Bar Backgrounds"] = "Скрыть фоновые текстуры панелей действий"
L["Hide Shapeshift Backgrounds"] = "Скрыть фоновые текстуры панели форм"
L["Hide Pet Bar Backgrounds"] = "Скрыть фоновые текстуры панели питомца"
L["Hide Possess Bar Backgrounds"] = "Скрыть фоновые текстуры панели обладания"
L["Hide Bonus Bar Textures"] = "Скрыть текстуры бонусной панели действий"
L["Hide Keyring Button"] = "Скрыть кнопку связки ключей"
L["Hide Page Buttons"] = "Скрыть кнопки переключения страниц"
L["Hide Max Level Bar"] = "Скрыть полосу максимального уровня"
L["Hide Page Numbers"] = "Скрыть номера страниц"
L["Show Page Numbers in Combat"] = "Показывать номера страниц в бою"
L["Show Page Numbers on Alt"] = "Показывать номера страниц при |cFFFFD700Alt|r"
L["Page Numbers Fade After Combat"] = "Плавное исчезновение номеров страниц после боя"
L["Page Numbers Fade Time"] = "Время исчезновения номеров страниц"
L["Hide Exp Bar"] = "Скрыть полосу опыта"
L["Show Exp Bar on Alt"] = "Показывать полосу опыта при |cFFFFD700Alt|r"
L["Show Exp Bar on Gain"] = "Показывать полосу опыта при получении"
L["Exp Bar Fade Time"] = "Время исчезновения полосы опыта"
L["Exp Bar Show Time"] = "Время отображения полосы опыта"
L["Hide Rep Bar"] = "Скрыть полосу репутации"
L["Show Rep Bar on Alt"] = "Показывать полосу репутации при |cFFFFD700Alt|r"
L["Button Border Alpha"] = "Прозрачность обводки кнопок"
L["Micro Menu Alpha"] = "Прозрачность кнопок микроменю"
L["Button Border Alpha Enabled"] = "Включить прозрачность обводки кнопок"
L["Micro Menu Alpha Enabled"] = "Включить прозрачность кнопок микроменю"
L["Minimap"] = "Миникарта"
L["Nameplates"] = "Неймплейты"
L["Plates Auras"] = "Ауры на индикаторах здоровья"
L["Health Indicators"] = "Индикаторы здоровья"
L["Health Indicators Desc"] = "Выбор системы индикаторов здоровья / nameplates."
L["Health Indicator Type"] = "Тип индикаторов здоровья"
L["Health Indicator Type Desc"] = "ElvUI — встроенные nameplates ElvUI. Классические WoW — стандартные индикаторы Blizzard."
L["Classic WoW Nameplates"] = "Классические WoW"
L["ElvUI Nameplates"] = "ElvUI индикаторы"
L["Plates Auras Profile Edit"] = "Сейчас редактируются параметры для режима: %s"
L["Health Indicators Reload Notice"] = "Для полного применения изменения типа индикаторов здоровья необходимо перезагрузить интерфейс."
L["Open ElvUI NamePlates Settings"] = "Настройки"
L["Open ElvUI NamePlates Settings Desc"] = "Открыть окно настроек ElvUI NamePlates (/enp)."
L["Arena Frame Type"] = "Тип фреймов арены"
L["Arena Frame Type Desc"] = "GladiusEx — встроенные фреймы GladiusEx. Классические WoW — стандартный модуль арены SarychUI."
L["Classic WoW Arena Frames"] = "Классические WoW"
L["Open GladiusEx Settings"] = "Открыть настройки GladiusEx"
L["Open GladiusEx Settings Desc"] = "Открыть окно настроек GladiusEx (/gex ui)."
L["Arena Classic Settings Disabled"] = "Эти настройки доступны только для режима Классические WoW."
L["Map"] = "Карта мира"
L["World Map"] = "Карта мира"
L["Map Module Desc"] = "Выбор типа карты."
L["Map Type"] = "Тип карты"
L["Map Type Desc"] = "Выберите, какой аддон карты использовать."
L["Classic WoW Map"] = "Классическая карта WoW"
L["Open Mapster Settings"] = "Открыть настройки Mapster"
L["Open Mapster Settings Desc"] = "Открыть окно настроек Mapster (/mapster)."
L["Open Carbonite Settings"] = "Открыть настройки Carbonite"
L["Open Carbonite Settings Desc"] = "Открыть окно настроек Carbonite (/carb options)."
L["Map Type Reload"] = "При смене типа карты требуется перезагрузка интерфейса."
L["Nameplate Distance"] = "Включить отображение дистанции"
L["Nameplate Distance Desc"] = "Работает только при наличии nameplate_range.dll. Статус: Система -> Обзор."
L["Nameplate Distance Tab"] = "Дистанция до неймплейта"
L["Nameplate Distance Font Desc"] = "Шрифт текста дистанции на неймплейте."
L["Nameplate Distance Font Size Desc"] = "Размер текста дистанции."
L["Nameplate Distance Offset X Desc"] = "Горизонтальное смещение текста дистанции."
L["Nameplate Distance Offset Y Desc"] = "Вертикальное смещение текста дистанции."
L["Font Size"] = "Размер шрифта"
L["Position X"] = "Позиция X"
L["Position Y"] = "Позиция Y"
L["Font Outline"] = "Граница шрифта"
L["Nameplate Distance Font Outline Desc"] = "Стиль контура текста дистанции (как в ElvUI NamePlates)."
L["Shadow X"] = "Тень X"
L["Shadow Y"] = "Тень Y"
L["Nameplate Distance Shadow X Desc"] = "Горизонтальное смещение тени текста."
L["Nameplate Distance Shadow Y Desc"] = "Вертикальное смещение тени текста."
L["None"] = "Без границы"
L["Reload UI"] = "Перезагрузить интерфейс"
L["Reload UI Desc"] = "Выполнить /reload для применения изменений."
L["Tools"] = "Инструменты и утилиты"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "Модуль автоматически подтверждает различные диалоги."
L["Crowd Control module displays CC effects on your screen."] = "Модуль отображает эффекты контроля на экране."
L["Chat module enhances the chat interface with additional features."] = "Модуль улучшает интерфейс чата дополнительными функциями."
L["Error Filter module filters out annoying error messages."] = "Модуль фильтрует надоедливые сообщения об ошибках."
L["Frame module allows you to move and customize unit frames."] = "Модуль позволяет перемещать и настраивать фреймы юнитов."
L["Main Menu Bar module customizes the main action bar."] = "Модуль настраивает главную панель действий."
L["Minimap module enhances and customizes the minimap."] = "Модуль улучшает и настраивает миникарту."
L["Plates Auras module displays auras on nameplates."] = "Модуль отображает ауры на индикаторах здоровья."
L["Tools module provides various utility functions."] = "Модуль предоставляет различные полезные функции."

-- Module description keys for options
L["Frames_Description"] = "Настройки модификаций фреймов"
L["Auras_Description"] = "Скрытие аур, подсветка развеивания и управление баффами персонажа"
L["Minimap_Description"] = "Настройка миникарты"
L["Chat_Description"] = "Настройка чата и сообщений"
L["Tools_Description"] = "Различные инструменты и утилиты"
L["MainMenuBar_Description"] = "Настройка главной панели команд и панелей действий"
L["CooldownText_Description"] = "Настройка отображения текста перезарядки и таймеров"
L["Automation_Description"] = "Автоматизация различных игровых действий"

-- Auto Confirm
L["Confirm Loot"] = "Подтверждать лут"
L["Automatically confirm loot rolls."] = "Автоматически подтверждать броски на предметы."
L["Confirm Bind"] = "Подтверждать привязку"
L["Automatically confirm binding items."] = "Автоматически подтверждать привязку предметов."
L["Confirm Delete"] = "Подтверждать удаление"
L["Automatically confirm item deletion."] = "Автоматически подтверждать удаление предметов."
L["Confirm Quest"] = "Подтверждать квесты"
L["Automatically confirm quest dialogs."] = "Автоматически подтверждать диалоги квестов."

-- Crowd Control
L["Show Icon"] = "Показывать иконку"
L["Show CC icon when you are affected by crowd control."] = "Показывать иконку при воздействии эффектов контроля."
L["Icon Size"] = "Размер иконки"
L["Size of the CC icon."] = "Размер иконки контроля."
L["Icon Position"] = "Позиция иконки"
L["Position of the CC icon on screen."] = "Позиция иконки контроля на экране."
L["Show Timer"] = "Показывать таймер"
L["Show remaining time on CC effects."] = "Показывать оставшееся время эффектов контроля."

-- Chat
L["Chat Bar"] = "Панель чата"
L["Enable chat bar with quick channel buttons."] = "Включить панель чата с быстрыми кнопками каналов."
L["Position"] = "Позиция"
L["Chat bar position."] = "Позиция панели чата."
L["Timestamps"] = "Временные метки"
L["Show timestamps in chat."] = "Показывать временные метки в чате."
L["Class Colors"] = "Цвета классов"
L["Color player names by class."] = "Окрашивать имена игроков по классу."
L["Short Channel Names"] = "Короткие названия каналов"
L["Use abbreviated channel names."] = "Использовать сокращённые названия каналов."

-- Error Filter
L["Filters"] = "Фильтры"
L["Configure which errors to filter."] = "Настроить какие ошибки фильтровать."

-- Frame
L["Move Frames"] = "Перемещать фреймы"
L["Allow moving unit frames."] = "Разрешить перемещение фреймов юнитов."
L["Combat Indicator"] = "Индикатор боя"
L["Show combat indicator on frames."] = "Показывать индикатор боя на фреймах."
L["Size"] = "Размер"
L["Frame Text"] = "Текст фрейма"
L["Show Name"] = "Показывать имя"
L["Show Level"] = "Показывать уровень"
L["Show Class"] = "Показывать класс"

-- Main Menu Bar
L["Hide Art"] = "Скрыть оформление"
L["Hide background art from the main menu bar."] = "Скрыть фоновое оформление главного меню."
L["Hide Gryphons"] = "Скрыть грифонов"
L["Hide the gryphon decorations."] = "Скрыть украшения с грифонами."
L["Show Buttons"] = "Показывать кнопки"
L["Configure which buttons to show."] = "Настроить какие кнопки показывать."

-- Minimap
L["Shape"] = "Форма"
L["Minimap shape (square or round)."] = "Форма миникарты (квадрат или круг)."
L["Square"] = "Квадрат"
L["Round"] = "Круг"
L["Zoom"] = "Зум"
L["Enable zoom buttons."] = "Включить кнопки зума."

-- Plates Auras
L["Show Buffs"] = "Показывать баффы"
L["Display buffs on nameplates."] = "Отображать баффы на неймплейтах."
L["Show Debuffs"] = "Показывать дебаффы"
L["Display debuffs on nameplates."] = "Отображать дебаффы на неймплейтах."
L["Max Icons"] = "Макс. иконок"
L["Maximum number of icons to display."] = "Максимальное количество иконок для отображения."
L["Only Mine"] = "Только мои"
L["Only show auras cast by you."] = "Показывать только ауры наложенные вами."
L["Show Duration"] = "Показывать длительность"
L["Display remaining duration on auras."] = "Отображать оставшуюся длительность аур."
L["Spell Settings"] = "Настройки заклинаний"
L["Visibility"] = "Видимость"
L["Show this spell on nameplates"] = "Показывать это заклинание на неймплейтах"
L["Spell Type"] = "Тип заклинания"
L["Type"] = "Тип"
L["Spell Priority"] = "Приоритет заклинания"
L["Custom Priority"] = "Пользовательский приоритет"
L["Priority"] = "Приоритет"
L["Higher priority spells will take precedence regardless of duration"] = "Заклинания с более высоким приоритетом будут иметь приоритет независимо от длительности"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC как OK"
L["Allow ESC key to confirm dialogs."] = "Разрешить клавише ESC подтверждать диалоги."
L["No Combat Errors"] = "Без ошибок в бою"
L["Hide errors during combat."] = "Скрывать ошибки во время боя."
L["Speedy Load"] = "Быстрая загрузка"
L["Faster addon loading."] = "Более быстрая загрузка аддона."

-- Positions
L["Top"] = "Верх"
L["Bottom"] = "Низ"
L["Left"] = "Лево"
L["Right"] = "Право"
L["Center"] = "Центр"
L["Top Left"] = "Верх слева"
L["Top Right"] = "Верх справа"
L["Bottom Left"] = "Низ слева"
L["Bottom Right"] = "Низ справа"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+ЛКМ по вкладке – |cFFFFD700окно копирования|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "Включить копирование чата по Ctrl+ЛКМ по вкладке чата"
L["Messages"] = "Сообщения: %d"
L["Drag_to_size"] = "Перетащите для изменения размера | ПКМ для закрытия"

-- Tooltip Settings
L["Tooltip_Settings"] = "Настройки окна"
L["Enable_Tooltip_Position"] = "Изменить позицию окна"
L["Enable_Tooltip_Position_Desc"] = "Включить кастомную позицию окна подсказок"
L["Tooltip_Base_Offset"] = "Базовое смещение"
L["Tooltip_Base_Offset_Desc"] = "Базовое смещение окна подсказок"
L["Tooltip_Pet_Offset"] = "Смещение для питомца"
L["Tooltip_Pet_Offset_Desc"] = "Дополнительное смещение окна подсказок для питомца"
L["Enable_Chat_Icons"] = "Показывать иконки в окне подсказок"
L["Enable_Chat_Icons_Desc"] = "Показывать иконки предметов, заклинаний и достижений в сообщениях чата"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "|TInterface\\CHATFRAME\\UI-ChatIcon-BattleBro-Up:15.3:15.3:0:0|t Скрыть кнопку друзей"
L["Enable_Friends_Button_Mod_Desc"] = "Скрыть кнопку друзей в чате"
L["Enable_Hide_Chat_Frame_Button"] = "|TInterface\\CHATFRAME\\UI-ChatIcon-Chat-Up:15.3:15.3:0:0|t Скрыть кнопку общения"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "Скрыть кнопку общения"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "Скрыть кнопку общения в чате"
L["Enable_Hide_Chat_Scroll_Buttons"] = "|TInterface\\CHATFRAME\\UI-ChatIcon-ScrollUp-Up:18:18:0:0|t Скрыть стрелки вверх и вниз"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "Скрыть стрелки прокрутки вверх и вниз в чате"
L["Enable_Hide_Chat_Bottom_Button"] = "|TInterface\\CHATFRAME\\UI-ChatIcon-ScrollEnd-Up:18:18:0:0|t Скрыть стрелку перемещения в конец"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "Скрыть стрелку перемещения в конец чата"

-- Chat Animations
L["Chat_Animations"] = "Анимации чата"
L["Enable_Chat_Animations"] = "Включить анимации чата"
L["Enable_Chat_Animations_Desc"] = "Включить кастомные анимации чата"
L["Chat_Tab_Show_Delay"] = "Задержка показа вкладок (сек)"
L["Chat_Tab_Show_Delay_Desc"] = "Задержка перед показом вкладок чата"
L["Chat_Tab_Hide_Delay"] = "Задержка скрытия вкладок (сек)"
L["Chat_Tab_Hide_Delay_Desc"] = "Задержка перед скрытием вкладок чата"
L["Chat_Frame_Fade_Time"] = "Длительность анимации появления чата (сек)"
L["Chat_Frame_Fade_Time_Desc"] = "Длительность анимации появления чата"
L["Chat_Frame_Fade_Out_Time"] = "Длительность анимации исчезновения чата (сек)"
L["Chat_Frame_Fade_Out_Time_Desc"] = "Длительность анимации исчезновения чата"

-- Messages
L["Profile reset to defaults."] = "Профиль сброшен на настройки по умолчанию."
L["Module enabled."] = "Модуль включён."
L["Module disabled."] = "Модуль отключён."

SarychUI.RegisterLocale("ruRU", L)

