-- SarychUI zhCN Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "常规"
L["Enable"] = "启用"
L["Disable"] = "禁用"
L["Enabled"] = "已启用"
L["Settings"] = "设置"
L["Options"] = "选项"
L["Reset"] = "重置"
L["Default"] = "默认"

-- System / wow_optimize compatibility
L["System"] = "系统"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "可选的 wow_optimize.dll 兼容模式。启用后，SarychUI 不会重复 GC/战斗日志修复，并会降低姓名板与聊天泡泡的重度扫描。"
L["WowOptimize_Mode"] = "兼容模式"
L["WowOptimize_Mode_Desc"] = "自动 — 通过 DLL 全局变量检测（LUABOOST_DLL_*）。启用 — 强制开启。禁用 — 普通 SarychUI。"
L["WowOptimize_Mode_Auto"] = "自动"
L["WowOptimize_Mode_Enabled"] = "启用"
L["WowOptimize_Mode_Disabled"] = "禁用"
L["WowOptimize_Debug"] = "兼容调试日志"
L["WowOptimize_Debug_Desc"] = "在聊天中输出已应用的适配（或设置 DEBUG_WOW_OPTIMIZE_COMPAT = true）。"
L["System_Overview"] = "概览"
L["Dll_Detection_Header"] = "DLL 检测"
L["Dll_Status_Detected"] = "已检测到"
L["Dll_Status_NotDetected"] = "未检测到"
L["Dll_Status_Checking"] = "检查中..."
L["Dll_Status_NoMarker"] = "无 Lua 标记"
L["Dll_Status_ApiDetected"] = "已检测到 API"
L["Dll_Status_WaitingNameplates"] = "等待姓名板"
L["Runtime_LuaOptimize"] = "Lua 优化"
L["Runtime_EnableGC"] = "启用垃圾回收管理器"
L["Runtime_EnableGC_Desc"] = "按模式递增 GC（普通 / 战斗 / 空闲 / 加载）。启用 wow_optimize.dll 时，GC 由 DLL 接管。"
L["Runtime_Preset"] = "GC 配置"
L["Runtime_Preset_Light"] = "轻量"
L["Runtime_Preset_Standard"] = "标准"
L["Runtime_Preset_Heavy"] = "重度"
L["Runtime_Preset_Custom"] = "自定义"
L["Runtime_StepNormal"] = "GC step（普通），KB"
L["Runtime_StepCombat"] = "GC step（战斗），KB"
L["Runtime_StepIdle"] = "GC step（空闲），KB"
L["Runtime_StepLoading"] = "GC step（加载），KB"
L["Runtime_EmergencyMB"] = "紧急完整 GC 阈值，MB"
L["Runtime_IdleTimeout"] = "空闲超时，秒"
L["Runtime_SpeedyLoad"] = "加载界面优化"
L["Runtime_SpeedyLoadMode"] = "加载模式"
L["Runtime_SpeedyLoadSafe"] = "安全"
L["Runtime_SpeedyLoadAggressive"] = "激进"
L["Runtime_Debug"] = "诊断输出"
L["Runtime_DllStatus"] = "wow_optimize.dll 状态"
L["Runtime_DllOwnsGC"] = "GC 由 wow_optimize.dll 接管 — Lua 步进已禁用。"
L["Runtime_ForceGC"] = "立即完整回收（非战斗）"
L["Runtime_ForceGC_Desc"] = "在非战斗时执行完整垃圾回收。战斗中不可用。"
L["Runtime_BlockedByLuaBoost"] = "检测到插件 !LuaBoost。为避免冲突，已禁用 SarychUI 的 GC 管理。请禁用或移除 !LuaBoost 以使用此选项。"

-- Modules
L["Modules"] = "模块"
L["Auto Confirm"] = "自动确认"
L["Crowd Control"] = "控制效果"
L["Cooldown Text"] = "冷却与计时器"
L["Font_Path"] = "字体路径"
L["Font_Path_Desc"] = ".ttf 完整路径（例如 Fonts\\FRIZQT__.TTF）"
L["Font_Flags"] = "字体样式"
L["Font_Flags_Desc"] = "选项：NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "文字大小（< 60秒）"
L["Font_Size_Small_Desc"] = "剩余时间不足 60 秒时的文字大小"
L["Font_Size_Medium"] = "文字大小（1–10分钟）"
L["Font_Size_Medium_Desc"] = "1:00–9:59 以及 ≥10 分钟时的文字大小"
L["Font_Size_Large"] = "文字大小（>10分钟）"
L["Font_Size_Large_Desc"] = "分钟数值 ≥ 10 时的文字大小"
L["Default_Color"] = "默认文字颜色"
L["Appearance"] = "外观"
L["Display_Conditions"] = "显示条件"
L["Behavior"] = "行为"
L["Min_Scale"] = "最小缩放"
L["Min_Scale_Desc"] = "当图标有效缩放更低时隐藏文字"
L["Min_Icon_Size"] = "最小图标尺寸"
L["Min_Icon_Size_Desc"] = "当图标宽/高更小时隐藏文字"
L["Hide_On_GCD"] = "GCD 时隐藏"
L["Hide_On_GCD_Desc"] = "隐藏带有公共冷却时间的技能冷却文字（GCD 约 1.5 秒）"
L["Chat"] = "聊天"
L["Error Filter"] = "错误过滤"
L["Frame"] = "框体"
L["Frames"] = "框体"
L["Auras"] = "光环"
L["Frame Auras"] = "框体光环"
L["Character Auras"] = "角色光环"
L["MainMenuBar"] = "动作条"
L["MainMenuBar_Description"] = "自定义动作条，包括快捷键管理与宏名称设置。"
L["Enable_Module"] = "启用模块"
L["Enable_Module_Desc"] = "完全启用或禁用动作条模块。"
L["Hotkeys"] = "快捷键"
L["Color Indication"] = "颜色提示"
L["Color_Indication_Enabled"] = "启用颜色提示"
L["Color_Indication_Enabled_Desc"] = "启用或禁用动作条按钮的颜色提示"
L["Color_Cooldown_Enabled"] = "冷却中变灰"
L["Color_Cooldown_Enabled_Desc"] = "冷却超过 1.5 秒时将按钮变灰"
L["Color_Cooldown_Alpha"] = "冷却透明度"
L["Color_Cooldown_Alpha_Desc"] = "冷却中按钮的透明度（0 - 不可见，1 - 默认）"
L["Color_Mana_Enabled"] = "资源不足时变蓝"
L["Color_Mana_Enabled_Desc"] = "法力、能量或怒气不足时将按钮变蓝"
L["Color_Range_Enabled"] = "超出距离变红"
L["Color_Range_Enabled_Desc"] = "目标超出距离时将按钮变红"
L["Color_Unusable_Enabled"] = "不可用时深灰"
L["Color_Unusable_Enabled_Desc"] = "技能不可用时将按钮变为深灰色"
L["Interface"] = "界面"
L["Visual"] = "文字"
L["Hide_Hotkeys"] = "隐藏快捷键"
L["Hide_Hotkeys_Desc"] = "隐藏动作条按钮上的快捷键文字"
L["Show_In_Combat"] = "战斗中显示"
L["Show_In_Combat_Desc"] = "即使已隐藏，战斗中仍显示快捷键"
L["Show_On_Alt"] = "按住 |cFFFFD700Alt|r 时显示"
L["Show_On_Alt_Desc"] = "按住 |cFFFFD700Alt|r 键时显示快捷键"
L["Show_With_Target"] = "有目标时显示"
L["Show_With_Target_Desc"] = "有目标时显示快捷键（在设置为隐藏时）；清除目标后再次隐藏。可与战斗显示和 Alt 显示一起使用。不影响宏名称。"
L["Fade_After_Combat"] = "战斗后淡入淡出"
L["Fade_After_Combat_Desc"] = "战斗后快捷键平滑淡入/淡出"
L["Fade_Time"] = "淡入淡出时间"
L["Fade_Time_Desc"] = "快捷键平滑淡入/淡出的时间（秒）"
L["Macros"] = "宏"
L["Hide_Macro_Names"] = "隐藏宏名称"
L["Hide_Macro_Names_Desc"] = "隐藏动作条按钮上的宏名称"
L["Hide Hotkeys"] = "隐藏快捷键"
L["Show in Combat"] = "战斗中显示"
L["Show on Alt"] = "按住 |cFFFFD700Alt|r 时显示"
L["Fade After Combat"] = "战斗后淡入淡出"
L["Fade Time"] = "淡入淡出时间"
L["Hide Macro Names"] = "隐藏宏名称"
L["Color Indication Enabled"] = "启用颜色提示"
L["Cooldown Color"] = "冷却颜色"
L["Cooldown Alpha"] = "冷却透明度"
L["Mana Color"] = "法力颜色"
L["Range Color"] = "距离颜色"
L["Unusable Color"] = "不可用颜色"
L["Show Panels on Alt"] = "按住 |cFFFFD700Alt|r 时显示面板"
L["Hide Gryphons"] = "隐藏狮鹫"
L["Hide Decorative Elements"] = "隐藏装饰元素"
L["Hide Action Bar Backgrounds"] = "隐藏动作条背景"
L["Hide Shapeshift Backgrounds"] = "隐藏变形条背景"
L["Hide Pet Bar Backgrounds"] = "隐藏宠物条背景"
L["Hide Possess Bar Backgrounds"] = "隐藏控制条背景"
L["Hide Bonus Bar Textures"] = "隐藏额外动作条材质"
L["Hide Keyring Button"] = "隐藏钥匙链按钮"
L["Hide Page Buttons"] = "隐藏翻页按钮"
L["Hide Max Level Bar"] = "隐藏满级条"
L["Hide Page Numbers"] = "隐藏页码"
L["Show Page Numbers in Combat"] = "战斗中显示页码"
L["Show Page Numbers on Alt"] = "按住 |cFFFFD700Alt|r 时显示页码"
L["Page Numbers Fade After Combat"] = "战斗后页码淡入淡出"
L["Page Numbers Fade Time"] = "页码淡入淡出时间"
L["Hide Exp Bar"] = "隐藏经验条"
L["Show Exp Bar on Alt"] = "按住 |cFFFFD700Alt|r 时显示经验条"
L["Show Exp Bar on Gain"] = "获得经验时显示经验条"
L["Exp Bar Fade Time"] = "经验条淡入淡出时间"
L["Exp Bar Show Time"] = "经验条显示时间"
L["Hide Rep Bar"] = "隐藏声望条"
L["Show Rep Bar on Alt"] = "按住 |cFFFFD700Alt|r 时显示声望条"
L["Show_Reputation_Bar_On_Gain"] = "声望变化时显示"
L["Show_Reputation_Bar_On_Gain_Desc"] = "获得或失去声望时临时显示声望条。"
L["Reputation_Bar_Fade_Time"] = "声望条淡入淡出时长"
L["Reputation_Bar_Fade_Time_Desc"] = "声望条出现/消失动画的时长。"
L["Reputation_Bar_Show_Time"] = "声望条显示时间"
L["Reputation_Bar_Show_Time_Desc"] = "声望变化后声望条保持可见的时长。"
L["Button Border Alpha"] = "按钮边框透明度"
L["Micro Menu Alpha"] = "微型菜单透明度"
L["Button Border Alpha Enabled"] = "启用按钮边框透明度"
L["Micro Menu Alpha Enabled"] = "启用微型菜单透明度"
L["Minimap"] = "小地图"
L["Nameplates"] = "姓名板"
L["Plates Auras"] = "姓名板光环"
L["Health Indicators"] = "生命指示"
L["Health Indicators Desc"] = "选择生命指示 / 姓名板系统。"
L["Health Indicator Type"] = "生命指示类型"
L["Health Indicator Type Desc"] = "ElvUI 使用内置的 ElvUI 姓名板。Classic WoW 使用默认的暴雪姓名板。"
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "正在编辑显示设置：%s"
L["Health Indicators Reload Notice"] = "需要重载界面才能完全应用生命指示类型的更改。"
L["Open ElvUI NamePlates Settings"] = "设置"
L["Open ElvUI NamePlates Settings Desc"] = "打开 ElvUI NamePlates 配置窗口（/enp）。"
L["Arena Frame Type"] = "竞技场框体类型"
L["Arena Frame Type Desc"] = "GladiusEx 使用内置的 GladiusEx 竞技场框体。Classic WoW 使用默认的 SarychUI 竞技场模块。"
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "打开 GladiusEx 设置"
L["Open GladiusEx Settings Desc"] = "打开 GladiusEx 配置窗口（/gex ui）。"
L["Arena Classic Settings Disabled"] = "这些设置仅在 Classic WoW 模式下可用。"
L["Map"] = "世界地图"
L["World Map"] = "世界地图"
L["Map Module Desc"] = "选择要使用的地图插件。"
L["Map Type"] = "地图类型"
L["Map Type Desc"] = "选择要使用的地图插件。"
L["Classic WoW Map"] = "Classic WoW 地图"
L["Open Mapster Settings"] = "打开 Mapster 设置"
L["Open Mapster Settings Desc"] = "打开 Mapster 配置窗口（/mapster）。"
L["Open Carbonite Settings"] = "打开 Carbonite 设置"
L["Open Carbonite Settings Desc"] = "打开 Carbonite 配置窗口（/carb options）。"
L["Map Type Reload"] = "需要重载界面才能应用地图类型更改。"
L["Nameplate Distance"] = "启用距离显示"
L["Nameplate Distance Desc"] = "需要 nameplate_range.dll。状态：系统 -> 概览。"
L["Nameplate Distance Tab"] = "姓名板距离"
L["Nameplate Distance Font Desc"] = "姓名板上距离文字的字体。"
L["Nameplate Distance Font Size Desc"] = "距离文字的字体大小。"
L["Nameplate Distance Offset X Desc"] = "距离文字的水平偏移。"
L["Nameplate Distance Offset Y Desc"] = "距离文字的垂直偏移。"
L["Font Size"] = "字体大小"
L["Position X"] = "位置 X"
L["Position Y"] = "位置 Y"
L["Font Outline"] = "字体描边"
L["Nameplate Distance Font Outline Desc"] = "距离标签的描边样式（与 ElvUI NamePlates 相同选项）。"
L["Shadow X"] = "阴影 X"
L["Shadow Y"] = "阴影 Y"
L["Nameplate Distance Shadow X Desc"] = "距离文字阴影的水平偏移。"
L["Nameplate Distance Shadow Y Desc"] = "距离文字阴影的垂直偏移。"
L["None"] = "无"
L["Reload UI"] = "重载界面"
L["Reload UI Desc"] = "执行 /reload 以应用更改。"
L["Tools"] = "其他"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "自动确认模块会自动确认各种对话框。"
L["Crowd Control module displays CC effects on your screen."] = "控制效果模块在屏幕上显示 CC 效果。"
L["Chat module enhances the chat interface with additional features."] = "聊天模块为聊天界面提供额外功能。"
L["Error Filter module filters out annoying error messages."] = "错误过滤模块过滤烦人的错误提示。"
L["Frame module allows you to move and customize unit frames."] = "框体模块允许移动和自定义单位框体。"
L["Main Menu Bar module customizes the main action bar."] = "动作条模块自定义主动作条。"
L["Minimap module enhances and customizes the minimap."] = "小地图模块增强并自定义小地图。"
L["Plates Auras module displays auras on nameplates."] = "姓名板光环模块在姓名板上显示光环。"
L["Tools module provides various utility functions."] = "其他模块提供各种实用功能。"

-- Module description keys for options
L["Frames_Description"] = "单位框体修改设置"
L["Auras_Description"] = "光环隐藏、驱散高亮以及玩家增益框体管理"
L["Minimap_Description"] = "小地图设置"
L["Chat_Description"] = "聊天与消息设置"
L["Tools_Description"] = "各种工具与实用功能"
L["MainMenuBar_Description"] = "主命令栏与动作条设置"
L["CooldownText_Description"] = "冷却文字与计时器显示设置"
L["Automation_Description"] = "各种游戏操作的自动化"

-- Auto Confirm
L["Confirm Loot"] = "确认拾取"
L["Automatically confirm loot rolls."] = "自动确认拾取掷骰。"
L["Confirm Bind"] = "确认绑定"
L["Automatically confirm binding items."] = "自动确认物品绑定。"
L["Confirm Delete"] = "确认删除"
L["Automatically confirm item deletion."] = "自动确认物品删除。"
L["Confirm Quest"] = "确认任务"
L["Automatically confirm quest dialogs."] = "自动确认任务对话框。"

-- Crowd Control
L["Show Icon"] = "显示图标"
L["Show CC icon when you are affected by crowd control."] = "受到控制效果时显示 CC 图标。"
L["Icon Size"] = "图标大小"
L["Size of the CC icon."] = "CC 图标的大小。"
L["Icon Position"] = "图标位置"
L["Position of the CC icon on screen."] = "CC 图标在屏幕上的位置。"
L["Show Timer"] = "显示计时器"
L["Show remaining time on CC effects."] = "显示控制效果的剩余时间。"

-- Chat
L["Chat Bar"] = "聊天栏"
L["Enable chat bar with quick channel buttons."] = "启用带有快速频道按钮的聊天栏。"
L["Position"] = "位置"
L["Chat bar position."] = "聊天栏位置。"
L["Timestamps"] = "时间戳"
L["Show timestamps in chat."] = "在聊天中显示时间戳。"
L["Class Colors"] = "职业颜色"
L["Color player names by class."] = "按职业为玩家名称着色。"
L["Short Channel Names"] = "短频道名"
L["Use abbreviated channel names."] = "使用缩写频道名。"

-- Error Filter
L["Filters"] = "过滤器"
L["Configure which errors to filter."] = "配置要过滤的错误。"

-- Frame
L["Move Frames"] = "移动框体"
L["Allow moving unit frames."] = "允许移动单位框体。"
L["Combat Indicator"] = "战斗指示"
L["Show combat indicator on frames."] = "在框体上显示战斗指示。"
L["Size"] = "大小"
L["Frame Text"] = "框体文字"
L["Show Name"] = "显示名称"
L["Show Level"] = "显示等级"
L["Show Class"] = "显示职业"

-- Main Menu Bar
L["Hide Art"] = "隐藏美术"
L["Hide background art from the main menu bar."] = "隐藏主菜单栏的背景美术。"
L["Hide Gryphons"] = "隐藏狮鹫"
L["Hide the gryphon decorations."] = "隐藏狮鹫装饰。"
L["Show Buttons"] = "显示按钮"
L["Configure which buttons to show."] = "配置要显示的按钮。"

-- Minimap
L["Shape"] = "形状"
L["Minimap shape (square or round)."] = "小地图形状（方形或圆形）。"
L["Square"] = "方形"
L["Round"] = "圆形"
L["Zoom"] = "缩放"
L["Enable zoom buttons."] = "启用缩放按钮。"

-- Plates Auras
L["Show Buffs"] = "显示增益"
L["Display buffs on nameplates."] = "在姓名板上显示增益。"
L["Show Debuffs"] = "显示减益"
L["Display debuffs on nameplates."] = "在姓名板上显示减益。"
L["Max Icons"] = "最大图标数"
L["Maximum number of icons to display."] = "要显示的最大图标数量。"
L["Only Mine"] = "仅自己的"
L["Only show auras cast by you."] = "仅显示你施放的光环。"
L["Show Duration"] = "显示持续时间"
L["Display remaining duration on auras."] = "显示光环的剩余持续时间。"
L["Spell Settings"] = "法术设置"
L["Visibility"] = "可见性"
L["Show this spell on nameplates"] = "在姓名板上显示此法术"
L["Spell Type"] = "法术类型"
L["Type"] = "类型"
L["Spell Priority"] = "法术优先级"
L["Custom Priority"] = "自定义优先级"
L["Priority"] = "优先级"
L["Higher priority spells will take precedence regardless of duration"] = "优先级更高的法术会优先显示，与持续时间无关"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC 确认"
L["Allow ESC key to confirm dialogs."] = "允许使用 ESC 键确认对话框。"
L["No Combat Errors"] = "战斗中无错误"
L["Hide errors during combat."] = "战斗中隐藏错误提示。"
L["Speedy Load"] = "快速加载"
L["Faster addon loading."] = "更快的插件加载。"

-- Positions
L["Top"] = "上"
L["Bottom"] = "下"
L["Left"] = "左"
L["Right"] = "右"
L["Center"] = "中"
L["Top Left"] = "左上"
L["Top Right"] = "右上"
L["Bottom Left"] = "左下"
L["Bottom Right"] = "右下"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+点击标签页 – |cFFFFD700复制窗口|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "启用对聊天标签页的 Ctrl+点击复制"
L["Messages"] = "消息：%d"
L["Drag_to_size"] = "拖动调整大小 | 右键关闭"

-- Tooltip Settings
L["Tooltip_Settings"] = "窗口设置"
L["Enable_Tooltip_Position"] = "更改窗口位置"
L["Enable_Tooltip_Position_Desc"] = "启用自定义鼠标提示窗口位置"
L["Tooltip_Base_Offset"] = "基础偏移"
L["Tooltip_Base_Offset_Desc"] = "鼠标提示窗口的基础偏移"
L["Tooltip_Pet_Offset"] = "宠物偏移"
L["Tooltip_Pet_Offset_Desc"] = "宠物激活时鼠标提示窗口的额外偏移"
L["Enable_Chat_Icons"] = "在提示窗口中显示图标"
L["Enable_Chat_Icons_Desc"] = "在聊天消息中显示物品、法术和成就图标"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "隐藏好友按钮"
L["Enable_Friends_Button_Mod_Desc"] = "隐藏聊天中的好友按钮"
L["Enable_Hide_Chat_Frame_Button"] = "隐藏通讯按钮"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "隐藏通讯按钮"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "隐藏聊天中的通讯按钮"
L["Enable_Hide_Chat_Scroll_Buttons"] = "隐藏上下箭头"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "隐藏聊天中的上下滚动箭头"
L["Enable_Hide_Chat_Bottom_Button"] = "隐藏到底部箭头"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "隐藏聊天中的到底部箭头"

-- Chat Animations
L["Chat_Animations"] = "聊天动画"
L["Enable_Chat_Animations"] = "启用聊天动画"
L["Enable_Chat_Animations_Desc"] = "启用自定义聊天动画"
L["Chat_Tab_Show_Delay"] = "标签显示延迟（秒）"
L["Chat_Tab_Show_Delay_Desc"] = "显示聊天标签前的延迟"
L["Chat_Tab_Hide_Delay"] = "标签隐藏延迟（秒）"
L["Chat_Tab_Hide_Delay_Desc"] = "隐藏聊天标签前的延迟"
L["Chat_Frame_Fade_Time"] = "淡入时长（秒）"
L["Chat_Frame_Fade_Time_Desc"] = "聊天出现动画的时长"
L["Chat_Frame_Fade_Out_Time"] = "淡出时长（秒）"
L["Chat_Frame_Fade_Out_Time_Desc"] = "聊天消失动画的时长"

-- Messages
L["Profile reset to defaults."] = "配置文件已重置为默认值。"
L["Module enabled."] = "模块已启用。"
L["Module disabled."] = "模块已禁用。"

SarychUI.RegisterLocale("zhCN", L)
