-- SarychUI zhTW Localization
local L = {}

-- General
L["SarychUI"] = "SarychUI"
L["General"] = "一般"
L["Enable"] = "啟用"
L["Disable"] = "停用"
L["Enabled"] = "已啟用"
L["Settings"] = "設定"
L["Options"] = "選項"
L["Reset"] = "重置"
L["Default"] = "預設"

-- System / wow_optimize compatibility
L["System"] = "系統"
L["WowOptimize_Compat"] = "wow_optimize.dll"
L["WowOptimize_Compat_Desc"] = "選用的 wow_optimize.dll 相容模式。啟用後，SarychUI 不會重複 GC／戰鬥紀錄修正，並會降低名條與聊天泡泡的重度掃描。"
L["WowOptimize_Mode"] = "相容模式"
L["WowOptimize_Mode_Desc"] = "自動 — 透過 DLL 全域變數偵測（LUABOOST_DLL_*）。啟用 — 強制開啟。停用 — 一般 SarychUI。"
L["WowOptimize_Mode_Auto"] = "自動"
L["WowOptimize_Mode_Enabled"] = "啟用"
L["WowOptimize_Mode_Disabled"] = "停用"
L["WowOptimize_Debug"] = "相容除錯日誌"
L["WowOptimize_Debug_Desc"] = "在聊天中輸出已套用的適配（或設定 DEBUG_WOW_OPTIMIZE_COMPAT = true）。"
L["System_Overview"] = "總覽"
L["Dll_Detection_Header"] = "DLL 偵測"
L["Dll_Status_Detected"] = "已偵測到"
L["Dll_Status_NotDetected"] = "未偵測到"
L["Dll_Status_Checking"] = "檢查中..."
L["Dll_Status_NoMarker"] = "無 Lua 標記"
L["Dll_Status_ApiDetected"] = "已偵測到 API"
L["Dll_Status_WaitingNameplates"] = "等待名條"
L["Runtime_LuaOptimize"] = "Lua 優化"
L["Runtime_EnableGC"] = "啟用垃圾回收管理器"
L["Runtime_EnableGC_Desc"] = "依模式遞增 GC（一般／戰鬥／閒置／載入）。啟用 wow_optimize.dll 時，GC 由 DLL 接管。"
L["Runtime_Preset"] = "GC 設定檔"
L["Runtime_Preset_Light"] = "輕量"
L["Runtime_Preset_Standard"] = "標準"
L["Runtime_Preset_Heavy"] = "重度"
L["Runtime_Preset_Custom"] = "自訂"
L["Runtime_StepNormal"] = "GC step（一般），KB"
L["Runtime_StepCombat"] = "GC step（戰鬥），KB"
L["Runtime_StepIdle"] = "GC step（閒置），KB"
L["Runtime_StepLoading"] = "GC step（載入），KB"
L["Runtime_EmergencyMB"] = "緊急完整 GC 臨界值，MB"
L["Runtime_IdleTimeout"] = "閒置逾時，秒"
L["Runtime_SpeedyLoad"] = "載入畫面優化"
L["Runtime_SpeedyLoadMode"] = "載入模式"
L["Runtime_SpeedyLoadSafe"] = "安全"
L["Runtime_SpeedyLoadAggressive"] = "激進"
L["Runtime_Debug"] = "診斷輸出"
L["Runtime_DllStatus"] = "wow_optimize.dll 狀態"
L["Runtime_DllOwnsGC"] = "GC 由 wow_optimize.dll 接管 — Lua 步進已停用。"
L["Runtime_ForceGC"] = "立即完整回收（非戰鬥）"
L["Runtime_ForceGC_Desc"] = "在非戰鬥時執行完整垃圾回收。戰鬥中無法使用。"
L["Runtime_BlockedByLuaBoost"] = "偵測到插件 !LuaBoost。為避免衝突，已停用 SarychUI 的 GC 管理。請停用或移除 !LuaBoost 以使用此選項。"

-- Modules
L["Modules"] = "模組"
L["Auto Confirm"] = "自動確認"
L["Crowd Control"] = "控制效果"
L["Cooldown Text"] = "冷卻與計時器"
L["Font_Path"] = "字型路徑"
L["Font_Path_Desc"] = ".ttf 完整路徑（例如 Fonts\\FRIZQT__.TTF）"
L["Font_Flags"] = "字型樣式"
L["Font_Flags_Desc"] = "選項：NONE, OUTLINE, THICKOUTLINE, MONOCHROMEOUTLINE"
L["Font_Size_Small"] = "文字大小（< 60秒）"
L["Font_Size_Small_Desc"] = "剩餘時間不足 60 秒時的文字大小"
L["Font_Size_Medium"] = "文字大小（1–10分鐘）"
L["Font_Size_Medium_Desc"] = "1:00–9:59 以及 ≥10 分鐘時的文字大小"
L["Font_Size_Large"] = "文字大小（>10分鐘）"
L["Font_Size_Large_Desc"] = "分鐘數值 ≥ 10 時的文字大小"
L["Default_Color"] = "預設文字顏色"
L["Appearance"] = "外觀"
L["Display_Conditions"] = "顯示條件"
L["Behavior"] = "行為"
L["Min_Scale"] = "最小縮放"
L["Min_Scale_Desc"] = "當圖示有效縮放更低時隱藏文字"
L["Min_Icon_Size"] = "最小圖示尺寸"
L["Min_Icon_Size_Desc"] = "當圖示寬／高更小時隱藏文字"
L["Hide_On_GCD"] = "GCD 時隱藏"
L["Hide_On_GCD_Desc"] = "隱藏帶有公共冷卻時間的技能冷卻文字（GCD 約 1.5 秒）"
L["Chat"] = "聊天"
L["Error Filter"] = "錯誤過濾"
L["Frame"] = "框架"
L["Frames"] = "框架"
L["Auras"] = "光環"
L["Frame Auras"] = "框架光環"
L["Character Auras"] = "角色光環"
L["MainMenuBar"] = "快捷列"
L["MainMenuBar_Description"] = "自訂快捷列，包含快捷鍵管理與巨集名稱設定。"
L["Enable_Module"] = "啟用模組"
L["Enable_Module_Desc"] = "完全啟用或停用快捷列模組。"
L["Hotkeys"] = "快捷鍵"
L["Color Indication"] = "顏色提示"
L["Color_Indication_Enabled"] = "啟用顏色提示"
L["Color_Indication_Enabled_Desc"] = "啟用或停用快捷列按鈕的顏色提示"
L["Color_Cooldown_Enabled"] = "冷卻中變灰"
L["Color_Cooldown_Enabled_Desc"] = "冷卻超過 1.5 秒時將按鈕變灰"
L["Color_Cooldown_Alpha"] = "冷卻透明度"
L["Color_Cooldown_Alpha_Desc"] = "冷卻中按鈕的透明度（0 - 不可見，1 - 預設）"
L["Color_Mana_Enabled"] = "資源不足時變藍"
L["Color_Mana_Enabled_Desc"] = "法力、能量或怒氣不足時將按鈕變藍"
L["Color_Range_Enabled"] = "超出距離變紅"
L["Color_Range_Enabled_Desc"] = "目標超出距離時將按鈕變紅"
L["Color_Unusable_Enabled"] = "無法使用時深灰"
L["Color_Unusable_Enabled_Desc"] = "技能無法使用時將按鈕變為深灰色"
L["Interface"] = "介面"
L["Visual"] = "文字"
L["Hide_Hotkeys"] = "隱藏快捷鍵"
L["Hide_Hotkeys_Desc"] = "隱藏快捷列按鈕上的快捷鍵文字"
L["Show_In_Combat"] = "戰鬥中顯示"
L["Show_In_Combat_Desc"] = "即使已隱藏，戰鬥中仍顯示快捷鍵"
L["Show_On_Alt"] = "按住 |cFFFFD700Alt|r 時顯示"
L["Show_On_Alt_Desc"] = "按住 |cFFFFD700Alt|r 鍵時顯示快捷鍵"
L["Show_With_Target"] = "有目標時顯示"
L["Show_With_Target_Desc"] = "有目標時顯示快捷鍵（在設為隱藏時）；清除目標後再次隱藏。可與戰鬥顯示和 Alt 顯示一起使用。不影響巨集名稱。"
L["Fade_After_Combat"] = "戰鬥後淡入淡出"
L["Fade_After_Combat_Desc"] = "戰鬥後快捷鍵平滑淡入／淡出"
L["Fade_Time"] = "淡入淡出時間"
L["Fade_Time_Desc"] = "快捷鍵平滑淡入／淡出的時間（秒）"
L["Macros"] = "巨集"
L["Hide_Macro_Names"] = "隱藏巨集名稱"
L["Hide_Macro_Names_Desc"] = "隱藏快捷列按鈕上的巨集名稱"
L["Hide Hotkeys"] = "隱藏快捷鍵"
L["Show in Combat"] = "戰鬥中顯示"
L["Show on Alt"] = "按住 |cFFFFD700Alt|r 時顯示"
L["Fade After Combat"] = "戰鬥後淡入淡出"
L["Fade Time"] = "淡入淡出時間"
L["Hide Macro Names"] = "隱藏巨集名稱"
L["Color Indication Enabled"] = "啟用顏色提示"
L["Cooldown Color"] = "冷卻顏色"
L["Cooldown Alpha"] = "冷卻透明度"
L["Mana Color"] = "法力顏色"
L["Range Color"] = "距離顏色"
L["Unusable Color"] = "無法使用顏色"
L["Show Panels on Alt"] = "按住 |cFFFFD700Alt|r 時顯示面板"
L["Hide Gryphons"] = "隱藏獅鷲"
L["Hide Decorative Elements"] = "隱藏裝飾元素"
L["Hide Action Bar Backgrounds"] = "隱藏快捷列背景"
L["Hide Shapeshift Backgrounds"] = "隱藏變形列背景"
L["Hide Pet Bar Backgrounds"] = "隱藏寵物列背景"
L["Hide Possess Bar Backgrounds"] = "隱藏控制列背景"
L["Hide Bonus Bar Textures"] = "隱藏額外快捷列材質"
L["Hide Keyring Button"] = "隱藏鑰匙圈按鈕"
L["Hide Page Buttons"] = "隱藏翻頁按鈕"
L["Hide Max Level Bar"] = "隱藏滿級條"
L["Hide Page Numbers"] = "隱藏頁碼"
L["Show Page Numbers in Combat"] = "戰鬥中顯示頁碼"
L["Show Page Numbers on Alt"] = "按住 |cFFFFD700Alt|r 時顯示頁碼"
L["Page Numbers Fade After Combat"] = "戰鬥後頁碼淡入淡出"
L["Page Numbers Fade Time"] = "頁碼淡入淡出時間"
L["Hide Exp Bar"] = "隱藏經驗條"
L["Show Exp Bar on Alt"] = "按住 |cFFFFD700Alt|r 時顯示經驗條"
L["Show Exp Bar on Gain"] = "獲得經驗時顯示經驗條"
L["Exp Bar Fade Time"] = "經驗條淡入淡出時間"
L["Exp Bar Show Time"] = "經驗條顯示時間"
L["Hide Rep Bar"] = "隱藏聲望條"
L["Show Rep Bar on Alt"] = "按住 |cFFFFD700Alt|r 時顯示聲望條"
L["Show_Reputation_Bar_On_Gain"] = "聲望變化時顯示"
L["Show_Reputation_Bar_On_Gain_Desc"] = "獲得或失去聲望時暫時顯示聲望條。"
L["Reputation_Bar_Fade_Time"] = "聲望條淡入淡出時長"
L["Reputation_Bar_Fade_Time_Desc"] = "聲望條出現／消失動畫的時長。"
L["Reputation_Bar_Show_Time"] = "聲望條顯示時間"
L["Reputation_Bar_Show_Time_Desc"] = "聲望變化後聲望條保持可見的時長。"
L["Button Border Alpha"] = "按鈕邊框透明度"
L["Micro Menu Alpha"] = "微型選單透明度"
L["Button Border Alpha Enabled"] = "啟用按鈕邊框透明度"
L["Micro Menu Alpha Enabled"] = "啟用微型選單透明度"
L["Minimap"] = "小地圖"
L["Nameplates"] = "名條"
L["Plates Auras"] = "名條光環"
L["Health Indicators"] = "生命指示"
L["Health Indicators Desc"] = "選擇生命指示／名條系統。"
L["Health Indicator Type"] = "生命指示類型"
L["Health Indicator Type Desc"] = "ElvUI 使用內建的 ElvUI 名條。Classic WoW 使用預設的暴雪名條。"
L["Classic WoW Nameplates"] = "Classic WoW"
L["ElvUI Nameplates"] = "ElvUI"
L["Plates Auras Profile Edit"] = "正在編輯顯示設定：%s"
L["Health Indicators Reload Notice"] = "需要重新載入介面才能完全套用生命指示類型的變更。"
L["Open ElvUI NamePlates Settings"] = "設定"
L["Open ElvUI NamePlates Settings Desc"] = "開啟 ElvUI NamePlates 設定視窗（/enp）。"
L["Arena Frame Type"] = "競技場框架類型"
L["Arena Frame Type Desc"] = "GladiusEx 使用內建的 GladiusEx 競技場框架。Classic WoW 使用預設的 SarychUI 競技場模組。"
L["Classic WoW Arena Frames"] = "Classic WoW"
L["Open GladiusEx Settings"] = "開啟 GladiusEx 設定"
L["Open GladiusEx Settings Desc"] = "開啟 GladiusEx 設定視窗（/gex ui）。"
L["Arena Classic Settings Disabled"] = "這些設定僅在 Classic WoW 模式下可用。"
L["Map"] = "世界地圖"
L["World Map"] = "世界地圖"
L["Map Module Desc"] = "選擇要使用的地圖插件。"
L["Map Type"] = "地圖類型"
L["Map Type Desc"] = "選擇要使用的地圖插件。"
L["Classic WoW Map"] = "Classic WoW 地圖"
L["Open Mapster Settings"] = "開啟 Mapster 設定"
L["Open Mapster Settings Desc"] = "開啟 Mapster 設定視窗（/mapster）。"
L["Open Carbonite Settings"] = "開啟 Carbonite 設定"
L["Open Carbonite Settings Desc"] = "開啟 Carbonite 設定視窗（/carb options）。"
L["Map Type Reload"] = "需要重新載入介面才能套用地圖類型變更。"
L["Nameplate Distance"] = "啟用距離顯示"
L["Nameplate Distance Desc"] = "需要 nameplate_range.dll。狀態：系統 -> 總覽。"
L["Nameplate Distance Tab"] = "名條距離"
L["Nameplate Distance Font Desc"] = "名條上距離文字的字型。"
L["Nameplate Distance Font Size Desc"] = "距離文字的字型大小。"
L["Nameplate Distance Offset X Desc"] = "距離文字的水平偏移。"
L["Nameplate Distance Offset Y Desc"] = "距離文字的垂直偏移。"
L["Font Size"] = "字型大小"
L["Position X"] = "位置 X"
L["Position Y"] = "位置 Y"
L["Font Outline"] = "字型外框"
L["Nameplate Distance Font Outline Desc"] = "距離標籤的外框樣式（與 ElvUI NamePlates 相同選項）。"
L["Shadow X"] = "陰影 X"
L["Shadow Y"] = "陰影 Y"
L["Nameplate Distance Shadow X Desc"] = "距離文字陰影的水平偏移。"
L["Nameplate Distance Shadow Y Desc"] = "距離文字陰影的垂直偏移。"
L["None"] = "無"
L["Reload UI"] = "重新載入介面"
L["Reload UI Desc"] = "執行 /reload 以套用變更。"
L["Tools"] = "其他"

-- Module Descriptions
L["Auto Confirm module automatically confirms various dialogs."] = "自動確認模組會自動確認各種對話框。"
L["Crowd Control module displays CC effects on your screen."] = "控制效果模組在螢幕上顯示 CC 效果。"
L["Chat module enhances the chat interface with additional features."] = "聊天模組為聊天介面提供額外功能。"
L["Error Filter module filters out annoying error messages."] = "錯誤過濾模組過濾惱人的錯誤提示。"
L["Frame module allows you to move and customize unit frames."] = "框架模組允許移動與自訂單位框架。"
L["Main Menu Bar module customizes the main action bar."] = "快捷列模組自訂主快捷列。"
L["Minimap module enhances and customizes the minimap."] = "小地圖模組強化並自訂小地圖。"
L["Plates Auras module displays auras on nameplates."] = "名條光環模組在名條上顯示光環。"
L["Tools module provides various utility functions."] = "其他模組提供各種實用功能。"

-- Module description keys for options
L["Frames_Description"] = "單位框架修改設定"
L["Auras_Description"] = "光環隱藏、驅散醒目提示與玩家增益框架管理"
L["Minimap_Description"] = "小地圖設定"
L["Chat_Description"] = "聊天與訊息設定"
L["Tools_Description"] = "各種工具與實用功能"
L["MainMenuBar_Description"] = "主命令列與快捷列設定"
L["CooldownText_Description"] = "冷卻文字與計時器顯示設定"
L["Automation_Description"] = "各種遊戲操作的自動化"

-- Auto Confirm
L["Confirm Loot"] = "確認拾取"
L["Automatically confirm loot rolls."] = "自動確認拾取擲骰。"
L["Confirm Bind"] = "確認綁定"
L["Automatically confirm binding items."] = "自動確認物品綁定。"
L["Confirm Delete"] = "確認刪除"
L["Automatically confirm item deletion."] = "自動確認物品刪除。"
L["Confirm Quest"] = "確認任務"
L["Automatically confirm quest dialogs."] = "自動確認任務對話框。"

-- Crowd Control
L["Show Icon"] = "顯示圖示"
L["Show CC icon when you are affected by crowd control."] = "受到控制效果時顯示 CC 圖示。"
L["Icon Size"] = "圖示大小"
L["Size of the CC icon."] = "CC 圖示的大小。"
L["Icon Position"] = "圖示位置"
L["Position of the CC icon on screen."] = "CC 圖示在螢幕上的位置。"
L["Show Timer"] = "顯示計時器"
L["Show remaining time on CC effects."] = "顯示控制效果的剩餘時間。"

-- Chat
L["Chat Bar"] = "聊天列"
L["Enable chat bar with quick channel buttons."] = "啟用帶有快速頻道按鈕的聊天列。"
L["Position"] = "位置"
L["Chat bar position."] = "聊天列位置。"
L["Timestamps"] = "時間戳記"
L["Show timestamps in chat."] = "在聊天中顯示時間戳記。"
L["Class Colors"] = "職業顏色"
L["Color player names by class."] = "依職業為玩家名稱著色。"
L["Short Channel Names"] = "短頻道名稱"
L["Use abbreviated channel names."] = "使用縮寫頻道名稱。"

-- Error Filter
L["Filters"] = "過濾器"
L["Configure which errors to filter."] = "設定要過濾的錯誤。"

-- Frame
L["Move Frames"] = "移動框架"
L["Allow moving unit frames."] = "允許移動單位框架。"
L["Combat Indicator"] = "戰鬥指示"
L["Show combat indicator on frames."] = "在框架上顯示戰鬥指示。"
L["Size"] = "大小"
L["Frame Text"] = "框架文字"
L["Show Name"] = "顯示名稱"
L["Show Level"] = "顯示等級"
L["Show Class"] = "顯示職業"

-- Main Menu Bar
L["Hide Art"] = "隱藏美術"
L["Hide background art from the main menu bar."] = "隱藏主選單列的背景美術。"
L["Hide Gryphons"] = "隱藏獅鷲"
L["Hide the gryphon decorations."] = "隱藏獅鷲裝飾。"
L["Show Buttons"] = "顯示按鈕"
L["Configure which buttons to show."] = "設定要顯示的按鈕。"

-- Minimap
L["Shape"] = "形狀"
L["Minimap shape (square or round)."] = "小地圖形狀（方形或圓形）。"
L["Square"] = "方形"
L["Round"] = "圓形"
L["Zoom"] = "縮放"
L["Enable zoom buttons."] = "啟用縮放按鈕。"

-- Plates Auras
L["Show Buffs"] = "顯示增益"
L["Display buffs on nameplates."] = "在名條上顯示增益。"
L["Show Debuffs"] = "顯示減益"
L["Display debuffs on nameplates."] = "在名條上顯示減益。"
L["Max Icons"] = "最大圖示數"
L["Maximum number of icons to display."] = "要顯示的最大圖示數量。"
L["Only Mine"] = "僅自己的"
L["Only show auras cast by you."] = "僅顯示你施放的光環。"
L["Show Duration"] = "顯示持續時間"
L["Display remaining duration on auras."] = "顯示光環的剩餘持續時間。"
L["Spell Settings"] = "法術設定"
L["Visibility"] = "可見性"
L["Show this spell on nameplates"] = "在名條上顯示此法術"
L["Spell Type"] = "法術類型"
L["Type"] = "類型"
L["Spell Priority"] = "法術優先順序"
L["Custom Priority"] = "自訂優先順序"
L["Priority"] = "優先順序"
L["Higher priority spells will take precedence regardless of duration"] = "優先順序較高的法術會優先顯示，與持續時間無關"
L["immunities"] = "immunities"
L["cc"] = "cc"
L["silence"] = "silence"
L["interrupts"] = "interrupts"
L["roots"] = "roots"
L["disarm"] = "disarm"
L["buffs_defensive"] = "buffs_defensive"
L["buffs_offensive"] = "buffs_offensive"
L["buffs_other"] = "buffs_other"
L["snare"] = "snare"
L["cast"] = "cast"
L["other"] = "other"

-- Tools
L["ESC to OK"] = "ESC 確認"
L["Allow ESC key to confirm dialogs."] = "允許使用 ESC 鍵確認對話框。"
L["No Combat Errors"] = "戰鬥中無錯誤"
L["Hide errors during combat."] = "戰鬥中隱藏錯誤提示。"
L["Speedy Load"] = "快速載入"
L["Faster addon loading."] = "更快的插件載入。"

-- Positions
L["Top"] = "上"
L["Bottom"] = "下"
L["Left"] = "左"
L["Right"] = "右"
L["Center"] = "中"
L["Top Left"] = "左上"
L["Top Right"] = "右上"
L["Bottom Left"] = "左下"
L["Bottom Right"] = "右下"

-- Chat Copying
L["Enable_Chat_Copy_On_Ctrl_Click"] = "Ctrl+點擊標籤頁 – |cFFFFD700複製視窗|r"
L["Enable_Chat_Copy_On_Ctrl_Click_Desc"] = "啟用對聊天標籤頁的 Ctrl+點擊複製"
L["Messages"] = "訊息：%d"
L["Drag_to_size"] = "拖曳調整大小 | 右鍵關閉"

-- Tooltip Settings
L["Tooltip_Settings"] = "視窗設定"
L["Enable_Tooltip_Position"] = "變更視窗位置"
L["Enable_Tooltip_Position_Desc"] = "啟用自訂滑鼠提示視窗位置"
L["Tooltip_Base_Offset"] = "基礎偏移"
L["Tooltip_Base_Offset_Desc"] = "滑鼠提示視窗的基礎偏移"
L["Tooltip_Pet_Offset"] = "寵物偏移"
L["Tooltip_Pet_Offset_Desc"] = "寵物啟用時滑鼠提示視窗的額外偏移"
L["Enable_Chat_Icons"] = "在提示視窗中顯示圖示"
L["Enable_Chat_Icons_Desc"] = "在聊天訊息中顯示物品、法術與成就圖示"

-- Chat Appearance Settings
L["Enable_Friends_Button_Mod"] = "隱藏好友按鈕"
L["Enable_Friends_Button_Mod_Desc"] = "隱藏聊天中的好友按鈕"
L["Enable_Hide_Chat_Frame_Button"] = "隱藏通訊按鈕"
L["Enable_Hide_Chat_Frame_Button_Tittle"] = "隱藏通訊按鈕"
L["Enable_Hide_Chat_Frame_Button_Desc"] = "隱藏聊天中的通訊按鈕"
L["Enable_Hide_Chat_Scroll_Buttons"] = "隱藏上下箭頭"
L["Enable_Hide_Chat_Scroll_Buttons_Desc"] = "隱藏聊天中的上下捲動箭頭"
L["Enable_Hide_Chat_Bottom_Button"] = "隱藏到底部箭頭"
L["Enable_Hide_Chat_Bottom_Button_Desc"] = "隱藏聊天中的到底部箭頭"

-- Chat Animations
L["Chat_Animations"] = "聊天動畫"
L["Enable_Chat_Animations"] = "啟用聊天動畫"
L["Enable_Chat_Animations_Desc"] = "啟用自訂聊天動畫"
L["Chat_Tab_Show_Delay"] = "標籤顯示延遲（秒）"
L["Chat_Tab_Show_Delay_Desc"] = "顯示聊天標籤前的延遲"
L["Chat_Tab_Hide_Delay"] = "標籤隱藏延遲（秒）"
L["Chat_Tab_Hide_Delay_Desc"] = "隱藏聊天標籤前的延遲"
L["Chat_Frame_Fade_Time"] = "淡入時長（秒）"
L["Chat_Frame_Fade_Time_Desc"] = "聊天出現動畫的時長"
L["Chat_Frame_Fade_Out_Time"] = "淡出時長（秒）"
L["Chat_Frame_Fade_Out_Time_Desc"] = "聊天消失動畫的時長"

-- Messages
L["Profile reset to defaults."] = "設定檔已重置為預設值。"
L["Module enabled."] = "模組已啟用。"
L["Module disabled."] = "模組已停用。"

SarychUI.RegisterLocale("zhTW", L)
