-- Meme Pack v2 smiley registry
SarychUI_MemePackV2Data = {
    memes = {
        { code = ":3head:", file = "3head.tga" },
        { code = ":5head:", file = "5head.tga" },
        { code = ":alta:", file = "alta.tga" },
        { code = ":ayaya:", file = "ayaya.tga" },
        { code = ":ayowtf:", file = "ayowtf.tga" },
        { code = ":based:", file = "based.tga" },
        { code = ":blehhhh:", file = "blehhhh.tga" },
        { code = ":bedge:", file = "bedge.tga" },
        { code = ":caught:", file = "caught.tga" },
        { code = ":copium:", file = "copium.tga" },
        { code = ":catchest:", file = "catchest.tga" },
        { code = ":chadge:", file = "chadge.tga" },
        { code = ":cinema:", file = "cinema.tga" },
        { code = ":clueless:", file = "clueless.tga" },
        { code = ":concerned:", file = "concerned.tga" },
        { code = ":considering:", file = "considering.tga" },
        { code = ":d_dot:", file = "d_dot.tga" },
        { code = ":deadge:", file = "deadge.tga" },
        { code = ":death:", file = "death.tga" },
        { code = ":dentge:", file = "dentge.tga" },
        { code = ":despairge:", file = "despairge.tga" },
        { code = ":dogo:", file = "dogo.tga" },
        { code = ":earthquake:", file = "earthquake.tga" },
        { code = ":ez:", file = "ez.tga" },
        { code = ":ermactually:", file = "ermactually.tga" },
        { code = ":feelsokayman:", file = "feelsokayman.tga" },
        { code = ":feelsstrongman:", file = "feelsstrongman.tga" },
        { code = ":feelsweirdman:", file = "feelsweirdman.tga" },
        { code = ":feelswowman:", file = "feelswowman.tga" },
        { code = ":flushed:", file = "flushed.tga" },
        { code = ":gandon:", file = "gandon.tga" },
        { code = ":gandonbi:", file = "gandonbi.tga" },
        { code = ":gooning:", file = "gooning.tga" },
        { code = ":hahaa:", file = "hahaa.tga" },
        { code = ":holy:", file = "holy.tga" },
        { code = ":huh:", file = "huh.tga" },
        { code = ":hypers:", file = "hypers.tga" },
        { code = ":haltdeinmaul:", file = "haltdeinmaul.tga" },
        { code = ":hehe:", file = "hehe.tga" },
        { code = ":heisenberj:", file = "heisenberj.tga" },
        { code = ":hmm:", file = "hmm.tga" },
        { code = ":kekl:", file = "kekl.tga" },
        { code = ":kekw:", file = "kekw.tga" },
        { code = ":kekwait:", file = "kekwait.tga" },
        { code = ":kkomrade:", file = "kkomrade.tga" },
        { code = ":lule:", file = "lule.tga" },
        { code = ":lulw:", file = "lulw.tga" },
        { code = ":life:", file = "life.tga" },
        { code = ":looking:", file = "looking.tga" },
        { code = ":monka:", file = "monka.tga" },
        { code = ":madge:", file = "madge.tga" },
        { code = ":modding:", file = "modding.tga" },
        { code = ":noway:", file = "noway.tga" },
        { code = ":nobitches:", file = "nobitches.tga" },
        { code = ":nyehehehe:", file = "nyehehehe.tga" },
        { code = ":omegalul:", file = "omegalul.tga" },
        { code = ":okayeg:", file = "okayeg.tga" },
        { code = ":okayge:", file = "okayge.tga" },
        { code = ":oldge:", file = "oldge.tga" },
        { code = ":poggers:", file = "poggers.tga" },
        { code = ":poggies:", file = "poggies.tga" },
        { code = ":pupsik:", file = "pupsik.tga" },
        { code = ":pupsiki:", file = "pupsiki.tga" },
        { code = ":pausechamp:", file = "pausechamp.tga" },
        { code = ":pepeclown:", file = "pepeclown.tga" },
        { code = ":pepemods:", file = "pepemods.tga" },
        { code = ":pepewhy:", file = "pepewhy.tga" },
        { code = ":pepega:", file = "pepega.tga" },
        { code = ":pepog:", file = "pepog.tga" },
        { code = ":period:", file = "period.tga" },
        { code = ":pikafacepalm:", file = "pikafacepalm.tga" },
        { code = ":pog:", file = "pog.tga" },
        { code = ":pogo:", file = "pogo.tga" },
        { code = ":pogo2:", file = "pogo2.tga" },
        { code = ":pogu:", file = "pogu.tga" },
        { code = ":pointless:", file = "pointless.tga" },
        { code = ":prayge:", file = "prayge.tga" },
        { code = ":realization:", file = "realization.tga" },
        { code = ":reallymad:", file = "reallymad.tga" },
        { code = ":reallywow:", file = "reallywow.tga" },
        { code = ":sadding:", file = "sadding.tga" },
        { code = ":sadeg:", file = "sadeg.tga" },
        { code = ":sadge:", file = "sadge.tga" },
        { code = ":shrekoh:", file = "shrekoh.tga" },
        { code = ":smadge:", file = "smadge.tga" },
        { code = ":socialcreditsdown:", file = "socialcreditsdown.tga" },
        { code = ":socialcreditsup:", file = "socialcreditsup.tga" },
        { code = ":starege:", file = "starege.tga" },
        { code = ":suske:", file = "suske.tga" },
        { code = ":thonk:", file = "thonk.tga" },
        { code = ":threw:", file = "threw.tga" },
        { code = ":trolldespair:", file = "trolldespair.tga" },
        { code = ":ultramad:", file = "ultramad.tga" },
        { code = ":vibeoff:", file = "vibeoff.tga" },
        { code = ":wajaja:", file = "wajaja.tga" },
        { code = ":weigh:", file = "weigh.tga" },
        { code = ":waiting:", file = "waiting.tga" },
        { code = ":war:", file = "war.tga" },
        { code = ":watchingstream:", file = "watchingstream.tga" },
        { code = ":weirdcat:", file = "weirdcat.tga" },
        { code = ":xdd:", file = "xdd.tga" },
        { code = ":meme_0:", file = "meme_0.tga" },
        { code = ":meme_3:", file = "meme_3.tga" },
        { code = ":meme_33:", file = "meme_33.tga" },
        { code = ":meme_b:", file = "meme_b.tga" },
        { code = ":aaaa:", file = "aaaa.tga" },
        { code = ":angrydog:", file = "angrydog.tga" },
        { code = ":angy:", file = "angy.tga" },
        { code = ":auh:", file = "auh.tga" },
        { code = ":baseg:", file = "baseg.tga" },
        { code = ":bla:", file = "bla.tga" },
        { code = ":boo:", file = "boo.tga" },
        { code = ":bro:", file = "bro.tga" },
        { code = ":catblush:", file = "catblush.tga" },
        { code = ":catdespair:", file = "catdespair.tga" },
        { code = ":catrose:", file = "catrose.tga" },
        { code = ":cmonbrug:", file = "cmonbrug.tga" },
        { code = ":confusedcat:", file = "confusedcat.tga" },
        { code = ":coronas:", file = "coronas.tga" },
        { code = ":damn:", file = "damn.tga" },
        { code = ":ddx:", file = "ddx.tga" },
        { code = ":deshovka:", file = "deshovka.tga" },
        { code = ":dumbass:", file = "dumbass.tga" },
        { code = ":eww:", file = "eww.tga" },
        { code = ":fatasswizardtryingtocastaspellonyou:", file = "fatasswizardtryingtocastaspellonyou.tga" },
        { code = ":forsencd:", file = "forsencd.tga" },
        { code = ":fredrick:", file = "fredrick.tga" },
        { code = ":frfr:", file = "frfr.tga" },
        { code = ":frfr_pepe:", file = "frfr_pepe.tga" },
        { code = ":gachigasm:", file = "gachigasm.tga" },
        { code = ":glorp:", file = "glorp.tga" },
        { code = ":gooned:", file = "gooned.tga" },
        { code = ":maaaaan:", file = "maaaaan.tga" },
        { code = ":monkagun:", file = "monkagun.tga" },
        { code = ":monkahmm:", file = "monkahmm.tga" },
        { code = ":monkalaugh:", file = "monkalaugh.tga" },
        { code = ":monkaomega:", file = "monkaomega.tga" },
        { code = ":monkas:", file = "monkas.tga" },
        { code = ":monkaw:", file = "monkaw.tga" },
        { code = ":muh:", file = "muh.tga" },
        { code = ":o7:", file = "o7.tga" },
        { code = ":oh:", file = "oh.tga" },
        { code = ":ok:", file = "ok.tga" },
        { code = ":okak:", file = "okak.tga" },
        { code = ":oopsie:", file = "oopsie.tga" },
        { code = ":peepoblanket:", file = "peepoblanket.tga" },
        { code = ":peepoblush:", file = "peepoblush.tga" },
        { code = ":peepoclown:", file = "peepoclown.tga" },
        { code = ":peepohappy:", file = "peepohappy.tga" },
        { code = ":peeposad:", file = "peeposad.tga" },
        { code = ":peeposit:", file = "peeposit.tga" },
        { code = ":pepelaugh:", file = "pepelaugh.tga" },
        { code = ":pikao:", file = "pikao.tga" },
        { code = ":sadcat:", file = "sadcat.tga" },
        { code = ":shocked:", file = "shocked.tga" },
        { code = ":sideeye_bob:", file = "sideeye_bob.tga" },
        { code = ":sideeye:", file = "sideeye.tga" },
        { code = ":soysmug:", file = "soysmug.tga" },
        { code = ":sus:", file = "sus.tga" },
        { code = ":ta:", file = "ta.tga" },
        { code = ":tuh:", file = "tuh.tga" },
        { code = ":uwu:", file = "uwu.tga" },
        { code = ":waaa:", file = "waaa.tga" },
        { code = ":wesmart:", file = "wesmart.tga" },
        { code = ":weirdchamp:", file = "weirdchamp.tga" },
        { code = ":xdd666:", file = "xdd666.tga" },
        { code = ":xdx:", file = "xdx.tga" },
        { code = ":xpp:", file = "xpp.tga" },
        { code = ":yuh:", file = "yuh.tga" },
    },
    classic = {
        { keys = { ":)" }, file = "peepohappy.tga", picker = ":)" },
        { keys = { ":(", ":%(", ":%-%(" }, file = "peeposad.tga", picker = ":(" },
        { keys = { ":D", ":%-D", ";D", ";%-D", "=D", "xD", "XD" }, file = "kekw.tga", picker = ":D" },
        { keys = { ";)", ";%)", ";%-%)" }, file = "hehe.tga", picker = ";)" },
        { keys = { ":P", ":p", ":%-P", ":%-p", "=P", "=p", ";P", ";p", ";%-P", ";%-p" }, file = "blehhhh.tga", picker = ":P" },
        { keys = { "<3" }, file = "peepoblush.tga", picker = "<3" },
        { keys = { "</3", "<\\3" }, file = "sadge.tga", picker = "</3" },
        { keys = { ":angry:", ":%-@", ":@", ">:(" }, file = "angrydog.tga", picker = ":angry:" },
        { keys = { ":kappa:", ":komrade:" }, file = "kkomrade.tga", picker = ":kappa:" },
        { keys = { ":murloc:" }, file = "glorp.tga", picker = ":murloc:" },
        { keys = { ":facepalm:" }, file = "pikafacepalm.tga", picker = ":facepalm:" },
        { keys = { ":cry:", ":,%(", ":,%-%(", ":'%(", ":'%-%(" }, file = "peeposad.tga", picker = nil },
        { keys = { ":grin:", ":smile:" }, file = "peepohappy.tga", picker = nil },
        { keys = { ":heart:" }, file = "peepoblush.tga", picker = ":heart:" },
        { keys = { ":broken_heart:" }, file = "sadge.tga", picker = nil },
        { keys = { ":thinking:", ":thonk:" }, file = "thonk.tga", picker = ":thinking:" },
        { keys = { ":wink:" }, file = "soysmug.tga", picker = nil },
        { keys = { ":pog:" }, file = "pog.tga", picker = ":pog:" },
        { keys = { ":clown:" }, file = "peepoclown.tga", picker = ":clown:" },
        { keys = { ":sus:" }, file = "sus.tga", picker = ":sus:" },
        { keys = { ":joy:", ":'%)", ";'%)" }, file = "pepelaugh.tga", picker = ":joy:" },
        { keys = { ":rage:", "D:<" }, file = "reallymad.tga", picker = ":rage:" },
        { keys = { ":blush:", ":%$" }, file = "peepoblush.tga", picker = nil },
        { keys = { ":sob:", ";o;" }, file = "sadding.tga", picker = ":sob:" },
        { keys = { ":scream:", ":o", ":%-o", ":%-O", ":O", ":%-0" }, file = "shocked.tga", picker = nil },
        { keys = { ":sunglasses:", "8%)", "8%-%)" }, file = "soysmug.tga", picker = nil },
        { keys = { ":thumbs_up:", ":%+1:" }, file = "based.tga", picker = ":thumbs_up:" },
        { keys = { ":middle_finger:", ":F", ",,!,," }, file = "madge.tga", picker = nil },
        { keys = { ":monkas:", ":monka:" }, file = "monkas.tga", picker = ":monkas:" },
        { keys = { ":slight_frown:" }, file = "sadge.tga", picker = nil },
        { keys = { ":open_mouth:" }, file = "shocked.tga", picker = nil },
        { keys = { ":stuck_out_tongue:" }, file = "blehhhh.tga", picker = nil },
        { keys = { ":stuck_out_tongue_closed_eyes:", "XP" }, file = "nyehehehe.tga", picker = nil },
        { keys = { ":smirk:", ":S", ":%-S" }, file = "sideeye.tga", picker = nil },
        { keys = { ":scream_cat:", ":o3" }, file = "confusedcat.tga", picker = nil },
        { keys = { ":semi_colon:", ":;:" }, file = "hmm.tga", picker = nil },
        { keys = { ":meaw:" }, file = "weirdcat.tga", picker = nil },
        { keys = { ":poop:" }, file = "eww.tga", picker = nil },
        { keys = { ":ok_hand:" }, file = "ok.tga", picker = nil },
        { keys = { ":call_me:" }, file = "based.tga", picker = nil },
        { keys = { ":heart_eyes:" }, file = "catblush.tga", picker = nil },
        { keys = { ":sadkitty:" }, file = "sadcat.tga", picker = nil },
        { keys = { ":zzz:" }, file = "waiting.tga", picker = nil },
        { keys = { ":%-%)", ":%)" }, file = "peepohappy.tga", picker = nil },
    },
    buttonIcon = "peepohappy.tga",
}
