local _, ns = ...
ns.AddonListLocale = ns.AddonListLocale or {}
local Private = ns.AddonListLocale

local Locale = GetLocale()

if Locale == "deDE" then
	Private.ADDON_LIST = "AddOn-Liste"
	Private.ADDON_DEPENDENCIES = "Abhängigkeiten:"
	Private.ADDON_FORCE_LOAD = "Veraltete Addons laden"
	Private.REQUIRES_RELOAD = "Erfordert Neuladen"
	Private.LOAD_ADDON = "AddOn laden"
	Private.ENABLE_ALL_ADDONS = "Alle aktivieren"
	Private.DISABLE_ALL_ADDONS = "Alle deaktivieren"
	Private.RELOADUI = "Neu laden"
	Private.ENABLED_FOR_SOME = "Für einige Charaktere aktiviert"
	Private.LIBRARIES = "Bibliotheken"
elseif Locale == "esES" then
	Private.ADDON_LIST = "Lista de addons"
	Private.ADDON_DEPENDENCIES = "Archivos necesarios: "
	Private.ADDON_FORCE_LOAD = "Cargar addons antiguos"
	Private.REQUIRES_RELOAD = "Se necesita reiniciar"
	Private.LOAD_ADDON = "Cargar addon"
	Private.ENABLE_ALL_ADDONS = "Marcar todo"
	Private.DISABLE_ALL_ADDONS = "Desmarcar"
	Private.RELOADUI = "Reiniciar IU"
	Private.ENABLED_FOR_SOME = "Activado para algunos personajes"
	Private.LIBRARIES = "Bibliotecas"
elseif Locale == "esMX" then
	Private.ADDON_LIST = "Accesorios"
	Private.ADDON_DEPENDENCIES = "Archivos imprescindibles: "
	Private.ADDON_FORCE_LOAD = "Cargar accesorios antiguos"
	Private.REQUIRES_RELOAD = "Requiere recarga"
	Private.LOAD_ADDON = "Cargar accesorio"
	Private.ENABLE_ALL_ADDONS = "Activar todo"
	Private.DISABLE_ALL_ADDONS = "Desactivar todo"
	Private.RELOADUI = "Recargar"
	Private.ENABLED_FOR_SOME = "Activado para algunos personajes"
	Private.LIBRARIES = "Bibliotecas"
elseif Locale == "frFR" then
	Private.ADDON_LIST = "Liste des add-ons"
	Private.ADDON_DEPENDENCIES = "Dépendances : "
	Private.ADDON_FORCE_LOAD = "Charger les add-ons périmés"
	Private.REQUIRES_RELOAD = "Recharger l'interface"
	Private.LOAD_ADDON = "Charger"
	Private.ENABLE_ALL_ADDONS = "Activer tous"
	Private.DISABLE_ALL_ADDONS = "Désactiver tous"
	Private.RELOADUI = "Recharger"
	Private.ENABLED_FOR_SOME = "Activé pour certains personnages"
	Private.LIBRARIES = "Bibliothèques"
elseif Locale == "koKR" then
	Private.ADDON_LIST = "애드온 목록"
	Private.ADDON_DEPENDENCIES = "추가 구성 요소:"
	Private.ADDON_FORCE_LOAD = "구버전 애드온 불러오기"
	Private.REQUIRES_RELOAD = "다시 불러오기 필요"
	Private.LOAD_ADDON = "애드온 불러오기"
	Private.ENABLE_ALL_ADDONS = "모두 사용"
	Private.DISABLE_ALL_ADDONS = "모두 사용 안 함"
	Private.RELOADUI = "UI 재시작"
	Private.ENABLED_FOR_SOME = "일부 캐릭터만 사용"
	Private.LIBRARIES = "라이브러리"
elseif Locale == "ruRU" then
	Private.ADDON_LIST = "Модификации"
	Private.ADDON_DEPENDENCIES = "Зависимые ресурсы: "
	Private.ADDON_FORCE_LOAD = "Устаревшие модификации"
	Private.REQUIRES_RELOAD = "Перезагрузите интерф."
	Private.LOAD_ADDON = "Загрузить модификацию"
	Private.ENABLE_ALL_ADDONS = "Включить все"
	Private.DISABLE_ALL_ADDONS = "Отключить все"
	Private.RELOADUI = "Перезагрузка"
	Private.ENABLED_FOR_SOME = "Включено для некоторых персонажей"
	Private.LIBRARIES = "Библиотеки"
elseif Locale == "zhCN" then
	Private.ADDON_LIST = "插件列表"
	Private.ADDON_DEPENDENCIES = "依赖功能："
	Private.ADDON_FORCE_LOAD = "加载过期插件"
	Private.REQUIRES_RELOAD = "需要重新加载"
	Private.LOAD_ADDON = "加载插件"
	Private.ENABLE_ALL_ADDONS = "全部启用"
	Private.DISABLE_ALL_ADDONS = "全部禁用"
	Private.RELOADUI = "重新加载UI"
	Private.ENABLED_FOR_SOME = "对部分角色启用"
	Private.LIBRARIES = "函数库"
elseif Locale == "zhTW" then
	Private.ADDON_LIST = "插件列表"
	Private.ADDON_DEPENDENCIES = "關聯功能："
	Private.ADDON_FORCE_LOAD = "載入過期插件"
	Private.REQUIRES_RELOAD = "必須重新載入"
	Private.LOAD_ADDON = "載入插件"
	Private.ENABLE_ALL_ADDONS = "全部啟用"
	Private.DISABLE_ALL_ADDONS = "全部停用"
	Private.RELOADUI = "重新載入"
	Private.ENABLED_FOR_SOME = "對部分角色啟用"
	Private.LIBRARIES = "函式庫"
else
	Private.ADDON_LIST = "AddOn List"
	Private.ADDON_DEPENDENCIES = "Dependencies: "
	Private.ADDON_FORCE_LOAD = "Load out of date AddOns"
	Private.REQUIRES_RELOAD = "Requires Reload"
	Private.LOAD_ADDON = "Load AddOn"
	Private.ENABLE_ALL_ADDONS = "Enable All"
	Private.DISABLE_ALL_ADDONS = "Disable All"
	Private.RELOADUI = "Reload UI"
	Private.ENABLED_FOR_SOME = "Enabled for some characters"
	Private.LIBRARIES = "Libraries"
end
