-- Bundled recommended profile for 2K displays (from author preset "Сарыч 13.07").
-- Profile key "Sarych" is a read-only recommended template for 2K.
-- Selecting it clones into the character profile ("Name - Realm").
-- Do not edit this file by hand unless updating the recommended preset.

SarychUI = SarychUI or {}
SarychUI.BuiltinProfiles = SarychUI.BuiltinProfiles or {}
SarychUI.BuiltinProfileMeta = SarychUI.BuiltinProfileMeta or {}

SarychUI.BuiltinProfileMeta["Sarych"] = {
	revision = 1,
	displayName = "Sarych (2K)",
}

SarychUI.BuiltinProfiles["Sarych"] = {
			["modules"] = {
				["map"] = {
					["mapType"] = "classic",
				},
				["frame"] = {
					["targetFrameX"] = -240.0000032825875,
					["focusFrameX"] = 350.0000179174567,
					["frameScale"] = 1.05,
					["changeScale"] = 1,
					["previousFrameScale"] = 1.05,
					["focusFrameY"] = -149.9999976748339,
					["playerFrameX"] = -514.0000149084182,
					["combatIndicatorScale"] = 0.8500000000000001,
					["targetFrameY"] = 200.0000027354896,
					["playerFrameY"] = 200.0000027354896,
				},
				["mainmenubar"] = {
					["microMenuAlpha"] = 1,
					["colorCooldownAlpha"] = 0.6000000000000001,
				},
				["plates_auras"] = {
					["useAwesomeWotlk"] = true,
					["spells"] = {
						[22570] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[9005] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[18498] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[34490] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[3034] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[1776] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[11113] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[3044] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[18658] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[13181] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[19185] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47585] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[58875] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[33357] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[67769] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[23920] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[6131] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[20910] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[642] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[51514] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[2565] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[14327] = {
							["customPriority"] = true,
							["priority"] = 7,
						},
						[55666] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[49039] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[2060] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[2061] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[51690] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[51722] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[11305] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[18499] = {
							["customPriority"] = true,
							["priority"] = 7,
						},
						[12355] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[50461] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[59164] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[1044] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[9852] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[6213] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[20711] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[5195] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[69369] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[61336] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[71988] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[2094] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[43020] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[19306] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[50334] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[48817] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[47843] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47859] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[57073] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[19386] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[27067] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[13553] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[47476] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[1062] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[66] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[17925] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[2637] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[133] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[5782] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[1833] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[27187] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[16188] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[2139] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[63685] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[33041] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[35101] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[1330] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[64803] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[25295] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[64356] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[47541] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[54216] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[22812] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[48707] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[8643] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[47813] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[7922] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[20904] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[14308] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[27068] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[14324] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[49011] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[676] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[116] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[29703] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[18469] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[44572] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[26669] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[49203] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[403] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[20066] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[57970] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[43183] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[33043] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[18118] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[20170] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[9853] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[49012] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[49028] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[64901] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[686] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[53308] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[33395] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[12472] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[8034] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[26989] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47847] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[31117] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[31125] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[8056] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[53548] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[53564] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[13554] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[47528] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[8983] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[118] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[45548] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[13099] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[28730] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[50259] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[47241] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[64695] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[31884] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[55050] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[17] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[24259] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[48998] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[47481] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[51585] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[71] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[18223] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[54428] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[27006] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[8178] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[50436] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[5116] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[5118] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[31661] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[53566] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[13810] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[48999] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[45438] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[2825] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[72] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[17928] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[13327] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[120] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[30216] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[44544] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[58373] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[24132] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[64058] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[53359] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[48792] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[30823] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[3355] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[58597] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[60210] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[18647] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[34692] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[64346] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[24394] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[15487] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[10308] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[47864] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[772] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[47465] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[5019] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[43012] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[12798] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[24364] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[5143] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[331] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[53312] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[8676] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[51209] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6136] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[19821] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[339] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[71586] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[10955] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[14030] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[29166] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[53562] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[55021] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[8936] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[31589] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[5246] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[8004] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[53568] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[58179] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47484] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[6789] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[19388] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[42917] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[12042] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[42949] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[46968] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[53201] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[30217] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[55277] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[39796] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6215] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[3409] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[16166] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[16979] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[55080] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[45334] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[27223] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[61391] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[19574] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47788] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[51693] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[47860] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[23694] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[20511] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[5185] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[54748] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[4167] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[3600] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[6673] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[1715] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[50519] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[64843] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[605] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[53] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6346] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[75] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[42950] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[1719] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[6358] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[20253] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[19750] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[61394] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[48156] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[19263] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[1978] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[12721] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[60995] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[635] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[48066] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[34471] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[11719] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[48300] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[48827] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[64044] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[14309] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[64205] = {
							["customPriority"] = true,
							["priority"] = 7,
						},
						[18425] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[865] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[32182] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[47486] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[26090] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[10230] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[2974] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[27088] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[5384] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[47502] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[55694] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[12809] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[33206] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[31224] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[498] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[10278] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[48125] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[19503] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47986] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[24133] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[20549] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[2458] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[2457] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[43180] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[19387] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[49802] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[57994] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[871] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[50396] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[10326] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[39965] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[9823] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[9827] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[58617] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[25771] = {
							["customPriority"] = true,
							["priority"] = 10,
						},
						[19647] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6615] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[20685] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[17116] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[18657] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[53565] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[19184] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[51724] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6940] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[20230] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[14325] = {
							["enabled"] = true,
							["type"] = "other",
							["customPriority"] = true,
							["priority"] = 100,
						},
						[33786] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[1752] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[5196] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[12323] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[53567] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[12975] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[54833] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[10060] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[3411] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[53313] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[122] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[49803] = {
							["customPriority"] = true,
							["priority"] = 5,
						},
						[5484] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[17926] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[12494] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[10890] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[5242] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[20271] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[55536] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[20909] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[63529] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[47610] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[31821] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[18708] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[6552] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[64804] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[33042] = {
							["customPriority"] = true,
							["priority"] = 4,
						},
						[46924] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[51713] = {
							["customPriority"] = true,
							["priority"] = 3,
						},
						[1766] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
						[54706] = {
							["customPriority"] = true,
							["priority"] = 6,
						},
						[45524] = {
							["customPriority"] = true,
							["priority"] = 2,
						},
						[48672] = {
							["customPriority"] = true,
							["priority"] = 1,
						},
					},
					["profileVersion"] = 4,
					["profiles"] = {
						["elvui"] = {
							["display"] = {
								["scale"] = 0.8,
							},
							["positions"] = {
								["RightX"] = 10,
								["RightY"] = 0,
							},
						},
					},
				},
				["chat"] = {
					["emotionPickerEnabled"] = 1,
					["chatWheel"] = {
						["selectedPhraseFontSize"] = 50,
						["phrase5Y"] = -15,
						["phrase5Text"] = "Назад! :poggies:",
						["phrase2X"] = -60,
						["phrase8X"] = 15,
						["phrase3Text"] = ")))",
						["phrase6X"] = 15,
						["phrase4X"] = -15,
						["phraseFontSize"] = 18,
						["phrase1Text"] = "Спасибо! <3",
						["key"] = "Y",
						["debugBoxHeight"] = 93,
						["debugBoxX"] = -1,
						["phrase7X"] = 15,
						["phrase1Y"] = 15,
						["debugBoxWidth"] = 93,
						["phrase2Text"] = "Хорошо сыграно! :ok:",
						["debugCircleTestEnabled"] = 1,
						["phrase3Emote"] = "/смех",
						["phrase2Emote"] = "/рад",
						["phrase4Text"] = "GG :based:",
						["phrase1Emote"] = "/спасибо",
						["phraseOffset"] = 79,
						["phrase5Emote"] = "/бежать",
					},
				},
				["minimap"] = {
					["minimapSavedA"] = "TOPRIGHT",
					["minimapSavedX"] = -5,
					["minimapSavedR"] = "TOPRIGHT",
					["addonButtons"] = {
						["icons"] = {
							["LibDBIcon10_WCollections - Transmogrify"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 320,
								["managed"] = true,
								["scale"] = 1,
							},
							["LibDBIcon10_LibDBIcon10_AtlasLoot"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 190,
								["managed"] = true,
								["scale"] = 1,
							},
							["NXMiniMapBut"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 225,
								["managed"] = true,
								["scale"] = 1,
							},
							["FindGroupFrameMinimapButton"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 225,
								["managed"] = true,
								["scale"] = 1,
							},
							["LibDBIcon10_WCollections - Collections"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 300,
								["managed"] = true,
								["scale"] = 1,
							},
							["LibDBIcon10_Questie"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 225,
								["managed"] = true,
								["scale"] = 1,
							},
							["TransmorpherMinimapButton"] = {
								["radius"] = 82,
								["shown"] = true,
								["angle"] = 340,
								["managed"] = true,
								["scale"] = 1,
							},
						},
					},
					["minimapSavedY"] = -5,
				},
				["floating_text"] = {
					["raidBossEmoteOffsetY"] = -650,
					["healShiftLess"] = 0,
				},
				["tools"] = {
					["blizzMoveFrames"] = {
						["QuestLogFrame"] = {
						},
						["TradeSkillFrame"] = {
						},
						["ClassTrainerFrame"] = {
						},
						["LFRParentFrame"] = {
						},
						["GameMenuFrame"] = {
						},
						["CharacterFrame"] = {
							["point"] = "LEFT",
							["relativePoint"] = "LEFT",
							["scale"] = 1.5,
							["xOfs"] = 178.0180286543901,
							["save"] = false,
							["yOfs"] = 40.00001805423122,
						},
						["MailFrame"] = {
						},
						["BarberShopFrame"] = {
						},
						["FriendsFrame"] = {
						},
						["GossipFrame"] = {
						},
						["InspectFrame"] = {
						},
						["MerchantFrame"] = {
						},
						["HelpFrame"] = {
						},
						["DressUpFrame"] = {
						},
						["VideoOptionsFrame"] = {
						},
						["BankFrame"] = {
						},
						["PlayerTalentFrame"] = {
						},
						["LootFrame"] = {
						},
						["SpellBookFrame"] = {
						},
						["InterfaceOptionsFrame"] = {
						},
						["ItemSocketingFrame"] = {
						},
						["LFDParentFrame"] = {
						},
						["QuestFrame"] = {
						},
						["TradeFrame"] = {
						},
						["PVPParentFrame"] = {
						},
					},
					["tooltipCursorAltOnly"] = 0,
					["fpsExtraOffsetY"] = -20,
					["fpsExtraOffsetX"] = -12,
					["fpsScale"] = 0.9,
				},
				["arena"] = {
					["distanceAlpha"] = false,
					["useAwesomeWotlk"] = true,
				},
				["cursor"] = {
					["enabled"] = true,
				},
				["bags"] = {
					["elvui"] = {
						["bagFont"] = "Arial Narrow",
						["savedWindowPosition"] = {
							["y"] = 129,
							["relativeTo"] = "UIParent",
							["point"] = "BOTTOMRIGHT",
							["relativePoint"] = "BOTTOMRIGHT",
							["x"] = -134,
						},
					},
				},
			},
			["coordination"] = {
				["bagnonFtDecoupled"] = true,
				["lootIndependentMigrated"] = true,
			},
			["addons"] = {
				["Postal"] = {
					["enabled"] = true,
				},
				["Mapster"] = {
					["enabled"] = false,
				},
				["UnitFrameLayers"] = {
					["playerClassColorHP"] = true,
				},
				["Cursor"] = {
					["enabled"] = true,
					["legacyMigrated"] = true,
					["cursors"] = {
						{
							["Enabled"] = true,
							["Type"] = "Trail",
							["Name"] = "Layer 1",
							["Value"] = "Electric, blue",
							["Strata"] = "TOOLTIP",
						}, -- [1]
						{
							["Enabled"] = true,
							["Type"] = "Particle",
							["Name"] = "Layer 2",
							["Value"] = "Fire, blue",
							["Strata"] = "FULLSCREEN_DIALOG",
						}, -- [2]
						{
							["Enabled"] = false,
							["Strata"] = "FULLSCREEN_DIALOG",
							["Name"] = "Layer 3",
							["Value"] = "",
							["Type"] = "",
						}, -- [3]
					},
					["sets"] = {
						["Face Melter (Warning, bright!)"] = {
							"Laser|1|LOW||spells\\cthuneeyeattack|1.5|.4|32|13", -- [1]
							"Heat|1|BACKGROUND||spells\\deathanddecay_area_base", -- [2]
							"Smoke|1|BACKGROUND||spells\\sandvortex_state_base", -- [3]
						},
						["Shadow trail"] = {
							"Layer 1|1|TOOLTIP|Trail|Shadow|0.5", -- [1]
							"Layer 2|1|FULLSCREEN_DIALOG|Particle|Shadow cloud", -- [2]
							"Layer 3||FULLSCREEN_DIALOG", -- [3]
						},
						["Energy beam"] = {
							"Layer 1|1|TOOLTIP|Trail|Electric, blue", -- [1]
							"Layer 2|1|FULLSCREEN_DIALOG|Particle|Fire, blue", -- [2]
							"Layer 3||FULLSCREEN_DIALOG", -- [3]
						},
					},
				},
				["Bagnon_FT"] = {
					["showOnAlt"] = true,
				},
				["LootHistory"] = {
					["lootTabButtonEnabled"] = true,
				},
			},
		}
